### ISSUE TITLE
Trying to figure out how to properly install dependencies for the physics engine

### ISSUE THREAD

**Issue by iShotFT** [ValkyrienSkies/Valkyrien-Skies-2#1001]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [ ] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Not as much an issue as it is a request to provide instruction on how to install the required libraries used by the physics engine, in this particular situation I was using the 'Minecraft Unlimited' modpack with these mods:

- valkyrienskies-119-2.1.2-beta.1.jar
- eureka-1192-1.5.1-beta.2.jar
- clockwork-1.19.2-0.1.13-forge-4621aeec07.jar

**Forge**: 1.19.2-43.3.0

The server itself was running containerized, I first used the default Java 17 yolk that pterodactyl provides, however after a few days of debugging I decided to build my own Dockerfile to try to ensure all requirements were met. This is the Dockerfile I ended up with before giving up:

```Dockerfile
FROM --platform=$TARGETOS/$TARGETARCH eclipse-temurin:17-jdk-jammy

# VS-specific environment variables
ENV LD_LIBRARY_PATH=/home/container/.vs-natives:/usr/lib/x86_64-linux-gnu:/usr/lib:/home/container
ENV JAVA_TOOL_OPTIONS="-Djava.library.path=/home/container/.vs-natives:/usr/lib/x86_64-linux-gnu:/usr/lib:/home/container"
ENV VS_USE_MOCK_PHYSICS=false
ENV VS_PREFER_JNI=true
ENV MALLOC_ARENA_MAX=2

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        lsof \
        curl \
        ca-certificates \
        openssl \
        git \
        tar \
        sqlite3 \
        fontconfig \
        libfreetype6 \
        tzdata \
        iproute2 \
        libstdc++6 \
        binutils \
        build-essential \
        libc6-dev \
        libgcc1 \
        libc6 \
        libssl-dev \
        libffi-dev \
        libxml2-dev \
        zlib1g-dev \
        libbz2-dev \
        libxrender1 \
        libxtst6 \
        libxi6 \
        numactl \
        libopengl0 \
    && rm -rf /var/lib/apt/lists/* \
    && ldconfig \
    && useradd -d /home/container -m container

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

# Create VS natives directory
RUN mkdir -p /home/container/.vs-natives

COPY ./../entrypoint.sh /entrypoint.sh
CMD [ "/bin/bash", "/entrypoint.sh" ]
```

All of those packages were installed on the host machine as well, speaking of which:

**Host machine:**
```
OS: Ubuntu 24.04.1 LTS x86_64
Kernel: 6.8.0-48-generic
CPU: AMD Ryzen 9 7950X3D (32) @ 5.759GHz
GPU: AMD ATI 0b:00.0 Raphael
Memory: 6729MiB / 128017MiB
```

However, when the server tries to boot, it seems to be pushing the physic engine too far and eventually crashes out with the following error: [hs_err_pid1.log](https://github.com/user-attachments/files/17748919/hs_err_pid1.log)

All dependencies are correctly installed, I eventually got frustrated and gave up, removing all vs2 related mods from the pack. After this, the server booted just fine.

I would love to add these mods back to the pack but while this issue persists, I can't push myself to smash my head against the wall over and over again without properly asking for some guidance as to what dependencies are required. The server in question is hosted on Hetzner (`sudo dmidecode -s system-manufacturer: ASUS`) and as far as I know, I should be able to install anything required over ssh.

### Issue reproduction

- Ubuntu 24.04.1 LTS x86_64
- Using pterodactyl & wings, install the '[Minecraft Unlimited](https://www.curseforge.com/minecraft/modpacks/hazardousdaniels-unlimited)' modpack
- Run server (when using pterodactyl, the server is ran in a Docker container)
- Crash

**Comment by thetheaplant** [comment]
See https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/826#issuecomment-2094226933, pterodactyl needs some configuration changes to work with vs.

**Comment by iShotFT** [comment]
Thanks for the response @thetheaplant, appreciate it, seems like I didn't find that github comment in the hours of trying to find a solution. It would be great if some note / warning was present in the docs or in the readme that points this out. I agree that it's a third-party solution, but still. Thanks again!

**Comment by iShotFT** [comment]
Closing issue

**Comment by thetheaplant** [comment]
> Thanks for the response @thetheaplant, appreciate it, seems like I didn't find that github comment in the hours of trying to find a solution. It would be great if some note / warning was present in the docs or in the readme that points this out. I agree that it's a third-party solution, but still. Thanks again!

Added to https://wiki.valkyrienskies.org/wiki/Compatibility_list?wvprov=sticky-header#Virtual_Machine_Support

**Comment by iShotFT** [comment]
Appreciate you <3
