### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Explode007** [ValkyrienSkies/Valkyrien-Skies-2#1002]
### Mod Name

Oculus

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Cannot load Oculus when utilizing any VS2 addons including VS Tournament, Clockwork, and Eureka.

Unsure if this is a known issue, I saw a few posts, but none seemed to narrow it down. There was one about a server crash and lateinit; that same thing is happening here.

Expectation: All mods load and I can make machines with shadows :)
Reality: Can play game with epic machines but no pretty shadows :(

### Issue reproduction

Install Specified addons, Add Oculus, Game won't load.

### Logs

https://mclo.gs/M76UGta

**Comment by thetheaplant** [comment]
Find the specific problem mod, create a save with just that mod, vs, and kotlin, and see if it launches. If it crashes, send the crashlog. If it doesn't, then re-add your other mods until it breaks, then send the crashlog. Occulus 1.7.0 is the version I confirmed to be working, so if it keeps crashing then use that version.

**Comment by Explode007** [comment]
It's on 1.20.x, even though I had selected that. (sorry if this was misleading)

I Now ran it with VS and each addon separately and found a couple of things. The main culprits are CC:VS and VS Tournament. Disabling CC:VS (along with CC) allows the game to run with trackwork and tournament. When I include CC:VS, the game launches if Tournament is disabled.

Crash w/Tournament&CC: https://mclo.gs/783z1R0

**Comment by thetheaplant** [comment]
Unable to recreate with specified mods. Check your modlist for mods you didn't mention.

**Comment by thetheaplant** [comment]
Unable to recreate
