### ISSUE TITLE
Automatically disable block face culling for ships on Sodium

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies-2#1003]

**Comment by xiewuzhiying** [comment]
https://github.com/xiewuzhiying/VS-Addition/blob/1.20.1/main/fabric/src/main/java/io/github/xiewuzhiying/vs_addition/fabric/mixin/sodium/client/MixinDefaultChunkRenderer.java
👍

**Comment by xiewuzhiying** [comment]
To be honest, I actually prefer to have it working normally rather than disabling it, but I don't know how to do it.

**Comment by Rubydesic** [comment]
I will look into fixing it properly later, but for now, this fix is good enough. Thanks!!

**Comment by xiewuzhiying** [comment]
I tried to transform the `origin` using the `worldToShip` matrix to the shipyard coordinates, but it did not work as expected.
