### ISSUE TITLE
No source code for vs-core?

### ISSUE THREAD

**Issue by heipiao233** [ValkyrienSkies/Valkyrien-Skies-2#1007]
Didn't that violate LGPL?

**Comment by PriestOfFerns** [comment]
Vs-core is ARR, not LGPL, so it doesn’t violate LGPL

**Comment by heipiao233** [comment]
> Vs-core is ARR, not LGPL, so it doesn’t violate LGPL

No.

LGPL v3:
> This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below.

GPL v3 section 1:
> The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities. However, it does not include the work's System Libraries, or general-purpose tools or generally available free programs which are used unmodified in performing those activities but which are not part of the work. For example, Corresponding Source includes interface definition files associated with source files for the work, and the source code for shared libraries and dynamically linked subprograms that the work is specifically designed to require, such as by intimate data communication or control flow between those subprograms and other parts of the work.
This term is *not* an exception in LGPL v3.

VS2 needs vs-core to run, and it isn't a "System Library", so "vs-core" is a part of the "Corresponding Source" of VS2. So vs-core must be under a license that compatible with (L)GPL. Including non-free software vs-core in "free" software VS2 violates LGPL.

**Comment by PriestOfFerns** [comment]
@heipiao233 software licenses exist to protect licensors, licensors don't serve the license. The only issue that could come up from this would be getting sued by the owner of a GPL-incompatible library, for using it in a GPL project. Which is why the GNU license FAQ has an entire section about using GPL-incompatible libraries in GPL-licensed software ([see here](![image](https://github.com/user-attachments/assets/b1cd4a3d-b9f3-43c5-8dd9-bf0d2922956a))).

Since vs_core is owned by the same people as VS2, there aren't any legal issues caused by using a GPL-incompatible library in a GPL-licensed software (Unless VS2 devs decide to sue themselves for violating their own copyright)

**Comment by Codetoil** [comment]
The [GNU Website](https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs), if I am reading it correctly, seems to say or at least imply that if you don't write out an explicit exception in your `LICENSE` file, it doesn't apply... which is it probably not what you want.

> If you want your program to link against a library not covered by the system library exception, you need to provide permission to do that. Below are two example license notices that you can use to do that; one for GPLv3, and the other for GPLv2. In either case, you should put this text in each file to which you are granting this permission.
> 
> Only the copyright holders for the program can legally release their software under these terms. If you wrote the whole program yourself, then assuming your employer or school does not claim the copyright, you are the copyright holder—so you can authorize the exception. But if you want to use parts of other GPL-covered programs by other authors in your code, you cannot authorize the exception for them. You have to get the approval of the copyright holders of those programs.

**Comment by blockninja124** [comment]
Where does it say it doesn't apply? The only issue I could see from what you linked is that VS could potentially sue a GPL addon because it depends on vs-core.

(Which we obviously aren't  going to do)

**Comment by heipiao233** [comment]
I was wrong.

**Comment by Codetoil** [comment]
[GPL License Section 7. Additional Terms](https://www.gnu.org/licenses/gpl-3.0.html#:~:text=If%20you%20add,apply%20either%20way.)
> If you add terms to a covered work in accord with this section, you must place, in the relevant source files, a statement of the additional terms that apply to those files, or a notice indicating where to find the applicable terms.
> 
> Additional terms, permissive or non-permissive, may be stated in the form of a separately written license, or stated as exceptions; the above requirements apply either way.
