### ISSUE TITLE
1.20.1, Operating a Pulley on a Ship leads to chunk ban.

### ISSUE THREAD

**Issue by deadkin123** [ValkyrienSkies/Valkyrien-Skies-2#1008]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Using a pulley on a ship, via gearshift and clutch, will chunk ban me, and keep me stuck on 100% while loading into the world.  Deleting the data file for VS did not work, neither did isolating the modpack to VS and Addons including Create (This will cause the entire profile to not be able to load).  
![image](https://github.com/user-attachments/assets/a8c1c758-cdc0-4e09-af08-c624fdc6bacc)

### Issue reproduction

To reproduce the issue, you must make a medium sized airship, make it into a physics object with balloons and a ship helm.  Then glue a wooden plank under the pulley (this is the only block I used, not sure if it's the only block that crashes the game.), then push the pulley downwards.

### Logs

[latest.log](https://github.com/user-attachments/files/17813201/latest.log)
[debug.log](https://github.com/user-attachments/files/17813203/debug.log)

**Comment by thetheaplant** [comment]
I've been unable to reproduce this issue, it's been mentioned a few times and is probably related to the "aabb is too big" issue.

**Comment by thetheaplant** [comment]
Unable to reproduce.
