### ISSUE TITLE
<title>A bug between the item "flap" and "cushion".

### ISSUE THREAD

**Issue by anyan114514** [ValkyrienSkies/Valkyrien-Skies-2#1013]
### Mod Name

VS Toutnament mod/Clockwork: Create x Valkyrien Skies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When I was building an airplane with "flap", my plane suddenly flew around uncontrollably,  flying thousands or even tens of thousands of blocks in an instant, and then when I searched for this bug on bilibili (a video app) I found that other people had encountered this bug as well, a video described this situation when the physical structure only had flap and seat cushion (white cushion from VS Toutnament mod), so I suspected that it was a problem between flap and seat cushion, but it's also possible that it's not like this, I don't understand mods or anything like that, it could be a conflict between vs and affiliate mods (this passage is translated with translation software, and there may be a language problem)

### Issue reproduction

Create a physical structure with only two blocks (flap below, cushion above)
The structure is then placed in water or dragged on the ground with the "Physics Gun", after which the structure may disappear (fly away) and may be accompanied by severe game stuttering，which may also cause some magical things to happen if you sit on it

### Logs

[2024-11-28-3.log.gz](https://github.com/user-attachments/files/17945136/2024-11-28-3.log.gz)
[latest.log](https://github.com/user-attachments/files/17945137/latest.log)

**Comment by anyan114514** [comment]
![fb14fe92bd5a00c5d1166fae69d2136d](https://github.com/user-attachments/assets/ab2a46b2-0737-4019-a0ca-5ff66a5cd4ff)

**Comment by anyan114514** [comment]
![fb14fe92bd5a00c5d1166fae69d2136d](https://github.com/user-attachments/assets/e3987021-37bc-4679-864c-5b8794c15b10)

**Comment by PriestOfFerns** [comment]
This is an issue with wings. It got fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/945

**Comment by anyan114514** [comment]
I don't know much about it, so what I'm going to do next to fix this in my game.@PriestOfFerns
