### ISSUE TITLE
Valkyrien skies doesn't remove crashed/errored force inducers

### ISSUE THREAD

**Issue by blockninja124** [ValkyrienSkies/Valkyrien-Skies-2#1019]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

If a ship has a force inducer that crashes, VS will crash (to desktop) instead of removing the force inducer. This is most common when removing a mod that adds a force inducer to all/a bunch of ships. Once the mod is removed, the force inducers 'apply forces' function no longer exists, so VS crashes.

This is stupid. There isn't really a way for an addon to code itself so that it can "detect" when it _doesn't exist_ and remove its force inducers. The only decent solution to this is for VS to put a try {} catch {} around calling a force inducer, and if it fails simply log the error once and remove the inducer from the ship.

### Issue reproduction

(Probably do-able with all/most VS addons, but I did it with starlance)
Make a world with starlance, VS and all their dependencies. 
Make a new ship, and put a starlance thruster on it (to attach the force inducer)
Leave the world, remove starlance, and rejoin.
On loading the world it will crash with an error about the force inducer not existing.

### Logs

[crash-2024-12-11_18.50.34-server.txt](https://github.com/user-attachments/files/18100723/crash-2024-12-11_18.50.34-server.txt)

**Comment by Rubydesic** [comment]
It will be fixed in the new api
