### ISSUE TITLE
Game crashes when assembling a ship with create items

### ISSUE THREAD

**Issue by davfrance** [ValkyrienSkies/Valkyrien-Skies-2#1022]
### Mod Name

Create, VS Eureka, Flywheel, Clockwork: Create x Valkyrien Skies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I'm playing on a server and we are trying to create a ship with create and VS Eureka in minecraft 1.20.1 with forge 47.3.12 running the server and 47.3.0 for clients.

We attached a Propeller Bearing to the ship, and are powering it with an electric generator.
When we try to assemble the ship all the clients crash but the server still runs fine.

The crash seems to fix when using flywheel backend instancing, but the ship still shows transparent blocks in some places (this might be related to embeddium).
The issue seems related to flywheel batching that seems incompatible with VS Instancing engine.

### Issue reproduction

Create a ship whit Helm and a running Propeller Bearing(creative engine right click it with a block in front and windmill sails), assemble, then use /flywheel backend batching (this can be done before or after, the result is the same)
This curse export should include my testing world with the ship already built and assembled
[Test.zip](https://github.com/user-attachments/files/18125917/Test.zip)

### Logs

Crash log when it first happened with Oculus and Embeddium: https://mclo.gs/QCFDyvv
[latest.log with Oculus and Embeddium removed](https://github.com/user-attachments/files/18125847/latest.log)
Crash on test modpack: [crash-2024-12-13_12.50.52-client.txt](https://github.com/user-attachments/files/18125949/crash-2024-12-13_12.50.52-client.txt)

**Comment by PriestOfFerns** [comment]
VS2 doesn’t support flywheel batching

**Comment by davfrance** [comment]
> VS2 doesn’t support flywheel batching

is there a reason for this? AMD gpus don't work very well with Instancing. Using create I usually get half moving belts, glitchy textures and so on. It's not game breaking but I would like to understand why that is. Thanks in advance

**Comment by thetheaplant** [comment]
Fixed in #893
