### ISSUE TITLE
Documents for vs-core api

### ISSUE THREAD

**Issue by zyxkad** [ValkyrienSkies/Valkyrien-Skies-2#1031]
### Mod Name

N/A

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

I'm developing a mod that is going to working with VS2. However I cannot find documents or sources refer to vs core. There I want to ask if there are any documents that I missed or I can only try some reverse engineering.

### Issue reproduction

N/A

**Comment by blockninja124** [comment]
I'm not the most knowledge-able person, but as far as I know there isn't any documentation on VS core stuff. And I do know for sure it isn't open source unfortunately, though a good IDE can de-compile it _somewhat_. Oh and there is a very small un-official wiki on various VS stuff at https://github.com/alex-s168/vs2-doc, and some limited java doc scattered around. Again, all of this is just from what I've seen while making addons, I'm not necessarily the best source lol.

**Comment by Rubydesic** [comment]
There are not currently any real documentation for vscore besides the sparse javadocs. If you have any questions feel free to join the discord and ask 

I will be adding documentation soonish along with the new update
