### ISSUE TITLE
Texture not loaded correctly

### ISSUE THREAD

**Issue by ChoChoRPG** [ValkyrienSkies/Valkyrien-Skies-2#1036]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I start to play minecfat vs mod, and then valkskies cannot load texture correctly
my other mods =
-create
-create connected
-create eureka
-eureka ships
-kotlin for forge
-trackwork
-valkyrie skies
![2024-12-26_22 28 46](https://github.com/user-attachments/assets/c3acccc4-3cda-4b37-9f71-0b99788dc304)

### Issue reproduction

idk i just try a new mod that i see on youtube, and this bug happen

### Logs

[latest.log](https://github.com/user-attachments/files/18253741/latest.log)

**Comment by thetheaplant** [comment]
Working as intended.
