### ISSUE TITLE
<title>Trouble the author to update the mod

### ISSUE THREAD

**Issue by anyan114514** [ValkyrienSkies/Valkyrien-Skies-2#1042]
### Mod Name

VS Toutnament mod/Clockwork: Create x Valkyrien Skies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

My problem was raised in #1013, thanks for the solution, but I hope the author will update the new version of the module quickly, because this bug has seriously affected the construction of the physical structure (especially the plane), almost every time I build, I will encounter this problem, my plane will always disappear and cause a waste of hours, this mod is very popular (at least in China) There are many people who like this mod, but everyone has encountered many bugs, although there are ways to fix it, but not everyone will fix the bug by themselves, Most people can only wait for the new version of the mod to be released, so please have time for the author to update the mod

### Issue reproduction

There is a chance that "flap" will appear when it appears in a physical structure (as if "flap" is more likely to appear when it comes into contact with the ground)

**Comment by PriestOfFerns** [comment]
Github issue reports are for reporting actual mod issues, not grievances with mod release dates
