### ISSUE TITLE
Question: What is the time-line on versions? 

### ISSUE THREAD

**Issue by Rushmore75** [ValkyrienSkies/Valkyrien-Skies-2#107]
What's the timeline on minecraft versions? Is the idea to just have vibe on 1.16.5 or is there intent to follow newer versions?

( I didn't see a FAQ of this, sry if I missed it )

**Comment by Rubydesic** [comment]
![Screenshot_20220722-235857](https://user-images.githubusercontent.com/26909616/180589674-9ea6c141-bbe1-4e25-81dc-5951967c588e.jpg)
