### ISSUE TITLE
Make sure survival players can walk on ships on multiplayer

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Valkyrien-Skies-2#114]
Right now the server will probably kick players that walk on ships, or move them back for going too fast. We should probably just disable the movement anti cheat, it doesnt even work properly anyways.

**Comment by StewStrong** [comment]
Maybe in the future we can make a modified version of [Grim](https://github.com/MWHunter/Grim) to detect cheat movement even with VS ships!

**Comment by copperwarrior** [comment]
Disabling the movement anticheat should only happen within the bounds of a ship imo, it's out of scope to completely remove it and could conflict with mods that would affect it.
