### ISSUE TITLE
Liquids flowing off a ship have no limit

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Valkyrien-Skies-2#124]
When a liquid flows off the side of a ship, it will flow down to the shipyard's bedrock unfettered. This is visually cringe, and should be limited to the bounds of the ship. Preventing placement of water or lava on a ship is a temporary solution that does not fix the problem.
Tested on Fabric with a ship assembled by the Eureka ship helm.

**Comment by Rubydesic** [comment]
added a config option to prevent this behaviour
