### ISSUE TITLE
Storage blocks when broken drop their contents in the shipyard

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Valkyrien-Skies-2#125]
This affects chests, dispensers, furnaces, etc. and also affects shulker boxes in creative mode.
Tested on Fabric with a ship built with Eureka's ship helm.

**Comment by ewoudje** [comment]
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/34 (dropped items are entities)
