### ISSUE TITLE
Crash on generating superflat world

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Valkyrien-Skies-2#126]
Left a normal world with ships in it and tried to create a superflat world.
Log: https://gist.github.com/copperwarrior/0282393d923cd481bd109c2e31be0456
Crash Report: https://gist.github.com/copperwarrior/6e8794c598393d506073125abacee94d

**Comment by StewStrong** [comment]
I've seen this bug occur on regular worlds as well. I think its just a bug in `Int2ObjectOpenHashMap`, maybe we should replace that with something else.

**Comment by StewStrong** [comment]
From some digging it looks like this is caused when a map is accessed from 2 threads at the same time https://github.com/vigna/fastutil/issues/42

**Comment by StewStrong** [comment]
I fixed this in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/9160005d31de4749fa9a4d72d090b55ed605d2c9
