### ISSUE TITLE
Quickly closing and reloading a world causes ships to disappear

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Valkyrien-Skies-2#127]
Generated a world, made a small ship, closed the world, reopened the world, ship was gone.
Log: https://gist.github.com/copperwarrior/91192523c77c279a364ac5ccfa8b7b0a
From here, closing the whole game and reloading into the world caused the ship to reappear.
Tested on Fabric with a ship built by the Eureka ship helm.

**Comment by copperwarrior** [comment]
Alleviated on latest commit, but not fixed. Ships are still disappearing, but had to do it 7 times to trigger it.

**Comment by StewStrong** [comment]
I wasn't able to reproduce this after 20 reloads. Closing for now.
