### ISSUE TITLE
How to join your development?

### ISSUE THREAD

**Issue by EnderTheCoder** [ValkyrienSkies/Valkyrien-Skies-2#15]
I've been following this project, but it looks like it's progressing slowly. It's really amazing in 1.12, so I want to participate in this project too. Do you have any public discord server? I'll have plenty of time after May.

**Comment by TechTastic** [comment]
This is their Discord
https://discord.gg/U8dSDzsC

Rn its mainly waiting on the bulk physics code to be finished before anything else

**Comment by EnderTheCoder** [comment]
thanks!
