### ISSUE TITLE
Particles spawned on ships do not inherit the ship's velocity

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Valkyrien-Skies-2#151]
https://gyazo.com/65aec4974320da2a88183ffd7c382715.mp4

Particles on a ship do not inherit the ship's velocity, and therefore create unwanted trails when a ship is moving.

Ideally, the particles should probably be parented to the ship, so that rotation does not also cause the issue.

There should be a way to check for exceptions to this rule, as smokestack particles rising from campfires should be possible.

**Comment by Rubydesic** [comment]
fixed
