### ISSUE TITLE
Fix player to ship collision + movement

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Valkyrien-Skies-2#17]
Currently the Player to Ship collision and movement in VS 2 is inferior to that of VS 1.

We can do better than this!

**Comment by StewStrong** [comment]
It turns out the root cause of this was caused by incorrect behavior of CollisionRangec.computeCollisionResponse() (see [this commit](https://github.com/ValkyrienSkies/vs-core/commit/6525445d02132d914682ac7d1bfe4f58a44face0#diff-c152b5e74296f6c93a428f1b6cc0b731471bff668f7cdec1d39e90c989a165b0L16-L43)).

The fix was to remove velocity from CollisionRangec.computeCollisionResponse() entirely.

Still need to do more work to make players slip down slopes that are too steep to stand on, and to allow players to step up stairs on ships.

**Comment by deltanedas** [comment]
players are also ignored by ships it seems, their collision is "one way"

**Comment by StewStrong** [comment]
It works now!
