### ISSUE TITLE
Explosions appear to crash the game

### ISSUE THREAD

**Issue by CrushFruits** [ValkyrienSkies/Valkyrien-Skies-2#172]
Self explanatory, here are the logs. Happened with a creeper and summoning in TNT. Apparently other people has not had this issue however.
[crash-2022-10-30_11.06.39-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/9895776/crash-2022-10-30_11.06.39-server.txt)

**Comment by Rubydesic** [comment]
fixed in latest
