### ISSUE TITLE
Water Dissapears when Looking through Framed Glass on Ships

### ISSUE THREAD

**Issue by SteelChikorita** [ValkyrienSkies/Valkyrien-Skies-2#188]
Version: 1.0.0-alpha3 , 1.16.5 Forge

repost of ValkyrienSkies/Eureka#35 to include version as asked, and more specific details. Water is seen as transparent when looked at through modded glass on an assembled airship, making oceans dark and shallow river systems disappear entirely. Was discovered whilst using Framed Glass from the Create Mod, regular glass does not display the same effects and renders water properly.

**Comment by SuperCraftAlex** [comment]
i have the same problem with vanilla glass (on forge)

**Comment by thetheaplant** [comment]
Unable to recreate.
