### ISSUE TITLE
limited by world height

### ISSUE THREAD

**Issue by Weromano** [ValkyrienSkies/Valkyrien-Skies-2#197]
when assembling a ship with the shiphelm, the shiphelm will be placed in the shipyard, at the same height it was, in the real world.

Example: i place the shiphelm on height 5 in the real world and assemble my ship, which results in the shiphelm being placed at height 5 in the shipyard as well.
When i am now flying upwards with the ship and try to expand my ship 6 blocks down, it wont work because i reached the world limit.

**Comment by Weromano** [comment]
doing it an other way may result in worse bugs though

**Comment by Rubydesic** [comment]
working as intended
