### ISSUE TITLE
CC: Restitched Speaker sound cannot be heard

### ISSUE THREAD

**Issue by TechTastic** [ValkyrienSkies/Valkyrien-Skies-2#198]
CC: Restitched speaker can be told to play a sound or note

This sound played cannot be heard when the speaker is on a ship which i suspect is probably because its playing in the Shipyard and not world space

Can confirm functionality when not on a ship via Subtitles and having sound on when running this command:
**peripheral.call("right", "playNote", "harp")**

_Right being the side of the computer the speaker is attached to_

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
this is also true for cc:tweaked

**Comment by TechTastic** [comment]
> this is also true for cc:tweaked 

I know, I am doing compatibility code for ComputerCraft right now

I've fixed Speakers, Modems, and am now doing Turtles. Once it is all done, I hope that my changes will be merged into VS2 so these issues are fixed

**Comment by thetheaplant** [comment]
Fixed in #889
