### ISSUE TITLE
Engines on a non assembled ship

### ISSUE THREAD

**Issue by Dayhel** [ValkyrienSkies/Valkyrien-Skies-2#204]
Bug: my entire minecraft completely stopped working, to the point that i cannot close it, minimize it, select it, or do anything with it at all. I have only recreated/tested this three times, since the only way to stop and open minecraft again is by restarting the computer. The world is fine, and when I log back in and enter the world again everything is normal, also the launcher doesn't bring up a crash report.
Circumstances: I placed 9 ship engines as a floor for a boat because I was gonna try to make the fastest land vehicle I could. They have a helm on them, but are not assembled and are still part of the ground. I would take a screenshot but for some reason it's not working. At first I thought it was putting fuel in them while they were not assembled, but on the subsequent two recreations it seems to just lag a bit when I do that, and actually occurs when I tried to shift click a stack of coal blocks into an engine that already had coal blocks in it.
Version/mod list: architectury-419699-3857643, BloodMagic-1.16.4-3.1.13-39, blue_skies-1.16.5-1.1.3, cloth-config-forge-4.16.91, Create 1.16.5 v0.3.2g, curios-forge-1.16.5-4.0.8.2, eureka-1.0.0-alpha4e280cd3b8b, flywheel-1.16-0.2.5, geckolib-forge-1.16.5-3.0.103, H.E.M+V0.4.8M, jei-1.16.5-7.7.1.152, kotlinforforge-351264-3527736, mahoutsukai-1.16.5-v1.34.35, malum-1.16.5-0.3.0, mana-and-artifice-1.5.1.7, minecolonies-1.16.5-1.0.978-RELEASE, Patchouli-1.16.4-53.3, structure_gel-1.16.5-1.7.8, structurize-1.16.5-1.0.418-ALPHA, valkyrienskies-116-2.0.0-alpha44eabb9d19a
Forge version is 1.16.5, 36.2.39

**Comment by dkmk100** [comment]
that's an issue with eureka, not valkyrien skies

also, I'm pretty sure that's the known issue that was already fixed in alpha 5. I suggest you update and see if that fixes the issue

**Comment by Rubydesic** [comment]
Should be fixed in alpha5
