### ISSUE TITLE
game won't load up on mac

### ISSUE THREAD

**Issue by cadenthecreator** [ValkyrienSkies/Valkyrien-Skies-2#206]
my game won't load up it is just stuck on the fml early loading process i have even tried it with only Eureka

**Comment by TechTastic** [comment]
Make sure you have ALL dependencies

**Comment by cadenthecreator** [comment]
yeah im stupid

**Comment by cadenthecreator** [comment]
curseforge usually installs the dependencies automatically but it did not

**Comment by cadenthecreator** [comment]
yay its doing stuff
