### ISSUE TITLE
braking the block you are standing on crash

### ISSUE THREAD

**Issue by davidCMs** [ValkyrienSkies/Valkyrien-Skies-2#213]
braking the block you are standing on crashes the server and only the server while controling the ship

**Comment by Rubydesic** [comment]
Send logs

**Comment by davidCMs** [comment]
[crash-2022-11-09_14.45.28-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/9973052/crash-2022-11-09_14.45.28-server.txt)

**Comment by thetheaplant** [comment]
Unable to recreate.
