### ISSUE TITLE
Random ticks stop almost completley with VS2 installed

### ISSUE THREAD

**Issue by AlexSaph** [ValkyrienSkies/Valkyrien-Skies-2#217]
With VS2 installed, I noticed whenever I'm standing anywhere near what needs to grow, crops stop growing, dry farmland stays dry even when it's next to water, leaves don't decay, and saplings don't grow. I've tried to increase tick speed though commands and still nothing changes. If I move far enough away from them (about 12 chunks away,) it continues to grow but much slower than normal. This issue persists to different worlds and the only thing that seems to fix the problem is disabling the mod through curseforge.

**Comment by dkmk100** [comment]
I also noticed this

**Comment by fauxtrauxt** [comment]
seconded/thirded, spent days thinking it was PamsHCcrops doing it but whittled it down today to Valkyrien.

**Comment by sawyer-jack-1** [comment]
I am experiencing the same issue

**Comment by Rubydesic** [comment]
should be fixed in latest
