### ISSUE TITLE
weird water lava and trees came out nowhere

### ISSUE THREAD

**Issue by FrankLuis285467** [ValkyrienSkies/Valkyrien-Skies-2#230]
weird trees and water lavas attach from far away to the ship in server plays
![2022-11-25_23 57 27](https://user-images.githubusercontent.com/119064999/204020871-200ab3fa-878f-4d71-92d8-5fd1ab81694f.png)
![2022-11-25_23 57 21](https://user-images.githubusercontent.com/119064999/204020887-82696207-3676-47d6-8f76-e52fc6a8b817.png)
like this just came out of nowhere when assembling ship

**Comment by Rubydesic** [comment]
Are you using a bukkit hybrid like magma or mohist? I've seen this problem with those in vs1 before. Otherwise it might be an incompatibility with a terrain gen mod.
