### ISSUE TITLE
Latest rubidium does not work with the latest 1.18 forge package

### ISSUE THREAD

**Issue by bloo-tree** [ValkyrienSkies/Valkyrien-Skies-2#234]
I was messing around with the latest 1.18 forge package (valkyrienskies-118-forge-2.1.0-alpha1+fe4d606020.jar) because I noticed it was on there and I wanted to check compatibility with my mod pack.
upon messing around with it I found that rubidium had lost compatibility and was making it so the top texture of the blocks were not rendering as seen in the image.
I know the image contains other mods but I made absolutely sure it was rubidium.
I also know this is still an unreleased version I just wanted to make sure this was known.
![rubbidium support](https://user-images.githubusercontent.com/110029345/205368329-387bc400-b32e-4764-a0b9-44b2d767de5f.png)

**Comment by Rubydesic** [comment]
Don't make issues for unreleased versions, if you want to report issues with unreleased versions do it on discord thru the playtesters channel thank you
