### ISSUE TITLE
How to fix: Minetogether incompatibility

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies-2#237]
MineTogether is incomaptible. I need them to fix this issue. For now you can use a patched version of the JAR. (extract the zip file, github doesn't let me upload JARs) [minetogether-forge-1.18.2-5.2.8.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10188762/minetogether-forge-1.18.2-5.2.8.zip)

https://github.com/CreeperHost/MineTogether/pull/689

**Comment by bullet23232** [comment]
thx

**Comment by walksanatora** [comment]
i think it has been merged 😄 
(it may say closed but they merged manually)

**Comment by ewoudje** [comment]
It was merged in dec 12 and latest release is from jan 19, im closing this then.
