### ISSUE TITLE
Incompatible with Combat-Commons

### ISSUE THREAD

**Issue by dasi666** [ValkyrienSkies/Valkyrien-Skies-2#238]
I wanted to use Biomancy(mod) with VS2 but when I load its library(Combat-Commons) it crashes. 
I only have 5 mods(VS2 and its 2 libraries, and Biomancy with its 1 library).
Maybe its because Combat-Commons is also imcompatible with Dungeons Gear.

**Comment by Rubydesic** [comment]
please post latest.log and reopen
