### ISSUE TITLE
Weird spam of a error line. 1.16.5

### ISSUE THREAD

**Issue by XxsjrapsxX** [ValkyrienSkies/Valkyrien-Skies-2#241]
game keeps spamming "Too many physics frames in the physics frame queue. Is the game stage broken?" in my modded server. Provided the config below. 

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10199457/latest.log)

**Comment by XxsjrapsxX** [comment]
if you need i can also send a mod list for what im running to see if there are any mod incompatabilities that show up and cause this interaction, cause it only seems to have an issue when on servers

**Comment by Rubydesic** [comment]
not an error, just a warning that shows up basically all the time
