### ISSUE TITLE
incompatible with the Create Big Cannons mod, cannon does not function correctly

### ISSUE THREAD

**Issue by NullHarp** [ValkyrienSkies/Valkyrien-Skies-2#242]
the cannon can fire into the world and assembles fine, but the placement of the cannon entity, and the location of where the shot is fired in relation to the physical location and aim of the cannon is completly off, curseforge link to cbc can be found here https://www.curseforge.com/minecraft/mc-mods/create-big-cannons

**Comment by thetheaplant** [comment]
Unable to recreate.
