### ISSUE TITLE
1.18 beta; ClassMetadataNotFoundException: kotlin.jvm.functions.Function0

### ISSUE THREAD

**Issue by dennisorlando** [ValkyrienSkies/Valkyrien-Skies-2#245]
Hi,
I built the gradle project but the game crashes on startup (with Exit code: 1) with this ^ error message.
I just tried with the beta jars released on curseforge but I'm getting the same error.
Is this a mod-related problem or is it a pc-side error?

I'm getting the same error on Windows and on Linux. On Linux, I tried with java 17 and also java 19.
Forge version: 1.18.2 - 40.1.86

I got the exact same error by cloning "Eureka" and running "gradlew :forge:runClient"

full log:
[https://pastebin.com/4wj5zEhd](url)

**Comment by ThePlasticPotato** [comment]
Do you have KotlinForForge in your mods folder?

**Comment by dennisorlando** [comment]
Woops :)

(No, I didn't lol)
