### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by sungho955** [ValkyrienSkies/Valkyrien-Skies-2#247]
[hs_err_pid2556.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10204529/hs_err_pid2556.log)

lastest lost :(

**Comment by sungho955** [comment]
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10204788/latest.log)

**Comment by Rubydesic** [comment]
Looks like you ran out of memory. Maybe allocate less memory to Minecraft
