### ISSUE TITLE
Ship blocks not rendering

### ISSUE THREAD

**Issue by DesPro111** [ValkyrienSkies/Valkyrien-Skies-2#248]
![2022-12-12_08 23 37](https://user-images.githubusercontent.com/120329750/207539913-5c338d26-0369-43ff-81a7-41262451ccdc.png)
![2022-12-12_08 24 22](https://user-images.githubusercontent.com/120329750/207539924-d3340880-a1a2-45c6-a950-2756d64256eb.png)

**Comment by StewStrong** [comment]
I cant access it, can you post the image using markdown? Like this `![alt text](https://play-lh.googleusercontent.com/8ddL1kuoNUB5vUvgDVjYY3_6HwQcrg1K2fd_R8soD-e2QYj8fT9cfhfh3G0hnSruLKec)`
![alt text](https://play-lh.googleusercontent.com/8ddL1kuoNUB5vUvgDVjYY3_6HwQcrg1K2fd_R8soD-e2QYj8fT9cfhfh3G0hnSruLKec)

**Comment by Rubydesic** [comment]
What version and what rendering mods do you have installed? Optifine is not supported on 1.18 and questionably supported on 1.16

**Comment by DesPro111** [comment]
> What version and what rendering mods do you have installed? Optifine is not supported on 1.18 and questionably supported on 1.16

1.18

**Comment by Rubydesic** [comment]
Use rubidium instead
