### ISSUE TITLE
Game refuses to start up; Exit Code: 1

### ISSUE THREAD

**Issue by scigeotech** [ValkyrienSkies/Valkyrien-Skies-2#249]
Debug Log: https://pastebin.com/i27myKaE
Latest Log: https://pastebin.com/pWmq36p3
Launcher Log: https://pastebin.com/rsM4cZdp

**Comment by Rubydesic** [comment]
This doesn't seem like a complete log, please upload the latest.log and debug.log after the game has crashed.

**Comment by scigeotech** [comment]
I started the game again and it shows the same message about Exit Code: 1, but the debug and latest log looks the same:

Debug Log: https://pastebin.com/cuX8D1qr
Latest Log: https://pastebin.com/Wfh19auF

I've also noticed that the launcher log isn't public on github (pending moderation), so I'm going to upload the file here.
[launcher_log.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10211473/launcher_log.txt)

**Comment by Rubydesic** [comment]
Looks like a mod compat issue that shouldn't exist but does thanks to forge's system of loading every mod as a module. Looks like a mod called "annotateddi" is shading javax.inject rather than JIJing it (which it shouldn't), so this is an issue with them and not VS.

**Comment by scigeotech** [comment]
Thanks for the quick diagnosis, I've been a big fan of your mod since 1.12.2 so I'm very excited to try it on 1.18.2.
