### ISSUE TITLE
Server Crash when Player Disconnects (Forge 1.18.2)

### ISSUE THREAD

**Issue by HoodBlah** [ValkyrienSkies/Valkyrien-Skies-2#254]
When a player disconnects from the server all other players are also kicked out and the server crashes. This line in the Debug log seems to be the issue.

 [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.valkyrienskies.core.apigame.world.ServerShipWorldCore.onDisconnect(org.valkyrienskies.core.apigame.world.IPlayer)" because the return value of "org.valkyrienskies.mod.common.VSGameUtilsKt.getShipObjectWorld(net.minecraft.server.MinecraftServer)" is null

The full Debug log is also attached.
[debug-1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10225063/debug-1.log)

**Comment by Rubydesic** [comment]
This seems like a mod compat issue, if you can narrow down which mod is causing it we can help further.

**Comment by Rubydesic** [comment]
Reopen the issue if you have any insights.
