### ISSUE TITLE
Create mod crashes while pondering and pressing identify (because of VS according to crash log)

### ISSUE THREAD

**Issue by Warhamm2000** [ValkyrienSkies/Valkyrien-Skies-2#256]
With Create mod and VS enabled together, trying to ponder and pressing identify while pondering cause crashing
Detailed info: https://github.com/Creators-of-Create/Create/issues/4142

**Comment by Rubydesic** [comment]
This issue is fixed in the 1.18 version of VS, I may backport it at some point

**Comment by thetheaplant** [comment]
Unable to recreate.
