### ISSUE TITLE
[1.18.2-2.1.0-beta3]Forge server start failed with create and Valkyrien

### ISSUE THREAD

**Issue by Rikka-Lyn** [ValkyrienSkies/Valkyrien-Skies-2#261]
Server start failed when I only installed create and Valkyrien.
Client worked with this set.

Here is the crash-report and logs:
https://pastebin.com/FYsSj1dQ
https://pastebin.com/EDjLkerQ
https://pastebin.com/rE0NrfdL

Valkyrien Version : valkyrienskies-118-2.1.0-beta3.jar
Create Version : create-1.18.2-0.5.0.e.jar

**Comment by Rubydesic** [comment]
fixed it
