### ISSUE TITLE
Eureka fails to load with VS2 1.18.2-2.1.0 beta6

### ISSUE THREAD

**Issue by strontix** [ValkyrienSkies/Valkyrien-Skies-2#266]
Using latest forge for 1.18.2 40.1.86 fails to load eureka upon startup and forces you to quit the game (with VS2 2.1.0 beta6)
40.1.69 does work however, this could be a eureka problem and not VS but its worth looking into
[2022-12-17-1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10252436/2022-12-17-1.log) 
might be wrong log, to reproduce this bug just install beta6 of VS 2.1.0 for 1.18 and use latest forge and eureka v1.1.0-beta1

**Comment by Rubydesic** [comment]
fixed in latest
