### ISSUE TITLE
VS2 1.18.2-2.1.0 beta6 client crash after assembling ship on multiplayer server

### ISSUE THREAD

**Issue by strontix** [ValkyrienSkies/Valkyrien-Skies-2#267]
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10252467/debug.log)
[crash-2022-12-17_12.12.10-fml.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10252468/crash-2022-12-17_12.12.10-fml.txt)

The client (not the server however) crashes after assembling a ship on multiplayer, upon reconnecting any attempt to render the ship results in a crash.

Forge ver 40.1.69

**Comment by ThePlasticPotato** [comment]
that crash log is the one you sent before, from failing to load- it's not for this issue.

**Comment by Rubydesic** [comment]
Please update to the latest version of Eureka.
