### ISSUE TITLE
[116-2.0.0-alpha6] Valkyrien Skies 2 (valkyrienskies) has failed to load correctly

### ISSUE THREAD

**Issue by Sablam** [ValkyrienSkies/Valkyrien-Skies-2#271]
Hi,

Once I activate more than 23 mods and Valkyrian Sky, the game won't start with the message: Valkyrien Skies 2 (valkyrienskies) has failed to load correctly. With 23 mods or less and Valkyrian Sky it work ok. What the other mods are don't seem to change the result. 
I use Curseforge launcher.

Version: valkyrienskies-116-2.0.0-alpha6.jar for minecraft 1.16.5
Tested with both Forge 36.2.34 and Forge 36.2.39

Here the crash report:
[crash-2022-12-18_21.21.20-fml.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10254577/crash-2022-12-18_21.21.20-fml.txt)

**Comment by Rubydesic** [comment]
Lol the problem has nothing to do with the amount of mods, but the other mod that you're adding (which might be OTG, judging by the crash log) - you need to say which mod is causing the issue for us to fix it. If it's OTG, we need to wait for OTG to fix it I can't do anything

**Comment by Sablam** [comment]
Ok you are right it pass throught my tests.
I will change the title in case other people find the same error.

Thank you.

**Comment by Rubydesic** [comment]
## Workaround for this issue:

Delete `com/fasterxml/jackson/databind` folder inside of the OTG jar file
