### ISSUE TITLE
I can not lunch the game

### ISSUE THREAD

**Issue by ShiinaYeZi** [ValkyrienSkies/Valkyrien-Skies-2#272]
Hello author, I have some problems, can you help me (my English is not too good, I use translation software, maybe my words will be rude).The version of Minecraft is 1.12.2
[minecraft-exported-logs-2022-12-19T09-07-21.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10255140/minecraft-exported-logs-2022-12-19T09-07-21.log)

**Comment by Rubydesic** [comment]
1.12 is no longer supported, sorry.

**Comment by ShiinaYeZi** [comment]
It's okay~, I found out that I was conflicting because of the mod, I'm debugging, thank you to the author for providing us with such a powerful mod, thank you author!!!!!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月19日(星期一) 上午9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ValkyrienSkies/Valkyrien-Skies-2] I can not lunch the game (Issue #272)





 
1.12 is no longer supported, sorry.
