### ISSUE TITLE
[1.18.2] Crash. Rendering screen

### ISSUE THREAD

**Issue by Proxwian** [ValkyrienSkies/Valkyrien-Skies-2#282]
[crash-2022-12-22_14.49.56-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10284839/crash-2022-12-22_14.49.56-client.txt)

[modlist.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10284849/modlist.2.txt)

**Comment by Rubydesic** [comment]
Looks like an issue with FancyMenu

**Comment by Proxwian** [comment]
Not fixed in beta9.

Also, why do you don't provide changelog for versions? That's inadmissible.

**Comment by walksanatora** [comment]
it is a beta
the only changelog would be internal changes
inwhich case just look at the git commits

**Comment by Rubydesic** [comment]
fixed in latest
