### ISSUE TITLE
[question] 1.18+

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ValkyrienSkies/Valkyrien-Skies-2#283]
I was just wondering if any version above 1.18 is planned or being worked on?

**Comment by ThePlasticPotato** [comment]
Most certainly not a priority, though I’d imagine a 1.20 version may come eventually whenever 1.20 releases. Mojang really enjoys fucking over their entire codebase every update, so it’s not worth it to version chase updates with little actual content.

**Comment by StewStrong** [comment]
There is a 1.19 version, though we need to do some refactoring to support multiple versions more easily.

**Comment by Aces-and-Jacks** [comment]
Well I get that. Doing every up part for a big mod would seem like a lot to do. Hopefully they stick to just doing minor changes for small updates (1.19, 1.19.1, ect) and big changes for big updates (1.18, 1.19, 1.20, ect)

**Comment by karateka8899** [comment]
tho 1.19.2 is pretty big as for mod variety, could be a main version for modpacks
