### ISSUE TITLE
projectiles don't rotate on 1.18

### ISSUE THREAD

**Issue by dkmk100** [ValkyrienSkies/Valkyrien-Skies-2#286]
projectiles from things like dispensers don't rotate to the ship's orientation when fired. Affects both vanilla and modded blocks.

![image](https://user-images.githubusercontent.com/33072952/209244223-00698818-a551-4740-8643-7ad36d531491.png)

**Comment by dkmk100** [comment]
isn't this the same as #303 ? which was closed and is supposedly fixed?

**Comment by walksanatora** [comment]
i mean i see Ars: Nouveau stuff on the airship soo
but yeah it *should* have been fixed
mabey they need to update VS version
