### ISSUE TITLE
does not render in ViveCraft

### ISSUE THREAD

**Issue by walksanatora** [ValkyrienSkies/Valkyrien-Skies-2#290]
(see issue over there [https://github.com/ferriarnus/VivecraftMod/issues/95](https://github.com/ferriarnus/VivecraftMod/issues/95))
Valkrien Skies 2 ships do not render in ViveCraft
you can create them
and block outlines do show up where you are pointing your cursor
but the blocks are invisible

**Comment by DJHugal** [comment]
Interesting, they show just fine for me, the only thing that does not work at all is when you try to control the boat, the view gets horribly distorted.

**Comment by walksanatora** [comment]
note: was playing QuestCraft so it was ViveCraft mixin Fabric

**Comment by DarianLStephens** [comment]
I haven't experienced anything unusual on the rendering side, but I had problems trying to control them with Eureka; I couldn't effectively move _forwards_ only, and had to rapidly switch left and right in order to make progress.

**Comment by thetheaplant** [comment]
Seems resolved, unable to recreate.
