### ISSUE TITLE
CTD when assembling ship using Eureka, Forge 40.1.92, Valk 118 2.1.0 Beta7, Eureka 1.1.0 beta 4

### ISSUE THREAD

**Issue by Jacob345k** [ValkyrienSkies/Valkyrien-Skies-2#292]
Er pids linked in chat, please let me know if anything else is needed! It also chops my ships into 1/4ths for some reason.
[hs_err_pid14460.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10327444/hs_err_pid14460.log)
[hs_err_pid8240.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10327445/hs_err_pid8240.log)

**Comment by Rubydesic** [comment]
Create 0.5g is incompatible
