### ISSUE TITLE
Crash with Structurize

### ISSUE THREAD

**Issue by emanuele246gi** [ValkyrienSkies/Valkyrien-Skies-2#293]
Minecraft Version:
1.18

Structurize Version
1.0.424-ALPHA

Valkyrien Skies Version
118-2.1.0-beta7

It's not the latest Structurize's version because Minecolonies doesn't work with it.
I tried to render a customized build with the building tool, then it crashed.
https://pastebin.com/TfvV6Tyy (crash report)

**Comment by walksanatora** [comment]
> minecolonies
... *ah*
iirc minecolonies is a known incompatabiity

**Comment by emanuele246gi** [comment]
I actually didn't do anything that used both mods, it happened when I was just using Minecolonies/Structurize, in that moment

**Comment by ThePlasticPotato** [comment]
Minecolonies and structurize are both completely incompatible.

**Comment by emanuele246gi** [comment]
How? The first requires the second, they are incompatible if they are different versions, Minecolonies devs say which version is required in the changelog

**Comment by ThePlasticPotato** [comment]
Vs2 is incompatible with both

**Comment by koap1** [comment]
when you right click with structurize tools on vs2 ships the game crashes

**Comment by emanuele246gi** [comment]
I didn't do anything with Valkyrien Skies, I was just doing things with Structurize, I completely didn't touch VS2

**Comment by walksanatora** [comment]
What part of Incompatible dont you understand @emanuele246gi

**Comment by emanuele246gi** [comment]
I know it's not compatible, I made this post because of this, calm down

**Comment by emanuele246gi** [comment]
I only explained what I did

**Comment by ThePlasticPotato** [comment]
VS2 is incompatible with structurize totally. It’s not surprising that it’d break on you even without using vs2 ships.

**Comment by ThePlasticPotato** [comment]
Ye I know, sorry, was just clarifying- ignore walks’s hostility, someone must’ve taken a dump in his Frosted Flakes this morning
