### ISSUE TITLE
Open Claims and Parties support

### ISSUE THREAD

**Issue by kristibektashi** [ValkyrienSkies/Valkyrien-Skies-2#294]

**Comment by Rubydesic** [comment]
No idea what this means

**Comment by kristibektashi** [comment]
> No idea what this means

My bad, I should've given a better explanation

Basically what I am requesting is adding support for this mod:
https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims
so that ships can't be interacted with if they're in a claimed area

**Comment by Rubydesic** [comment]
@TechTastic added support for FTB Chunks, it will be in the next release

**Comment by walksanatora** [comment]
if you ask nicely in the discord he (or someone else) may add open parties and claims 
i would but that would require learning another API
although the API should be similar to FTB so it should be some modifications from that

**Comment by kristibektashi** [comment]
This should be reopned, it is a valid feature request

**Comment by kristibektashi** [comment]
> @TechTastic added support for FTB Chunks, it will be in the next release

I don't understand your point. I know that FTB Chunks support was added, but what's the issue with also supporting Open Claims and Parties?

**Comment by TechTastic** [comment]
> > @TechTastic added support for FTB Chunks, it will be in the next release
> 
> I don't understand your point. I know that FTB Chunks support was added, but what's the issue with also supporting Open Claims and Parties?

Their point is that I did that in my free time and it was not a priority for VS2 Devs

If you want it done for your mid in particular, you'll have faster results if you do it yourself
