### ISSUE TITLE
The game crashes with only VS2, Eureka and their dependencies installed

### ISSUE THREAD

**Issue by ImSpaceLover** [ValkyrienSkies/Valkyrien-Skies-2#308]
Mods:
valkyrienskies-118-2.1.0-beta7.jar
architectury-4.10.88-forge.jar
eureka-1.1.0-beta4.jar
cloth-config-6.4.90-forge.jar

debug.log:
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10368667/debug.log)

latest.log:
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10368669/latest.log)

**Comment by ImSpaceLover** [comment]
I forgot to mention that the game crashes with Exit code 1

**Comment by Rubydesic** [comment]
You're missing kotlin for forge and you don't need cloth config or architectury
