### ISSUE TITLE
Incompatible with most content in fabric create [1.18.2]

### ISSUE THREAD

**Issue by aD-1337** [ValkyrienSkies/Valkyrien-Skies-2#310]
The content of the fabric create (such as creating engine, transmission lever, etc.) placed on the physical structure of the fabric valkyrienSkies does not work. I have submitted this question on the github project issue page of fabric create. Their reply is that there is a problem with the compatibility of valkyrienSkies with flywheel. I hope to improve the compatibility of fabric valkyrienSkies with fabric create which the forge version can.
thanks

**Comment by Rubydesic** [comment]
This will be all solved with the release of Clockwork. Watch our Discord for progress :)
