### ISSUE TITLE
Issues with Ender Storage

### ISSUE THREAD

**Issue by SyntheticSeraph** [ValkyrienSkies/Valkyrien-Skies-2#312]
When running this mod alongside Eureka and Ender Storage/Ender Tanks, you are no longer able to interact with the ender storage items in any way. You cannot dye them, or open them. Functionally they still accept items, but you can only access the chest through using an Ender Pouch.

**Comment by walksanatora** [comment]
you can dye them via crafting*
but not the in-world method

**Comment by SyntheticSeraph** [comment]
It's not -just- dyeing them. You can't interact with it at all. The chests won't open.

**Comment by jpalutke** [comment]
Same issue... None of us on our server can interact with either the Ender Chests or Ender Tanks... _You can access the chests with an Ender Pouch._

**Comment by Inferius77** [comment]
same here.   we jsut added VS to our server thats been up for a month.  cant use the ender storage after adding VS, Eureka, VS computers.

Also i cant run a //regen command via worldedit.
https://pastebin.com/2rBjUUzU

**Comment by KajesLorian** [comment]
Problem still persists. Setting up a 1.18.2 server and unable to interact with Ender Chests with VS Eureka installed.

**Comment by AirplanegoBrr** [comment]
Still a problem, 1.18.2, 40.2.0 (However I am using clockwork, but it seems like this is a problem with VS)
Is this an Ender Storage problem or VS problem? And is this being looked into???
You can't Open, Change color, or set it private, the pouch does still work, but it shouldn't have to be like that

**Comment by StewStrong** [comment]
Fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/93fd59898f94b124ee777a33818b72c9b5a002e8
