### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by Readf0x** [ValkyrienSkies/Valkyrien-Skies-2#317]
Upon loading the game with no mods except eureka and valkyrien skies, it will crash with exit code 2. It must be pretty early on or with forge itself because it doesn't even spit out a crash report.
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10397039/latest.log)

**Comment by Readf0x** [comment]
forgot to specify, playing on 1.18.2, with version 2.1.0-beta7 of valkyrien skies 2 and version 1.1.0-beta4 of Eureka

**Comment by Rubydesic** [comment]
You didn't install Kotlin for Forge

**Comment by Readf0x** [comment]
Thank you! I couldn't find any dependencies on curseforge so I just assumed it was standalone, guess I didn't read hard enough, sorry for taking up your time!
