### ISSUE TITLE
Breaking all blocks on a ship while controlling it will tp you to crazy far coordinates and the world will generate no blocks

### ISSUE THREAD

**Issue by ToxicGold180** [ValkyrienSkies/Valkyrien-Skies-2#318]
If you destroy all blocks on a ship (including the helm) will controlling said ship, you teleport to crazy far coordinates in a place with no blocks, it happens every time I've tried it. Here's a screenshot I took of this strange place:
![Imgur](https://i.imgur.com/d3zVhLp.png)

**Comment by walksanatora** [comment]
welcome to the shipyard

**Comment by Rubydesic** [comment]
#307 dupe
