### ISSUE TITLE
teleport to ship's chunk after sleeping

### ISSUE THREAD

**Issue by supershorty1** [ValkyrienSkies/Valkyrien-Skies-2#319]
using vs 1.18beta9
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10398615/latest.log)

**Comment by Rubydesic** [comment]
We need to re-add the setPosRaw mixin that I removed in 26720096406bfd2f71642eb5ec5e3c315b895f50 but only trigger it for player entities

**Comment by Rubydesic** [comment]
fixed
