### ISSUE TITLE
[1.18.2 Forge] I can't create or load singleplayer worlds

### ISSUE THREAD

**Issue by MrTophatMan** [ValkyrienSkies/Valkyrien-Skies-2#325]
Every time I try to create one the world starts the creation process and then the game crashes.

Mods:
Valkyrien skies Forge beta9
Optifine
Eureka beta4
Kotlin 3.9.1

Crash report (this appears every time I try):

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'

**Comment by Kuzex** [comment]
Did you give version enough ram?

**Comment by MrTophatMan** [comment]
Normally mods work with 2 GB but I tried 4GB and it didn't work, same crash report.

**Comment by Quickburst** [comment]
You did not send full crash report. It should be in crash report folder. Try again.

**Comment by MrTophatMan** [comment]
[crash-2023-01-15_08.21.39-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10420263/crash-2023-01-15_08.21.39-server.txt)

**Comment by Rubydesic** [comment]
send your full latest.log please

**Comment by MrTophatMan** [comment]
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10471428/latest.log)
There

**Comment by Rubydesic** [comment]
sorry, I didn't read your mods list. Optifine is not supported on 1.18+ please use rubidium or oculus
