### ISSUE TITLE
invisible ships

### ISSUE THREAD

**Issue by CosmosFury13** [ValkyrienSkies/Valkyrien-Skies-2#338]
im playing in 1.18.2 and whenever i assemble a ship its invisible but still flies

**Comment by copperwarrior** [comment]
Do you have any other mods installed?

**Comment by AtQm1x** [comment]
i have the same issue, im playing with optifine and create mod installed

**Comment by Rubydesic** [comment]
Use rubidium and oculus, optifine is not supported

**Comment by CosmosFury13** [comment]
I’m not using optifine I’m already using rubidium and oculus

**Comment by Rubydesic** [comment]
Upload your latest.log and mod list

**Comment by CosmosFury13** [comment]
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10418580/latest.log)

**Comment by Theoyeah** [comment]
man i also have that... i wanted to try but impossible with this bug

**Comment by oliverrook** [comment]
Same here.
I don't even get anything in my latest.log
Checked several times through everything since my world generated and there's not a single error message.

**Comment by Rubydesic** [comment]
too many mods to tell honestly, please re-open a new issue with only VS and the mod that causes the issue
