### ISSUE TITLE
Any block/interaction on ship creates entities in the shipyard

### ISSUE THREAD

**Issue by deltanedas** [ValkyrienSkies/Valkyrien-Skies-2#34]
tnt being lit, dispensers, etc all spawn their entities in the shipyard. mixin required for each thing, or maybe correct entity position if it gets spawned in the shipyard.

**Comment by ewoudje** [comment]
A way of fixing this is for every entity in the shipyard to tp it to the normal world; 
Or another way that makes pathfinding inside ships easier is letting the entities live inside the shipyard and render them in the ship and then ofc also raytracing etc should be modified for this.

**Comment by deltanedas** [comment]
would probably also help with physics + make minecarts aligned to ship

**Comment by copperwarrior** [comment]
Seems to be mostly fixed as of latest commit, there are some exceptions:
 - Minecarts:
![image](https://user-images.githubusercontent.com/17477758/182491726-54b3cbb9-bbd6-4797-84a7-ae97b2aabdc6.png)
 - Paintings
 - Spawn eggs
 - Item frames
 - Armor stands
 - Lit TNT

**Comment by deltanedas** [comment]
all of the above still dont render

**Comment by Andy608** [comment]
Any updates on this? Item frames and Armor Stands don't seem to work. I placed an armor stand on my ship and I can't break it or place any armor on it.
