### ISSUE TITLE
Crash on open Multiplayer Menu (Probably a FM incompatibility)

### ISSUE THREAD

**Issue by SrRapero720** [ValkyrienSkies/Valkyrien-Skies-2#343]
**WHAT's Happen**
New version `(valkyrienskies-118-2.1.0-beta9.jar) (eureka-1.1.0-beta5.jar)` of eureka, causes game crash on open Multiplayer menu (with a FM override customization), i really dont know how to replicated in other menu.

**FILES**
Crash Report: [crash-2023-01-15_05.11.28-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10419997/crash-2023-01-15_05.11.28-client.txt)
Log: [latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10419998/latest.log)
Debug: [debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10420000/debug.log)

**Comment by Rubydesic** [comment]
fixed in beta10
