### ISSUE TITLE
Additional Mod Incompatibilities that I've discovered

### ISSUE THREAD

**Issue by bloxspace12345** [ValkyrienSkies/Valkyrien-Skies-2#350]
Hello, I know that this addon is still in a current alpha phase, however I wanted to make you aware of some mod incompatibility issues that I've encountered most recently involving some of the mods listed below:

- Magnesium/Rubidium Extras [by TeamDeusVult]: "Causes Rendering Errors for Half of Modeled Entities"
	(Alternative: Rubidium, Rubidium Extras, and Rubidium Toolkit seems to be a somewhat decent workaround);

- Performant [by someaddon]: "Causes Issues with entities colliding with ships/ mobs phase through without collisions"
	(Alternative: Have this addon completely uninstalled if you want entity collisions with your ships)

- TRansliterationLib [by tr9zw]: "Trying to access config files using a config menu will cause the game to Crash"
	(Alternative: Do not open VS/Eureka configs through the a game menu using mods like Catalogue/Configured and etc.)

**Comment by ewoudje** [comment]
Im closing this since this is for 1.16, and we aren't updating that version anymore
