### ISSUE TITLE
Shipyard Respawn issues

### ISSUE THREAD

**Issue by TwentyWrong** [ValkyrienSkies/Valkyrien-Skies-2#351]
Whenever you respawn on a ship in the shipyard and go to the helm, it teleports you back to the ship outside the shipyard, but also locks your mouse to vertical movement and you cant leave the helm without /tp.
How to replicate: 
Place bed in ship, right click bed, type /kill in chat, go to helm, right click, presto! you broke the game

No (Besides Prerequisetes)

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/10416304/latest.log)
Didnt have a debug log.

**Comment by Rubydesic** [comment]
fixed in latest
