### ISSUE TITLE
optifine and invisible ships.

### ISSUE THREAD

**Issue by drkeinmann** [ValkyrienSkies/Valkyrien-Skies-2#356]
when getting optifine to work (for some odd reason I need to use optifines 1.18.2 pre 2 h9 or else the game won't start at all on forge) the ships are entirely invisible, however still functional.  
![image](https://user-images.githubusercontent.com/122845433/212792929-b59d6578-ac4e-4a21-9308-43e65b836fbc.png)

**Comment by Quickburst** [comment]
Don't use Optifine. Use Rubidium + Oculus.

**Comment by Rubydesic** [comment]
^

**Comment by suneao** [comment]
thx,same problem

**Comment by thetheaplant** [comment]
Please don't post on closed issues if you are not providing additional information related to the issue.
