### ISSUE TITLE
don't know which versions i need

### ISSUE THREAD

**Issue by Lagas11** [ValkyrienSkies/Valkyrien-Skies-2#360]
I have downloaded 1.16.5 of valkyrien skies and 1.16.5 of fabric but i don't know how to replace minecraft 1.19.3 to 1.16.5 of is there something else i can do??

**Comment by Rubydesic** [comment]
Use PrismLauncher https://prismlauncher.org/ to manage multiple installations of MC for different versions at once. Also if you don't care what version I suggest using 1.18.2
