### ISSUE TITLE
Invisible ship

### ISSUE THREAD

**Issue by IGROBRAT** [ValkyrienSkies/Valkyrien-Skies-2#361]
Just as said before - The moment I assemble the ship it becomes invisible apart from ship helm, it still works however.
The industrial mods that i use are: Create, ValkirienSkies, Eureka! Airships!.
Here is the link to my modpack(Google drive) (https://drive.google.com/drive/folders/1xyqALOFVQ0L03nt5LHdGjtuJ0fIzB1r6?usp=share_link)

**Comment by Rubydesic** [comment]
You have too many mods to tell, please remove some and make a new issue
