### ISSUE TITLE
[FABRIC 1.18.2] Incompatibility with SoundPhysics Remastered when installed on a dedicated server

### ISSUE THREAD

**Issue by 0RadicalLarry0** [ValkyrienSkies/Valkyrien-Skies-2#362]
Server crashes when https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered is installed on a dedicated server.

**Log:**
https://pastebin.com/qa4kj8vs

**Comment by Rubydesic** [comment]
It's a client side mod

**Comment by 0RadicalLarry0** [comment]
It can be installed on the server and if it is, entities sounds can be heard from much further away compared to just being installed on the client. Basically you get the full experience if installed on the server rather than just clients.

**Comment by 0RadicalLarry0** [comment]
> Q: Hwy, just wondering if this mod is server side or client side? I couldnt find anything saying if it was either unless im just blind.

> A: (from dev) Client side, but for a better experience you can also install it on the server
