### ISSUE TITLE
Incompatible with "Immersive Portals" [1.18.2 - forge and fabric both tested]

### ISSUE THREAD

**Issue by ExpertNugget** [ValkyrienSkies/Valkyrien-Skies-2#368]
When both mods are installed the airships from "Eureka! Airships! (Forge/Fabric)" become invisible and no longer interactable, upon player collision of where a ship used to be causes player to become stuck.

Issue reported to both mods.

Fabric Logs:
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10461985/latest.log)
Forge Logs:
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10462001/latest.log)

Both logs taken after completing the same actions:
1) Create creative world (default settings)
2) Made basic airship
3) assembled (this causes the airship to become invisible)
4) exited world

**Comment by tt-thoma** [comment]
Same issue here.

**Comment by TheUndeadOwlGoddess** [comment]
Has there been any update on this issue?

**Comment by Rubydesic** [comment]
Duplicate of #330

**Comment by Nightmar0** [comment]
Um, did you turn off block-face culling in video settings? That might help.

**Comment by thetheaplant** [comment]
Blockface culling is not related to the issue shown.

**Comment by Nightmar0** [comment]
Yeh. UR right. I crashed in 1.18.2 without the game even loading. 🤣🤣
