### ISSUE TITLE
Server Stops responding with Valkyrien skies and Eureka

### ISSUE THREAD

**Issue by Cappuccinussy** [ValkyrienSkies/Valkyrien-Skies-2#377]
Every time i boot up my minecraft server which has 20gb of ram, it relays a failed to start server and gives me these lines before refusing to respond

Server] main/ERROR Failed to start the minecraft server
22.01 03:55:55 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'valkyrienskies'!
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonIgnoreProperties$Value com.fasterxml.jackson.databind.AnnotationIntrospector.findPropertyIgnoralByName(com.fasterxml.jackson.databind.cfg.MapperConfig, com.fasterxml.jackson.databind.introspect.Annotated)'
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.module.jackson.JacksonModule.shouldIgnoreField(JacksonModule.java:270) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGeneratorConfigPart.lambda$shouldIgnore$0(SchemaGeneratorConfigPart.java:131) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGeneratorConfigPart.shouldIgnore(SchemaGeneratorConfigPart.java:131) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.shouldIgnore(SchemaGeneratorConfigImpl.java:292) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.lambda$collectFields$4(SchemaGenerationContextImpl.java:500) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.collectFields(SchemaGenerationContextImpl.java:501) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.collectObjectProperties(SchemaGenerationContextImpl.java:456) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.generateObjectDefinition(SchemaGenerationContextImpl.java:413) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.addSubtypeReferencesInDefinition(SchemaGenerationContextImpl.java:332) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:305) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:243) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.parseType(SchemaGenerationContextImpl.java:96) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaBuilder.createSchemaForSingleType(SchemaBuilder.java:111) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaBuilder.createSingleTypeSchema(SchemaBuilder.java:56) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGenerator.generateSchema(SchemaGenerator.java:60) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.core.impl.config.VSConfigClass$Companion.createSidedVSConfigClass(VSConfigClass.kt:229) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.core.impl.config.VSConfigClass$Companion.registerConfig(VSConfigClass.kt:247) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.mod.common.ValkyrienSkiesMod.init(ValkyrienSkiesMod.java:47) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.mod.fabric.common.ValkyrienSkiesModFabric.onInitialize(ValkyrienSkiesModFabric.kt:77) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO ... 7 more

**Comment by Rubydesic** [comment]
Another mod is shading an incompatible version of jackson. Known offenders are Music Box and OpenTerrainGenerator. Not our problem to fix, but I would appreciate it if you followed up with what mod was causing the issue or added it to our wiki: https://wiki.valkyrienskies.org/wiki/Compatibility_list/1.18

**Comment by Cappuccinussy** [comment]
ill drop my modpack here, i cant seem to find what mod is causing it since I'm not that experience in it
[Origins SMP.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10473746/Origins.SMP.zip)

**Comment by brisingraerowing** [comment]
I used [this SO answer](https://stackoverflow.com/a/1343026) to find the issue in my instance, might be of use to you.

My problem was WaTERMEDIA 2.0.25, which is a dependency for WaTERFrames picture frame mod.

**Comment by SrRapero720** [comment]
Watermedia have not the culprit 
Jackson is relocated on `me.lib720.jackson` and there's no way is interacting with

I answer this because I reshade the library back
