### ISSUE TITLE
server keeps crashing

### ISSUE THREAD

**Issue by Cappuccinussy** [ValkyrienSkies/Valkyrien-Skies-2#378]
heres the error and the pack as well, I cant figure out what mod exactly is causing it, but I do know that a mod is shading an incompatible version of jackson
[Origins SMP.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10473776/Origins.SMP.zip)

Server] main/ERROR Failed to start the minecraft server
22.01 03:55:55 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'valkyrienskies'!
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonIgnoreProperties$Value com.fasterxml.jackson.databind.AnnotationIntrospector.findPropertyIgnoralByName(com.fasterxml.jackson.databind.cfg.MapperConfig, com.fasterxml.jackson.databind.introspect.Annotated)'
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.module.jackson.JacksonModule.shouldIgnoreField(JacksonModule.java:270) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGeneratorConfigPart.lambda$shouldIgnore$0(SchemaGeneratorConfigPart.java:131) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGeneratorConfigPart.shouldIgnore(SchemaGeneratorConfigPart.java:131) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.shouldIgnore(SchemaGeneratorConfigImpl.java:292) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.lambda$collectFields$4(SchemaGenerationContextImpl.java:500) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
22.01 03:55:55 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.collectFields(SchemaGenerationContextImpl.java:501) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.collectObjectProperties(SchemaGenerationContextImpl.java:456) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.generateObjectDefinition(SchemaGenerationContextImpl.java:413) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.addSubtypeReferencesInDefinition(SchemaGenerationContextImpl.java:332) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:305) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:243) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.parseType(SchemaGenerationContextImpl.java:96) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaBuilder.createSchemaForSingleType(SchemaBuilder.java:111) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaBuilder.createSingleTypeSchema(SchemaBuilder.java:56) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at com.github.victools.jsonschema.generator.SchemaGenerator.generateSchema(SchemaGenerator.java:60) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.core.impl.config.VSConfigClass$Companion.createSidedVSConfigClass(VSConfigClass.kt:229) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.core.impl.config.VSConfigClass$Companion.registerConfig(VSConfigClass.kt:247) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.mod.common.ValkyrienSkiesMod.init(ValkyrienSkiesMod.java:47) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at org.valkyrienskies.mod.fabric.common.ValkyrienSkiesModFabric.onInitialize(ValkyrienSkiesModFabric.kt:77) ~[valkyrienskies-118-2.1.0-beta9.jar:?]
22.01 03:55:55 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
22.01 03:55:55 [Server] INFO ... 7 more
[Origins SMP.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10473775/Origins.SMP.zip)

**Comment by Rubydesic** [comment]
Please make a new issue once you know which mod is causing it
