### ISSUE TITLE
Block Rotation Options

### ISSUE THREAD

**Issue by nl1213** [ValkyrienSkies/Valkyrien-Skies-2#379]
Sorry if this is either reported before or already has an option I haven't seen but I think it would be awesome if blocks on ships could have the option to retain their original rotation as opposed to a new one if say the ship was rotated 90 degrees.

This could allow things like stairs to easily realign to their proper rotation and connect with each other or allow create gears to continue to be connected after the ship has fliped direction and then disassembled.

**Comment by copperwarrior** [comment]
On the latest dev versions, disassembling ships rotates blocks correctly relative to where they were rotated to with the ship.

**Comment by gamespuller** [comment]
I dont't know if I should make a new issue for this since the update isnt out, but banners dont keep their pattern when disassembled, but do drop the pattern they had when broken
