### ISSUE TITLE
[Crash] Valkerian skies doesn't work with the essential mod for 1.16 Forge

### ISSUE THREAD

**Issue by Ferogreywolf7** [ValkyrienSkies/Valkyrien-Skies-2#380]
When trying to load the game, it instantly crashes with this shown in the crash log
"java.io.UncheckedIOException: java.nio.file.FileSystemException: **[Folder Directory]**/Essential-forge_1-16-5.jar: The process cannot access the file because it is being used by another process.

at org.valkyrienskies.dependency_downloader.DependencyAnalyzer.lambda$checkDependencies$5(DependencyAnalyzer.java:125) ~[?:?]"

**Comment by tt-thoma** [comment]
Close any other open Minecraft instance and try again

**Comment by thetheaplant** [comment]
Unable to reproduce.
