### ISSUE TITLE
extreem amounts of ram usage

### ISSUE THREAD

**Issue by Shotgn995533** [ValkyrienSkies/Valkyrien-Skies-2#382]
i have a server with some mods including eureka and vs.
the server often says in the console [Physics thread/WARN] [or.va.co.im.pi.VSGamePipelineStage/]: Too many physics frames in the physics frame queue. Is the game stage broken?
and i saw ram usage of upto 9.5gb!!!!!! 
the server runs on 1.18.2 with forge 40.2.0 , eureka 1.1.0-beta5 and vs 118-2.1.1-beta-9

**Comment by thetheaplant** [comment]
Closing in favor of #525
