### ISSUE TITLE
Respawning/sleeping in a bed while on a ship will fling you about 90000000000 block away

### ISSUE THREAD

**Issue by Ripskyofficals** [ValkyrienSkies/Valkyrien-Skies-2#386]
I am not exagerating in both an airship and regular boat generally interacting with a bed while in a ship would fling you away (verrrry far away) first killing you and then softlocking you in some sort of pseudo dimension where you caracter would not be visible and you would not be able to change positons or break anithing, i arleady lost a survival world because of this but, may i ask for it to be fixed?

**Comment by Rubydesic** [comment]
will be fixed in beta10. You can fix it by doing /tp ~ ~ ~

**Comment by Ripskyofficals** [comment]
oh... well it wouldn't help me much because my body would be inacesable and my ship (atempted 100 days as a pirate) is about 10K blocks away, thanks though!

**Comment by walksanatora** [comment]
you have accidently been sent to the shipyard
the tp ~ ~ ~ fixes you and puts you back to the real world
