### ISSUE TITLE
Block alignment and height

### ISSUE THREAD

**Issue by FabulousACDC** [ValkyrienSkies/Valkyrien-Skies-2#390]
Assembling the ship, moving then disassembling the ship causes 2 things in minecraft 1.16.5 (latest version) with eureka. I am posting here as no one seems to have had a problem with block facing on that mod's page. 
1. The ship splits down the middle and one side "disassembles" a block higher than the other side. 
2. Any stairs or similar blocks spin 180 degrees (this gets fixed when assembling and disassembling while stationary)
I would like to preemptively thank you for any time you may have spent reading or answering this

![2023-01-25_04 17 06](https://user-images.githubusercontent.com/117591822/214467714-5d9b8b60-523d-4587-964e-cedb696d2928.png)
![2023-01-25_04 17 27](https://user-images.githubusercontent.com/117591822/214467717-2d9e979b-c25c-460e-b03d-1ccfb87141b7.png)

![2023-01-25_04 28 26](https://user-images.githubusercontent.com/117591822/214467726-786a0cfa-9211-4779-8151-d12038587b48.png)

![2023-01-25_04 31 19](https://user-images.githubusercontent.com/117591822/214467708-0e650fea-978d-4023-9a2b-5b6933089d3b.png)

edit: I have done a bit more of experimenting, it seems the chunk borders are what splits the ship upon disassembly

**Comment by Rubydesic** [comment]
Update to the latest version of VS2 and/or Eureka on Curseforge
