### ISSUE TITLE
crash with magma in 1.18.2

### ISSUE THREAD

**Issue by coco875** [ValkyrienSkies/Valkyrien-Skies-2#392]
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10522179/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10522186/latest.log)
[crash-2023-01-27_19.52.08-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10522202/crash-2023-01-27_19.52.08-server.txt)

**Comment by Rubydesic** [comment]
VS2 generally doesn't support forge/bukkit hybrid servers, but some users have had success with [Arclight](https://github.com/IzzelAliz/Arclight)
