### ISSUE TITLE
Error 1 Doesent load

### ISSUE THREAD

**Issue by vevikpepiktom** [ValkyrienSkies/Valkyrien-Skies-2#397]
When i start minecraft it doesent load up and it crashes 👎 :( pls fix 
![image_2023-01-29_132754001](https://user-images.githubusercontent.com/115349133/215326089-4574d662-cac2-4a4c-be3e-e6851ad76629.png)

**Comment by Rubydesic** [comment]
To help you with your crash I need some more information - please go to your .minecraft/logs folder and upload the "latest.log" and "debug.log" file.
