### ISSUE TITLE
ship is invisible

### ISSUE THREAD

**Issue by MrPotatoguy** [ValkyrienSkies/Valkyrien-Skies-2#398]

**Comment by qqqZXzz123** [comment]
ships are invisible if you use optifine

**Comment by MrPotatoguy** [comment]
oh

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative
