### ISSUE TITLE
Incompatibility with Shimmer mod

### ISSUE THREAD

**Issue by gglobensky** [ValkyrienSkies/Valkyrien-Skies-2#401]
Minecraft 1.18.2
Forge 40.2.1

valkyrienskies-118-2.1.0-beta.10
eureka-1.1.0-beta.6
Shimmer-forge-1.18.2-0.1.14

Can load the world and move around but quickly crashes, sometimes right after moving an inch.

Crash report:
https://pastebin.com/nT7qGnK5

Thanks for the wonderful mod!

**Comment by Rubydesic** [comment]
fixed in 6a23d06550d536df7dfb952bac186928666ed975
