### ISSUE TITLE
Eureka Ships are lagging 

### ISSUE THREAD

**Issue by forest-cat** [ValkyrienSkies/Valkyrien-Skies-2#402]
Alright, so my airships are lagging extremely when using them on the server, also its sending all the time this message: 
`[16:29:02] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8645374650000006E7, 66.0, -377.27189764380455] -> [7206.4025353919715, 156.4461791551314, 1.2290061650000006E7] returning empty list! this might break things
`
My Modlist is this:
- abverticaledition-1.0.2-mc1.18.jar
- AdvancedPeripherals-0.7.23r.jar
- AE2-Additions-1.18.2-0.2.1.jar
- AE2-Things-1.0.4.jar
- ae2extras-2-1.18.2.jar
- AE2WTLib-11.6.3.jar
- AEAdditions-1.18.2-3.2.6.jar
- AEInfinityBooster-1.18.2-1.1.0+9.jar
- Applied-Mekanistics-1.2.2.jar
- appliedenergistics2-forge-11.7.0.jar
- architectury-4.10.88-forge.jar
- Ballistix-1.18.2-0.5.3-3.jar
- balm-3.2.2+0.jar
- betterstats-2.2+1.18.2.jar
- Beyond-Earth-1.18.2-6.2.jar
- buildinggadgets-3.13.1-build.18+mc1.18.2.jar
- caelus-forge-1.18.1-3.0.0.2.jar
- cc-tweaked-1.18.2-1.101.0.jar
- cccbridge-1.3.1-forge.jar
- CCTVCraft_4.3.0_for_1.18.2.jar
- cgm-1.3.3-1.18.2.jar
- chunkloaders-1.2.3-forge-mc1.18.jar
- cloth-config-6.4.90-forge.jar
- cofh_core-1.18.2-9.1.2.32.jar
- collective-1.18.2-6.30.jar
- configured-2.0.0-1.18.2.jar
- connectedglass-1.1.6-forge-mc1.18.jar
- Controlling-forge-1.18.2-9.0+22.jar
- cookingforblockheads-forge-1.18.2-12.2.0.jar
- CraftPresence-2.0.0-alpha.3+1.18.2.jar
- create-1.18.2-0.5.0.h.jar
- create-stuff-additions1.18.2_v2.0.2a.jar
- createaddition-1.18.2-20221219a.jar
- createdeco-1.2.12-1.18.2.jar
- create_connected_blocks-0.5.4.jar
- CreativeCore_FORGE_v2.6.15_mc1.18.2.jar
- CTM-1.18.2-1.1.5+5.jar
- Cucumber-1.18.2-5.1.3.jar
- curios-forge-1.18.2-5.0.7.1.jar
- curiouselytra-forge-1.18.1-5.0.1.0.jar
- Cyclic-1.18.2-1.7.13.jar
- dcintegration-forge-2.6.2-1.18.2.jar
- Ding-1.18-1.3.0.jar
- dynamiclightsreforged-1.18.2_v1.3.3.jar
- Electrodynamics-1.18.2-0.6.4-0.jar
- eureka-1.1.0-beta5.jar
- FastLeafDecay-28.jar
- feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
- FluxNetworks-1.18.2-7.0.8.12.jar
- flywheel-forge-1.18.2-0.6.8.a.jar
- framework-0.4.2-1.18.2.jar
- fullbrightnesstoggle-1.18.2-3.0.jar
- geckolib-forge-1.18-3.0.57.jar
- grappling_hook_mod-1.18.2-v13.jar
- GravitationalModulatingAdditionalUnit-1.18.2-1.9.jar
- ImmersiveEngineering-1.18.2-8.3.0-155.jar
- industrial-foregoing-1.18.2-3.3.1.5-9.jar
- inventorysorter-1.18.2-19.0.4.jar
- ironchest-1.18.2-13.2.11.jar
- ironfurnaces-1.18.2-3.3.3.jar
- itemcollectors-1.1.6-forge-mc1.18.jar
- jei-1.18.2-9.7.2.1001.jar.disabled
- jei-1.18.2-forge-10.2.1.1002.jar
- journeymap-1.18.2-5.9.2-forge.jar
- K-Turrets-1.1.12-1.18.2.jar
- kotlinforforge-3.9.1-all.jar
- longerlogintimes-1.0.0-mc1.18.jar
- loot_journal-1.1.0-1.18.jar
- mcw-doors-1.0.7-mc1.18.2.jar
- Mekanism-1.18.2-10.2.5.465.jar
- MekanismAdditions-1.18.2-10.2.5.465.jar
- MekanismGenerators-1.18.2-10.2.5.465.jar
- MekanismTools-1.18.2-10.2.5.465.jar
- metalbarrels-1.18.2-4.3.jar
- MineTraps-1.18.2-(v.2.1.4).jar
- moreoverlays-1.20.10-mc1.18.2.jar
- MouseTweaks-forge-mc1.18-2.21.jar
- movingelevators-1.3.11-forge-mc1.18.jar
- MysticalAgradditions-1.18.2-5.1.3.jar
- MysticalAgriculture-1.18.2-5.1.3.jar
- MysticalCustomization-1.18.2-3.1.2.jar
- neoncraft2-2.2.jar
- noautojump-1.18.2-1.jar
- oculus-1.4.3a.jar
- oculus-flywheel-compat-1.18.2-0.1.8-BETA.jar
- OfflineSkins-1.18.2-v2.jar
- PackMenu-1.18.2-4.1.4.jar
- Patchouli-1.18.2-71.1.jar
- Placebo-1.18.2-6.6.6.jar
- PlayerRevive_FORGE_v2.0.13_mc1.18.2.jar
- radium-0.7.10.jar
- radon-0.8.1.jar
- recruits-1.18.2-1.8.4.jar
- refinedstorage-1.10.4.jar
- refinedstorageaddons-0.8.2.jar
- repurposed_structures_forge-5.1.14+1.18.2.jar
- RSInfinityBooster-1.18.2-2.1+20.jar
- rubidium-0.5.4.jar
- rubidium-extra-0.4.16+mc1.18.2-build.57.jar
- rubidium_extras-1.18.2_v1.3.2.jar
- Satako-5.0.7-1.18.2.jar
- scannable-1.18.2-forge-1.7.6+135af8a.jar
- secretrooms-1.18.2-1.1.5.jar
- simpleplanes-1.18.2-5.2.1.jar
- SimpleStorageNetwork-1.18.2-1.6.2.jar
- simplylight-1.18.2-1.4.5-build.43.jar
- StorageDrawers-1.18.2-10.2.1.jar
- supermartijn642configlib-1.1.6-forge-mc1.18.jar
- supermartijn642corelib-1.1.1-forge-mc1.18.jar
- tcdcommons-2.1+1.18.2.jar
- tesseract-1.0.28-forge-mc1.18.jar
- TextruesRubidiumOptions-1.0.4-mc1.18.2.jar
- theoneprobe-1.18-5.1.2.jar
- thermal_expansion-1.18.2-9.1.0.18.jar
- thermal_foundation-1.18.2-9.1.0.34.jar
- thermal_innovation-1.18.2-9.1.0.15.jar
- titanium-1.18.2-3.5.8-40.jar
- trajans-tanks-forge-1.18-2.21.jar
- trajanscore1.18.jar
- trashcans-1.0.16-forge-mc1.18.jar
- universalgrid-1.18.2-1.0321.jar
- valkyrienskies-118-2.1.0-beta9.jar
- vc-1.0.1+e01d52e7d8.jar
- voicechat-forge-1.18.2-2.3.27.jar
- [1.18.2] SecurityCraft v1.9.5.jar

**Comment by rugter100** [comment]
I have a similar issue. For me it throws that error only when the ships are moving and it fills up my memory relatively fast and it does not seem to clean up either since it uses more memory than is allocated to the container

**Comment by Rubydesic** [comment]
There are too many mods to tell what is causing this issue and also you have no provided a log.

**Comment by Thexiaoyuqaq** [comment]
> 有太多的模组无法判断导致此问题的原因，而且您也没有提供日志。
Because he only returned this log, and I only installed this mod, the problem still occurs. Furthermore, it is accompanied by the ship being unable to move

**Comment by Thexiaoyuqaq** [comment]
> 有太多的模组无法判断导致此问题的原因，而且您也没有提供日志。
Because he only returned this log, and I only installed this mod, the problem still occurs. Furthermore, it is accompanied by the ship being unable to move
