### ISSUE TITLE
Ship stuck

### ISSUE THREAD

**Issue by spion2008l** [ValkyrienSkies/Valkyrien-Skies-2#403]
The ship is stuck in the air, it cannot move at all, even when breaking the helm.

**Comment by SrRapero720** [comment]
PRESS C

**Comment by spion2008l** [comment]
I tried that

**Comment by SrRapero720** [comment]
Open Helm and press align

**Comment by Rubydesic** [comment]
To help you with your issue I need some more information - please go to your .minecraft/logs folder and upload the "latest.log" and "debug.log" file.
