### ISSUE TITLE
Create moving contraptions don't render on Fabric

### ISSUE THREAD

**Issue by redtardis12** [ValkyrienSkies/Valkyrien-Skies-2#407]
Any kind of moving or rotating create mechanisms become invisible when assembled or placed after. This issue exists only on **Fabric** version 1.18.2. **Forge** versions still renderer things. I understand that it is a known issue. I just noticed that it wasn't mentioned here, maybe it will be a warning for someone else.

**Comment by Rubydesic** [comment]
This will be fixed when clockwork is released
