### ISSUE TITLE
Invisible ship when assembled

### ISSUE THREAD

**Issue by S4CRAL** [ValkyrienSkies/Valkyrien-Skies-2#412]
when i assemble a ship all the blocks disappear
![Minecraft_ 1 18 2 06_02_2023 16_19_17](https://user-images.githubusercontent.com/108689652/217010913-620d5063-eca0-496c-afe3-dbc9a3ee706d.png)

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative

**Comment by S4CRAL** [comment]
> 

Oh thank tou very much it works now
