### ISSUE TITLE
Setting Spawn Point At Bed In Ship And Dying Respawns Near World Border

### ISSUE THREAD

**Issue by Hubcat123** [ValkyrienSkies/Valkyrien-Skies-2#414]
When sleeping on a bed on a ship and then dying, I respawn really far out, where the actual ship structures seem to be stored near the world border. This happens with ships created with the ship wand or with Eureka.

Other Mods:
Create
Eureka
WTHIT
JEI
Pam's Harvestcraft 2 - Food Core

**Comment by TechTastic** [comment]
Update VS2 and Eureka to latest

**Comment by Hubcat123** [comment]
> Update VS2 and Eureka to latest

Ah, that worked, thank you! I thought I was up to date for some reason but I guess not
