### ISSUE TITLE
Server stuck in startup when trying to load Valkyrien

### ISSUE THREAD

**Issue by TheRealGriind** [ValkyrienSkies/Valkyrien-Skies-2#423]
Hi, I've got a server which gets stuck in the startup procedure every time it starts to load the world, and the only message that comes in the console once it's stuck is `[Physics thread/WARN] [org.valkyrienskies.core.impl.pipelines.VSGamePipelineStage/]: Too many physics frames in the physics frame queue. Is the game stage broken?` and it keeps spamming that. I've tried multiple different versions of the mod (and it's dependencies) but nothing seems to be working.

Issue: Server gets stuck at startup with one repeating message. (``)

Log: https://pastebin.com/bbJVAqP4

Installed Mods: 
- | AppleSkin                          | https://www.curseforge.com/minecraft/mc-mods/appleskin
- | Architectury API                   | https://www.curseforge.com/minecraft/mc-mods/architectury-api
- | Better Compatibility Checker       | https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker
- | Biomes O' Plenty                   | https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
- | Builder's Delight                  | https://www.curseforge.com/minecraft/mc-mods/builders-delight-forge
- | CC: Tweaked                        | https://www.curseforge.com/minecraft/mc-mods/cc-tweaked
- | CC:C Bridge                        | https://www.curseforge.com/minecraft/mc-mods/cccbridge
- | Chipped                            | https://curseforge.com/minecraft/mc-mods/chipped
- | Cloth Config API                   | https://www.curseforge.com/minecraft/mc-mods/configured
- | Configured                         | https://www.curseforge.com/minecraft/mc-mods/configured
- | ConnectedTexturesMod               | https://www.curseforge.com/minecraft/mc-mods/ctm
- | Controlling                        | https://www.curseforge.com/minecraft/mc-mods/controlling
- | Corpse                             | https://www.curseforge.com/minecraft/mc-mods/corpse
- | Create                             | https://www.curseforge.com/minecraft/mc-mods/create
- | Create Crafts & Additions          | https://www.curseforge.com/minecraft/mc-mods/createaddition
- | Create Plus                        | https://www.curseforge.com/minecraft/mc-mods/create-plus
- | FerriteCore                        | https://curseforge.com/minecraft/mc-mods/ferritecore
- | Flywheel                           | https://www.curseforge.com/minecraft/mc-mods/flywheel
- | FTB Chunks                         | https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge
- | FTB Library                        | https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge
- | FTB Ranks                          | https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge
- | FTB Teams                          | https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge
- | Journey Map                        | https://www.curseforge.com/minecraft/mc-mods/journeymap
- | Journey Map Integration            | https://www.curseforge.com/minecraft/mc-mods/journeymap-integration
- | Just Enough Items (JEI)            | https://www.curseforge.com/minecraft/mc-mods/journeymap-integration
- | Just Enough Resources (JER)        | https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
- | Macaw's Doors                      | https://www.curseforge.com/minecraft/mc-mods/macaws-doors
- | Macaw's Fences and Walls           | https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls
- | Macaw's Trapdoors                  | https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors
- | Macaw's Windows                    | https://www.curseforge.com/minecraft/mc-mods/macaws-windows
- | Mantle                             | https://www.curseforge.com/minecraft/mc-mods/mantle
- | MrCrayfish's Furniture Mod         | https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
- | Pam's Harvestcraft 2 Core          | https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core
- | Pam's Harvestcraft 2 Crops         | https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops
- | Pam's Harvestcraft 2 Food Extended | https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended
- | Pam's Harvestcraft 2 Trees         | https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees
- | Re-chiseled                        | https://curseforge.com/minecraft/mc-mods/rechiseled
- | Right Click, Get Crops             | https://www.curseforge.com/minecraft/mc-mods/right-click-get-crops
- | Shoppy                             | https://www.curseforge.com/minecraft/mc-mods/shoppy
- | Sophisticated Backpacks            | https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
- | Sophisticated Core                 | https://www.curseforge.com/minecraft/mc-mods/sophisticated-core
- | Storage Drawers                    | https://www.curseforge.com/minecraft/mc-mods/storage-drawers
- | SuperMartijn642's Config Lib       | https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib
- | SuperMartijn642's Core Lib         | https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
- | TerraBlender                       | https://www.curseforge.com/minecraft/mc-mods/terrablender
- | Tinker's Construct                 | https://www.curseforge.com/minecraft/mc-mods/tinkers-construct
- + Valkyrien Skies (Version **118-2.1.0-beta 10** mc 1.18.2), Eureka! Airships! (Version **1.1.0-beta.8** mc 1.18.2) & Kotlin (Version **3.10.0** for mc 1.18.2)

Minecraft version: MAGMA v1.18.2-4c85e283 | Forge - 40.2.1.

**Comment by ajh123** [comment]
Have you tried the mod without using a Magma server (just a normal forge one). Many mods don’t work probably when using Magma (they have to change a lot in order to make sure plugins will work with mods)

**Comment by Rubydesic** [comment]
VS2 generally doesn't support forge/bukkit hybrid servers, but some users have had success with [Arclight](https://github.com/IzzelAliz/Arclight)

**Comment by TheRealGriind** [comment]
Alright, thanks, I'll try that out! I originally did send this as an issue on Magma's issue report site, but they were very adamant on it just being a warning, not something that made the server not work. Hence why I tried my luck here.

**Comment by Kubson519** [comment]
i had the same issue with my forge server but it turned on after a few minutes
