### ISSUE TITLE
Tinker construct smeltery controller shows fuel is not found in ships

### ISSUE THREAD

**Issue by Ch1216** [ValkyrienSkies/Valkyrien-Skies-2#427]
![yeah](https://user-images.githubusercontent.com/68875386/221008879-dd1b7c19-8586-4c42-afde-687093bdc4e0.png)|

Tinker construct smeltery controller shows fuel is not found in ships but the smeltery still works as intended, it still smelts items and entitys, although the entity smelting range seems off

**Comment by walksanatora** [comment]
note: this used to work

**Comment by christianfirecup** [comment]
this is a visual glitch

**Comment by Ch1216** [comment]
works now for some reason, somehow
