### ISSUE TITLE
Valkryien Skies crashes, Critical Injection Failure

### ISSUE THREAD

**Issue by Zigmoid2** [ValkyrienSkies/Valkyrien-Skies-2#428]
Not sure what happened;

[Crash log +15kb](https://hastebin.com/share/oposovimoy.ruby)

**Comment by Zigmoid2** [comment]
Updated it..

**Comment by Rubydesic** [comment]
I can't tell which of your mods is causing the incompatibility, please make a new issue if you identify which specific one is causing the problem
