### ISSUE TITLE
Couldn't exactly reopen the issue, and I don't think this is visible otherwise, so opening a new issue.

### ISSUE THREAD

**Issue by LordDarthDan** [ValkyrienSkies/Valkyrien-Skies-2#433]
Okay, getting back to you with this: the performance has indeed improved, but only marginally; the postTick() method still takes up over 10% of tick time.
On a world generated by the same seed:
![image](https://user-images.githubusercontent.com/49121253/224853858-245a03d9-a1ed-4fd9-9cb8-a56d76e35b10.png)
(before)
![image](https://user-images.githubusercontent.com/49121253/224853892-00495f5b-ac9f-4171-bc5e-5724c448f24f.png)
(after)

_Originally posted by @LordDarthDan in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/431#issuecomment-1467114044_

**Comment by ewoudje** [comment]
Huh wierd i thought the OP of the issue would be able to open it, well i opened it up since its more clear if we continue in the same issue, thus closing this in favor of #431 .
