### ISSUE TITLE
rash

### ISSUE THREAD

**Issue by akon1248** [ValkyrienSkies/Valkyrien-Skies-2#434]

**Comment by klebin-bit** [comment]
Vs2 is sick?!??!?!!?

**Comment by walksanatora** [comment]
> says that vs2 crashes
> *does not provide logs/mod list*
> Leaves
https://www.youtube.com/watch?v=vAvcxeXtBz0

**Comment by akon1248** [comment]
Oops, it seems I accidentally opened this issue while searching issues.
