### ISSUE TITLE
Massive lag spikes after teleporting

### ISSUE THREAD

**Issue by emanuele246gi** [ValkyrienSkies/Valkyrien-Skies-2#437]
After consulting the debug.log right in the moment it started to lag, I saw the mod's name, it happened when I teleported back in my home village; I also don't have any ship assembled so I don't understand why this happens.

P.s.: to easily find the moment it was lagging scroll down to:
[24Mar2023 22:43:14.788] [Server thread/WARN] [org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage/]: Too many game frames in the game frame queue. Is the physics stage broken?

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11066765/debug.log)

**Comment by SrRapero720** [comment]
I have the same issue

**Comment by SaxDev** [comment]
I'd suggest you see https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/473 it is linked to this issue

**Comment by thetheaplant** [comment]
Closing in favor of #323
