### ISSUE TITLE
Extended Cogwheels - Fabric log - Incompatibility

### ISSUE THREAD

**Issue by TheRobberPanda** [ValkyrienSkies/Valkyrien-Skies-2#438]
As stated in the log, crash report wasn't generated.

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11071444/latest.log)

**Comment by Rubydesic** [comment]
Are you sure this is a problem with VS2? Can you see if this problem occurs without it?

**Comment by thetheaplant** [comment]
Unable to recreate.
