### ISSUE TITLE
Lectern link controller from Create not working using Tournament

### ISSUE THREAD

**Issue by Taggart1993** [ValkyrienSkies/Valkyrien-Skies-2#442]
I did not set the link range to infinite based on my knowledge of the VS2 system. Since on a lectern controller the signal is coming from a block instead of the player, it should have the rest of the ship/plane within range, right? Unfortunately, it does not. Is there a way to fix this now without setting the link range to infinite?

**Comment by NullHarp** [comment]
only fix other then infinite range is to wait for clockwork to release

**Comment by Rubydesic** [comment]
this will be fixed when clockwork releases
