### ISSUE TITLE
Crash when running in freebsd environment.

### ISSUE THREAD

**Issue by WhiteNoise1010** [ValkyrienSkies/Valkyrien-Skies-2#445]
An error occurred while starting the server. Even if I delete everything including the world and settings folder, it is the same.

When running in the Windows environment on the same system, openjdk 17.0.3, 17.0.4, 17.0.5, and 17.0.6 all worked normally.
In the case of the freebsd environment, neither case was executed.

I thought that freebsd's openjdk might be broken, so when I removed the Valkyrien Skies mod and ran it, it worked normally.

It may be a problem with freebsd's openjdk, but the error log clearly says that Valkyrien Skies caused a crash, and it works normally when the mod is removed, so I wrote an issue.

Crash report attached.
[crash-2023-04-05_06.26.31-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11153491/crash-2023-04-05_06.26.31-server.txt)

**Comment by WhiteNoise1010** [comment]
I tracked down the crash report and found it to be an issue with the Valkyrien-Skies-Krunch-Physics-API .

It was confirmed that the problem was that the JNI library could not be imported in the freebsd environment.

Since freebsd and linux are almost similar and work without major problems, I modified the KrunchPhysicsAPISharedLibraryLoader.java file as follows.

`static public boolean isLinux = System.getProperty("os.name").contains("Linux");`

I modified the above code as below.

`public static boolean isLinux = System.getProperty("os.name").contains("Linux") || System.getProperty("os.name").contains("FreeBSD");`

After modifying the freebsd environment to be recognized as a Linux environment, the server started.

However, in this case, the ship did not move at all.

The cause seems to be that Valkyrien-Skies-Krunch-Physics-API fails to load the library in the freebsd environment.

**Comment by WhiteNoise1010** [comment]
hmm. Crashes over time. It seems that it needs to be modified so that it runs properly in the freebsd environment, rather than tricking it into a Linux environment.

Crash report attached.
[crash-2023-04-05_22.31.02-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11159591/crash-2023-04-05_22.31.02-server.txt)

**Comment by Rubydesic** [comment]
supporting freebsd is not currently an interest of ours. Sorry
