### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by KadenConnin** [ValkyrienSkies/Valkyrien-Skies-2#446]
I don't know if this is the right page that i should post this on, but i tried to install eureka and it crashes every time, I tried downgrading the version but it still crashes. i tried using the logs to see if the missing despendency for forge changes but it never did, is there a version that i just haven't found the download yet?
Forge version is 40.1.51 if that helps.
[2023-04-07-2.log.gz](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11182445/2023-04-07-2.log.gz)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. If you try with only VS/Eureka does the issue persist?

**Comment by KadenConnin** [comment]
Nope not caused by the other mods, log still says Missing mandatory dependencies: forge, forge, I know my forge version is 1.18.2 and I know I'm downloading for 1.18.2 so it can't be wrong forge version or wrong VS/Eureka

**Comment by Dempat1** [comment]
Sometimes, when you use no premium launchers, like "tlauncher" and similars, that have a forge version to "download", they actually download a lower version, so, you  tried to erase all of the forge in your directory, and download it again, but now from forge page? I remember a similar thing happened to me a few days ago, and that fixed

**Comment by Rubydesic** [comment]
cannot reproduce
