### ISSUE TITLE
TPS & FPS dramatically drops when using Valkyrien Skies 2

### ISSUE THREAD

**Issue by hathslippy** [ValkyrienSkies/Valkyrien-Skies-2#456]
Tested without & without VS2 on a Curseforge modpack - empty of mods except VS2 and got substantial drops in server TPS & client FPS even with no ships created or rendered. Same issue on packs with performance mods like Rubidium installed too - essentially precludes running this mod on any decent sized server.

Issue seems related to https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/431 & https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/440

**Comment by Rubydesic** [comment]
Cannot reproduce
