### ISSUE TITLE
My ship is invisible

### ISSUE THREAD

**Issue by Kylehegamer** [ValkyrienSkies/Valkyrien-Skies-2#458]
when i assemble a ship it simply just turn invisible

**Comment by http-80** [comment]
do you have optifine? optifine causes this problem for me.

**Comment by Kylehegamer** [comment]
no i dont , this usually happens when i add more mods

**Comment by Rubydesic** [comment]
I can't tell which of your mods is causing the incompatibility, please make a new issue if you identify which specific one is causing the problem
