### ISSUE TITLE
Command arguments do not have a translation

### ISSUE THREAD

**Issue by Ch1216** [ValkyrienSkies/Valkyrien-Skies-2#465]
argument.ship.no_found (do "/tp @v" when no ship exist)

argument.ship.multiple_found (do "/tp @v" when multiple ships exist)

**Comment by StewStrong** [comment]
Fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/5747aa2ad0ba190c003afa51e37d3831765efc58
