### ISSUE TITLE
VS2 causes massive drops in FPS & TPS on serverTick

### ISSUE THREAD

**Issue by hathslippy** [ValkyrienSkies/Valkyrien-Skies-2#473]
Testing modpack with mostly performance mods installed. Ran spark profiler with VS2 & eureka on / off and got substantially TPS/MSPT & FPS drops with VS2 & Eureka on (MSPT 95 percentile goes from 21.7 to 75.2) - see spark profiler links below.

VS2 On:- https://spark.lucko.me/koFuchigAR
VS2 Off:- https://spark.lucko.me/WTXfXOapKY

Issue seems to be tick.Server>handler$blj001$postTickGame>VSPhysicsPipelineStage.pushGameFrame>Thread.sleep which was also commented on in [issue #449](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/449). I assume that this means that the server is constantly running with [gameFramesQueue >= 100](https://github.com/ValkyrienSkies/vs-core/blob/main/impl/src/main/kotlin/org/valkyrienskies/core/impl/pipelines/VSPhysicsPipelineStage.kt#L114) which is accompanied by hundreds of "Too many game frames in the game frame queue. Is the physics stage broken?" server thread errors in the console while the game is running.

Modlist here:- [Modlist.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11408606/Modlist.zip)

**Comment by StewStrong** [comment]
This occurs when the physics is running very slow or has crashed entirely. We have a fix for this planned but it wont be ready for at least another month or so.

**Comment by rhinotastic** [comment]
Is there any work arounds we can do in the meantime?

**Comment by SaxDev** [comment]
Im having the same exact issue, commenting to bring it up again, is there a fix for this?

**Comment by NovelPhacelia** [comment]
There's been many updates since then, is this still a issue?

**Comment by ThatOneKitsune** [comment]
> This occurs when the physics is running very slow or has crashed entirely. We have a fix for this planned but it wont be ready for at least another month or so.

running a server on 1.19.2 with this exact issue that keeps causing the server to run 30-60 tick behind. is it still being addressed or not? i love having this mod in because it's nice to make our own ships, and i'm hoping that there will be an update to fix this soon.

**Comment by Sunconure11** [comment]
I’m still running into this. @StewStrong

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13799536/latest.log)
Here's my latest log, just in case.

**Comment by Sunconure11** [comment]
@ThatOneKitsune Can you replicate this still? I want you to post a log. I am having this issue in environments with many mods, but with just VK + some addons, no issues.

**Comment by boniblade** [comment]
Still happening in 1.20.1, what's going on over there?

**Comment by StonedGoat** [comment]
> This occurs when the physics is running very slow or has crashed entirely. We have a fix for this planned but it wont be ready for at least another month or so.

it's been over a YEAR, whats going on??????

**Comment by thetheaplant** [comment]
Closing in favor of #323
