### ISSUE TITLE
Optimise Hashset

### ISSUE THREAD

**Issue by coco875** [ValkyrienSkies/Valkyrien-Skies-2#474]
Try to find a way to better use Hashset to reduce memory and CPU
Here a exemple:
https://spark.lucko.me/7FShGimrLf
![image](https://user-images.githubusercontent.com/59367621/236573516-e4f83f34-51aa-41cd-bc9d-db25529d6b71.png)
is nearly 17% here and I think we can optise it

and it's here you define it
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/c3076eba2428b4bef3a4732aea55051d928f41ae/common/src/main/java/org/valkyrienskies/mod/mixin/server/world/MixinServerLevel.java#L117

**Comment by StewStrong** [comment]
We need a more efficient way to gets loaded/unloaded last tick. Then we can remove the hashset copy.

**Comment by StewStrong** [comment]
I have removed the HashSet copy in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/2c04a9a70d852ad8e69bb1d550143227f0061071 which should fix this performance problem
