### ISSUE TITLE
Crash /tp @v[limit=1] @s

### ISSUE THREAD

**Issue by cj05** [ValkyrienSkies/Valkyrien-Skies-2#476]
Modpack: newest cogfight modpack, with updated vs and cw and cbc
World seemed to crash out, but not the client, no debug log was generated
Crashes when using /tp @v[limit=1] @s to teleport a plane to me

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11419177/latest.log)

**Comment by cj05** [comment]
removing replaymod helps

**Comment by StewStrong** [comment]
I think I fixed it in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/5c9e3bf764a6a9be1f2c1c7c0da3188c06f1a785, can you test this build once github actions is done compiling?

**Comment by cj05** [comment]
Works now
should i close the issue now
