### ISSUE TITLE
Redstone Resistor signal doesn't update

### ISSUE THREAD

**Issue by Jarkyc** [ValkyrienSkies/Valkyrien-Skies-2#478]
When using a redstone link between a redstone resistor, the resistor won't update its analog input signal unless you bring the signal down to 0, and then set it to the designated power level. Once it is set, you cannot change it to anything unless you set it to 0 again. Shown in this video https://youtu.be/hm7QLlwwW1c

**Comment by thetheaplant** [comment]
Unable to recreate, and non Vs2 issue.
