### ISSUE TITLE
Breaks right click handling of Thermal series mods

### ISSUE THREAD

**Issue by REDxEYE** [ValkyrienSkies/Valkyrien-Skies-2#479]
Bug with thermal series and valkyrien skies 2 mod on MC 1.18.2 + forge 40.2.0
When valkyrien skies 2 is installed, player is unable to use servos(right click with servo in hand)  on fluid pipes.

Expected:
* Player should be able to use servo on fluid pipe(fluidduct)

Steps to reproduce:
* Place `Aqueous Accumulator`
* Place `fluidduct` next to `Aqueous Accumulator`
* Use `Attachment: Servo` in fluidduct part connected to `Aqueous Accumulator`

mod versions: 
* valkyrien skies 2 2.11.0-beta.11
* kotlinforforge 3.12.0-all
* cofh-core 9.2.1
* thermal_dynamics 9.2.1b
* thermal_expansion 9.2.0.20
* thermal_foundation 9.2.0.46
* thermal_series 9.2.0.46 
* thermal_integration 9.2.0.16
* thermal_locomotion 9.2.0.13
* thermal_cultivation 9.2.0.16

**Comment by StewStrong** [comment]
I might've fixed this when I fixed ender storage compatibility. Can you test this again with `v2.1.0-beta.12`? Its on curseforge.

**Comment by REDxEYE** [comment]
Verified fixed.

**Comment by arensagun2** [comment]
This issue also happens in MC 1.20.1 + 47.2.30

Steps to reproduce:
- Place down a Redstone Furnace on a physics/ship object
- Right Click Redstone Furnace

Mod Versions:
valkyrienskies-120-2.3.0-beta.5
kotlinforforge-4.10.0
thermal_expansion-1.20.1-11.0.0.27
thermal_foundation-1.20.1-11.0.2.64
