### ISSUE TITLE
Crash when first player joins on a custom multiplayer server

### ISSUE THREAD

**Issue by gglobensky** [ValkyrienSkies/Valkyrien-Skies-2#483]
The title says it all.

Information:
Forge 40.2.0
Java 17
Minecraft 1.18.2
Valkyrien Skies: valkyrienskies-118-2.1.0-beta.12

Crashlog:
https://pastebin.com/GsdWcG25

Latest.log
https://www.file.io/6Yi0/download/PrmOzZdQtx5n

**Comment by Rubydesic** [comment]
incompatible with mods that add other dimensions, duplicatae of multiple other issues, will be fixed at some point

**Comment by gglobensky** [comment]
AFAIK I don't have dimension mod. 
I would take a wild guess and say I have hourglass that changes the duration of the day, it may cause the same problems.

Thanks
