### ISSUE TITLE
[1.18.2] Mixin apply failed with vault hunters

### ISSUE THREAD

**Issue by Altrath** [ValkyrienSkies/Valkyrien-Skies-2#484]
[crash.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11559117/crash.txt)

Running a modified Vault Hunters modpack on 1.18.2 forge 40.2.1
Further inspection showed that its incompatible with the vault core mod (the_vault-1.18.2-3.8.0.2176.jar) game launches with all the mods minus the vault

**Comment by Rubydesic** [comment]
dupe of #450
