### ISSUE TITLE
Sodium crashes at startup with fairly huge modpack

### ISSUE THREAD

**Issue by gittibene** [ValkyrienSkies/Valkyrien-Skies-2#488]
### Mod Name

Sodium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

Game crashes at startup with failed injection error. Mods installed:
12/02/2023  12:30           324.153 Ad-Astra-Giselle-Addon-fabric-1.19.2-1.12.jar
31/05/2023  00:47            66.310 AdaptiveTooltips-1.0.1-fabric-1.19.2.jar
24/03/2023  21:39           643.442 AdditionalEnchantedMiner-1.19-fabric-19.1.753.jar
29/11/2022  23:38         3.935.476 Adorn-3.7.0+1.19.2-fabric.jar
04/12/2022  19:13           192.525 AdvancementPlaques-1.19.2-fabric-1.4.6.jar
29/11/2022  23:39            11.117 advdebug-2.3.0.jar
11/05/2023  16:48        10.198.308 ad_astra-fabric-1.19.2-1.12.6.jar
04/05/2023  02:13           177.970 almostunified-fabric-1.19.2-0.4.3.jar
23/04/2023  16:37            38.323 alternate-current-mc1.19-1.5.0.jar
14/05/2023  06:52            22.823 Angel-Ring-Fabric-1.19-1.0.2.jar
24/05/2023  05:26        10.143.754 appliedenergistics2-fabric-12.9.5.jar
15/04/2023  02:16           563.594 architectury-6.5.77-fabric.jar
30/11/2022  14:42           599.880 artifacts-7.1.1+fabric.jar
11/01/2023  21:00            18.895 AttributeFix-Fabric-1.19.2-17.1.3.jar
18/05/2023  15:31           572.177 autohud-3.2.1+1.19.1.jar
29/11/2022  23:44         1.268.682 automobility-0.4.1+1.19.2-fabric.jar
29/11/2022  23:44           414.751 awesomedungeon-fabric-1.19.2-3.0.0.jar
29/11/2022  23:45           205.942 awesomedungeonend-fabric-1.19.2-3.0.0.jar
29/11/2022  23:45           242.831 awesomedungeonnether-fabric-1.19.2-3.0.0.jar
29/11/2022  23:44           215.990 awesomedungeonocean-fabric-1.19.2-3.0.1.jar
29/11/2022  23:46           640.522 balm-fabric-4.5.2+0.jar
22/12/2022  04:23         1.892.104 bclib-2.1.5.jar
09/03/2023  17:31           100.427 better-mcdonalds-mod-fabric-1.19.2-2.0.0.jar
29/11/2022  23:48        21.951.916 better-nether-7.1.2.jar
21/01/2023  16:07         2.453.915 betteranimalsplus-1.19.2-11.0.10-fabric.jar
29/11/2022  23:49            45.804 BetterThirdPerson-Fabric-1.19-1.8.1.jar
08/05/2023  19:48           887.437 biometech-0.1.3+1.19.2.jar
02/01/2023  17:04         2.709.532 BOMD-1.4.6-1.19.2.jar
20/05/2023  11:58           294.279 Bookshelf-Fabric-1.19.2-16.2.18.jar
12/01/2023  19:01           136.409 botarium-fabric-1.19.2-1.8.2.jar
17/04/2023  15:40         1.601.059 BuildGuide-1.19.2-0.3.3.jar
23/04/2023  02:16            78.360 carpeted-1.19.2-1.4-fabric.jar
26/03/2023  13:18         2.978.418 cc-restitched-1.101.2.jar
24/04/2023  15:10           182.452 cccbridge-1.4.1-fabric.jar
29/11/2022  23:50         3.968.760 charm-fabric-1.19.2-4.4.4.jar
28/05/2023  18:46           102.529 chefs-delight-1.0.3-fabric-1.19.2.jar
22/01/2023  16:41         5.301.179 chisel-1.4.7+1.19.2.jar
04/06/2023  17:04         1.141.796 cloth-config-8.2.88-fabric.jar
23/04/2023  03:17           578.981 collective-1.19.2-6.53.jar
05/03/2023  18:52         1.277.398 companion-bats-fabric-1.19.3.jar
18/05/2023  09:17           209.162 connectiblechains-2.1.4+1.19.2.jar
03/05/2023  02:33           142.097 connectivity-fabric-1.19.2-4.1.jar
23/04/2023  16:55           246.552 construction+deco+1.19.jar
17/03/2023  10:19           973.386 Continents_1.19_v1.1.1.jar
22/01/2023  15:46         1.128.730 continuity-2.0.1+1.19.jar
19/04/2023  12:36           513.091 CorgiLib-fabric-1.19.2-1.0.0.32.jar
04/05/2023  16:30            21.482 CosmeticArmor-1.19-1.4.2.jar
20/05/2023  09:35           356.678 Couplings-1.9.1+1.19.jar
14/05/2023  23:12        18.066.675 create-fabric-0.5.0.i-1017+1.19.2.jar
08/05/2023  22:47           932.706 createaddition-fabric+1.19.2-20230308b.jar
05/01/2023  01:11            21.217 createchunkloading-1.3.0-fabric.jar
15/04/2023  01:48         3.227.224 createdeco-1.3.0-1.19.2.jar
30/11/2022  00:00           653.406 creeperoverhaul-2.0.5-fabric.jar
22/12/2022  05:37         1.040.804 crittersandcompanions-fabric-1.19.2-1.0.2.jar
19/04/2023  12:37         2.904.375 Croptopia-1.19.2-FABRIC-2.2.2.jar
01/06/2023  00:48            36.729 cryingghasts-1.19.2-3.1.jar
23/04/2023  14:36            81.692 cullleaves-fabric-3.0.1.jar
15/01/2023  16:14           289.003 cultural-delights-fabric-0.14.9+1.19.2.jar
20/05/2023  09:33           177.736 DarkUtilities-Fabric-1.19.2-13.1.7.jar
30/11/2022  21:42        18.295.501 deeperdarker-fabric-1.1.4.jar
14/05/2023  06:46            89.858 DiagonalFences-v4.2.4-1.19.2-Fabric.jar
22/12/2022  04:28         4.566.838 DramaticDoors-Fabric-1.19.2-1.3.5.jar
23/04/2023  02:08         1.223.262 drinkbeer-3.2.2-1.19.2.jar
18/05/2023  15:31           406.213 dynamiccrosshair-5.6.1+1.19.2-fabric.jar
04/12/2022  18:54         2.785.802 ecologics-fabric-1.19.2-2.1.10.jar
19/04/2023  12:33            16.059 EnderDragonEggRespawn-1.0.0_1.19.2-Fabric.jar
30/11/2022  00:12            10.797 Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
02/06/2023  03:35           442.996 entity_texture_features_fabric_1.19.2-4.4.4(1).jar
28/05/2023  09:43           133.300 exordium-fabric-1.0.1-mc1.19.2.jar
26/03/2023  14:00         1.882.121 fabric-api-0.76.0+1.19.2.jar
11/05/2023  15:59         6.578.017 fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
02/06/2023  16:58           426.451 fabric-seasons-2.2.1+1.19.jar
02/06/2023  16:59            50.831 fabric-seasons-croptopia-2.2.2-compat-1.0.jar
02/06/2023  16:59            39.100 fabric-seasons-delight-1.3.9-compat-1.0.jar
02/06/2023  16:59           339.976 fabric-seasons-extras-1.2-BETA+1.19.jar
02/06/2023  17:00            49.473 fabric-seasons-terralith-2.3.7-compat-1.0.jar
22/01/2023  16:41           611.657 factory-blocks-mod-1.0.1+1.19.jar
30/11/2022  00:15           407.197 FallingTree-1.19.2-3.10.0.jar
02/01/2023  17:32         2.705.516 farmers-delight-fabric-1.19.X-1.3.9.jar
18/05/2023  08:32            24.046 farsighted-mobs-fabric-1.1-1.18-1.19.jar
22/01/2023  17:52           119.275 ferritecore-5.0.3-fabric.jar
22/05/2023  14:07           439.991 ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric(1).jar
22/01/2023  06:38         1.089.467 fpsdisplay-1.5.0+1.19.jar
20/05/2023  10:40           110.689 FpsReducer2-fabric-1.19.2-2.1.jar
30/04/2023  17:08           373.520 full-slabs-3.3.6.jar
30/11/2022  00:18         3.618.819 geckolib-fabric-1.19-3.1.37.jar
15/04/2023  01:52           500.932 HopoBetterUnderwaterRuins-1.19-1.1.jar
04/12/2022  19:13            79.522 Iceberg-1.19.1-fabric-1.0.46.jar
28/05/2023  09:44           180.269 ImmediatelyFast-1.1.12+1.19.jar
17/03/2023  10:43         4.818.740 immersive_paintings-0.5.1+1.19.2-fabric.jar
23/04/2023  01:54         2.673.023 immersive_weathering-1.19.2-1.2.9-fabric.jar
30/11/2022  00:21           118.642 indium-1.0.9+mc1.19.2.jar
30/11/2022  00:22           166.710 indypets-1.1.0-1.19.2.jar
04/05/2023  02:59         1.120.618 infinitybuttons-3.1.0-mc1.19.2.jar
02/01/2023  17:15           133.595 inventoryessentials-fabric-1.19-5.0.0.jar
04/06/2023  19:29            51.961 iris-flywheel-compat-1.19.2-0.1.9-BETA.jar
19/04/2023  17:22         2.799.149 iris-mc1.19.2-1.6.1.jar
27/04/2023  16:04         7.388.420 journeymap-1.19.2-5.9.5-fabric(1).jar
02/06/2023  17:34           105.432 labels-1.19.2-1.9-fabric.jar
04/01/2023  12:19           134.262 laserbridges-1.19.2-0.jar
02/01/2023  15:50            14.531 lazydfu-0.1.3.jar
04/05/2023  03:00           372.060 led-1.3.0.jar
30/11/2022  00:23           155.643 libraryferret-fabric-1.19.2-3.0.0.jar
23/04/2023  02:22           501.222 lightest-lamps-fabric-3.0.0f.jar
05/06/2023  03:08                 0 list.txt
22/01/2023  17:51           555.137 lithium-fabric-mc1.19.2-0.10.4.jar
30/11/2022  00:24           120.017 logical_zoom-0.0.17.jar
14/05/2023  06:44            83.610 MagnumTorch-v4.2.2-1.19.2-Fabric.jar
04/06/2023  13:13           516.948 malilib-fabric-1.19.2-0.13.0.jar
08/05/2023  03:18           406.204 MapFrontiers-1.19.2-2.5.0-beta3-fabric.jar
23/04/2023  02:19           589.543 marketcrates-fabric-1.5.jar
30/11/2022  00:24           594.351 mcw-bridges-2.0.5-mc1.19.2fabric.jar
30/11/2022  00:26         1.000.349 mcw-doors-1.0.7fabric-mc1.19.2.jar
30/11/2022  00:31           331.665 mcw-fences-1.0.6fabric-mc1.19.2.jar
04/12/2022  18:53           274.166 mcw-lights-1.0.4fabric-mc1.19.2.jar
30/11/2022  00:32            49.460 mcw-paintings-1.0.4fabric-mc1.19.jar
15/01/2023  15:17           258.105 mcw-paths-1.0.2fabric-mc1.19.2.jar
30/11/2022  00:32         1.850.649 mcw-roofs-2.2.1-mc1.19.2-fabric.jar
30/11/2022  00:32           515.744 mcw-trapdoors-1.0.7fabric-mc1.19.2.jar
30/11/2022  00:33           945.768 mcw-windows-2.1.0fabric-1.19.2.jar
24/05/2023  15:30           146.933 memoryleakfix-fabric-1.17+-1.0.0.jar
24/05/2023  15:31           216.275 merequester-1.19.2-1.1.2.jar
04/06/2023  16:24            66.328 midnightlib-fabric-1.0.0.jar
27/05/2023  14:00        11.938.172 minecraft-comes-alive-7.5.0+1.19.2-universal.jar
16/03/2023  06:39            88.496 moderate-loading-screen-1.1.3+1.19.jar
04/06/2023  11:00           518.586 modernfix-mc1.19.2-fabric-3.7.1.jar
12/05/2023  05:45           692.192 modmenu-4.2.0-beta.2.jar
16/03/2023  06:26           644.312 MoEnchantments-2.2.9+1.19.2.jar
28/05/2023  10:11           836.268 moonlight-1.19.2-2.2.34-fabric.jar
30/11/2022  00:36           114.787 MoreLeads-fabric-1.19.2-1.0.0.jar
23/04/2023  02:32           692.187 mostructures-1.4.3+1.19.2.jar
17/03/2023  10:45           229.915 mysticaloaktree-1.19.2-1.8-fabric.jar
04/01/2023  02:37           791.355 NethersDelight-1.0.0+1.19.2.jar
05/06/2023  03:08                14 New Text Document.bat
03/06/2023  05:04           475.653 no-more-purple-1.0.1+1.19.jar
30/11/2022  00:38            39.831 NotEnoughBreeding-1.19.2-1.0.0-fabric.jar
30/05/2023  13:54           364.396 Nullscape_1.19.3_v1.2.1.jar
19/04/2023  12:37        37.915.825 Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.1.jar
04/05/2023  02:59           163.625 online_detector-1.19-3.1.2.jar
18/01/2023  19:21            79.602 OverpoweredMending-1.19.2-2.8.2.jar
22/01/2023  05:56           649.188 owo-lib-0.8.2+1.19.jar
04/06/2023  15:54           851.784 Patchouli-1.19.2-77-FABRIC.jar
05/05/2023  19:20        60.646.098 physics-mod-pro-v143b-fabric-1.19.2.jar
24/05/2023  15:11            91.402 PickUpNotifier-v4.2.4-1.19.2-Fabric.jar
09/03/2023  17:37           180.871 player-animation-lib-fabric-1.0.2.jar
30/11/2022  00:40         7.221.397 PresenceFootsteps-1.6.3.jar
04/05/2023  16:24           525.817 PuzzlesLib-v4.4.0-1.19.2-Fabric.jar
14/05/2023  09:55           251.816 quickshulker-1.3.9-1.19.jar
02/06/2023  12:09            27.519 rainbowlamp-fabric-1.1-1.19.X.jar
18/05/2023  09:20            50.173 randombonemealflowers-1.19.2-4.1.jar
30/11/2022  00:41           581.185 RebornCore-5.4.0.jar
07/12/2022  11:11            64.260 resolution-control-plus-1.19.x-3.0.0.jar
11/05/2023  16:49           128.481 resourcefulconfig-fabric-1.19.2-1.0.20.jar
11/05/2023  16:50           229.931 resourcefullib-fabric-1.19.2-1.1.24.jar
30/11/2022  00:41           269.493 respawnablepets-1.19-2.jar
30/11/2022  00:43           184.633 rocks-1.6.1.jar
04/12/2022  19:06         1.386.673 rottencreatures-fabric-1.19.2-1.0.1.jar
29/05/2023  10:43         2.213.819 RoughlyEnoughItems-9.1.601.jar
24/05/2023  13:12         1.175.957 Rrls-1.5.0-fabric.jar
09/03/2023  09:37           256.085 runes-fabric-0.9.6+1.19.jar
20/05/2023  11:16            23.509 ShowMeWhatYouGot-1.19.2-1.0.3.jar
18/05/2023  08:41            53.472 silencemobs-1.19.2-3.0.jar
23/04/2023  02:14         1.221.170 simplehats-fabric-1.19.2-0.1.6.jar
11/05/2023  14:37           814.418 sliceanddice-fabric-2.1.2-fabric.jar
15/04/2023  02:18           322.170 SmartBrainLib-fabric-1.19.2-1.9.jar
31/05/2023  12:33            47.869 smarterfarmers-1.19.2-1.7.2-fabric.jar
28/05/2023  09:39            88.634 smoothboot-fabric-1.19-1.7.1.jar
15/05/2023  04:41         1.372.575 sodium-fabric-mc1.19.2-0.4.4+build.18.jar
10/05/2023  03:02         5.139.094 soulslike-weaponry-0.9.9.3.jar
22/12/2022  04:42           106.368 soundphysics-fabric-1.19.2-1.0.18.jar
21/01/2023  14:19         2.773.826 spark-1.9.45-fabric.jar
09/03/2023  17:34         1.016.489 spell_engine-fabric-0.9.15+1.19.jar
09/03/2023  17:38           159.221 spell_power-fabric-0.9.8+1.19.jar
12/05/2023  04:59           127.465 starlight-1.1.1+fabric.ae22326.jar
04/06/2023  13:14           174.055 Statement-4.2.5+1.14.4-1.19.3.jar
30/04/2023  00:06         2.797.531 Steam_Rails-1.2.6+fabric-mc1.19.2.jar
23/04/2023  01:58           477.865 Structory_Towers_1.19.3_v1.0.2.jar
30/11/2022  00:48           863.168 structure-tools-1.0.30.jar
27/05/2023  16:13        14.371.649 supplementaries-1.19.2-2.3.14-fabric.jar
21/05/2023  23:11         6.032.827 TechReborn-5.4.0.jar
30/11/2022  00:49           309.445 TerraBlender-fabric-1.19.2-2.0.1.130.jar
23/05/2023  23:17         3.050.183 Terralith_1.19.3_v2.3.8.jar
30/11/2022  00:52            67.999 time-and-wind-ct-1.4.3+1.19.2.jar
30/11/2022  00:53         2.822.845 Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
30/11/2022  00:56           235.740 trinkets-3.4.1.jar
25/05/2023  00:36           263.266 unloadedactivity-0.4.0-1.19.2.jar
12/05/2023  04:05           628.402 upgradedshulkers-1.1.3-1.19.jar
04/06/2023  15:56            35.648 VarietyAPI-1.0-release.jar
04/06/2023  15:53         1.949.401 Variety_Aquatic-1.0.4.4.jar
01/06/2023  08:47         3.073.855 vinery-fabric-1.2.11.jar
30/11/2022  00:56         1.223.275 windchimes-1.2.1.jar
03/06/2023  16:21           153.817 witchmobility-1.3.2-1.19.2.jar
15/04/2023  01:29         2.107.325 wizards-fabric-0.9.13+1.19.jar
30/11/2022  00:58           163.370 wolves-with-armor-1.8.0-1.19.jar
06/12/2022  18:57           671.152 wondrouswilds-1.19.2-1.1.5.jar
04/06/2023  13:21           401.031 wraith-waystones-3.0.7+mc1.19.2.jar
30/11/2022  01:00           808.171 wunderreich-3.0.18.jar
15/04/2023  01:47           166.402 xp_obelisk-0.4.9-r+1.19.2-Fabric.jar
15/04/2023  01:47           130.373 xp_obelisk_additions-0.1.9-r+1.19.2-Fabric.jar
01/06/2023  09:03           202.452 YetAnotherConfigLib-2.2.0-for-1.19.2.jar
30/11/2022  01:01           324.735 youre-in-grave-danger-1.4.6.jar
04/03/2023  19:01         1.211.292 YungsApi-1.19.2-Fabric-3.8.8.jar
04/03/2023  17:22         1.132.583 YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
30/11/2022  01:04         1.162.780 YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
30/11/2022  01:03           278.685 YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
28/02/2023  10:37           962.330 YungsBetterNetherFortresses-1.19.2-Fabric-1.0.4.jar
05/03/2023  05:57         1.414.502 YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
30/11/2022  01:04           426.331 YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
04/12/2022  19:11           248.312 YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
30/11/2022  01:04           386.484 YungsBridges-1.19.2-Fabric-3.1.0.jar
30/11/2022  01:04           428.068 YungsExtras-1.19.2-Fabric-3.1.0.jar

### Issue reproduction

Starting the game with sodium installed: crash, without sodium: runs

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11648561/latest.log)

**Comment by Rubydesic** [comment]
I can't tell which of your mods is causing the incompatibility, please make a new issue if you identify which specific one is causing the problem
