### ISSUE TITLE
Save and load vs_ship_data in every dimension

### ISSUE THREAD

**Issue by Ranpoes** [ValkyrienSkies/Valkyrien-Skies-2#489]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

The shipSavedData is currently stored exclusively in the data directory of the overworld, tightly coupled with the vsPipeline. Its challenges for server administrators who need to manage and backup ships across multiple worlds.

### Issue reproduction

``` 
// Load ship data from the world storage
final ShipSavedData shipSavedData = overworld().getDataStorage()
    .computeIfAbsent(ShipSavedData::load, ShipSavedData.Companion::createEmpty, ShipSavedData.SAVED_DATA_ID);

// If there was an error deserializing, re-throw it here so that the game actually crashes.
// We would prefer to crash the game here than allow the player keep playing with everything corrupted.
final Throwable ex = shipSavedData.getLoadingException();
if (ex != null) {
    System.err.println("VALKYRIEN SKIES ERROR WHILE LOADING SHIP DATA");
    ex.printStackTrace();
    throw new RuntimeException(ex);
}

// Create ship world and VS Pipeline
vsPipeline = shipSavedData.getPipeline();

KrunchSupport.INSTANCE.setKrunchSupported(!vsPipeline.isUsingDummyPhysics());

shipWorld = vsPipeline.getShipWorld();
```

**Comment by Rubydesic** [comment]
due to plans for implementing portals in the future, this will unfortunately be pretty difficult to implement compared to the amount of users it will benefit. Sorry.
