### ISSUE TITLE
Server crashing if a create contraption on a ship is actuated. (From Entity to Block)

### ISSUE THREAD

**Issue by piRsquaredH256** [ValkyrienSkies/Valkyrien-Skies-2#496]
### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Title.
Crash log provided.

### Issue reproduction

Have a ship and actuate a create contraption on it. 

### Logs

[crash-2023-06-14_05.28.06-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11741431/crash-2023-06-14_05.28.06-server.txt)

**Comment by piRsquaredH256** [comment]
I disabled server Watchdog. Server console now spams: 

[Server thread/WARN] [Cl.MixinAbstractContraptionEntity/]: Warning distance too high ignoring teleportTo request 
and
[Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8514295650000006E7, 68.87498681386415, 20433.943997502716] -> [20842.71195509087, 70.67498676618044, 1.2290059650000006E7] returning empty list! this might break things

and starts lagging really bad resulting in a timed out disconnect. 
Once reconnecting everything is fine.

**Comment by piRsquaredH256** [comment]
Okay after some testing, server still crashes. 
New server crash report is attached. 
[crash-2023-06-15_19.21.39-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11760858/crash-2023-06-15_19.21.39-server.txt)

**Comment by piRsquaredH256** [comment]
I just tested it with the latest package (valkyrienskies-118-forge-2.1.0-beta.13+3450e9e705). Server still crashing. 
Crash log attached.
[crash-2023-06-15_19.36.38-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11760982/crash-2023-06-15_19.36.38-server.txt)

**Comment by piRsquaredH256** [comment]
Removed Balm and IE same error still happens.

**Comment by piRsquaredH256** [comment]
Video of the crash happening:
https://m.youtube.com/watch?v=evlzLZ-OFK0&feature=youtu.be

**Comment by Rubydesic** [comment]
Thanks for the detailed report. This seems like it might be an issue with Clockwork. Does the issue persist if you remove Clockwork?

**Comment by Kielbashnikov** [comment]
Hello,
I've been having similar issue for a few days on my moded server. Whenever some craft made with VS with Eureka installed is moved server spams message "java.lang.Exception: Collision box is too big!" and enormous lags are created. This lag combined with new chunks rendering may even cause timed out server crash. Unfortunaty I have no idea what is it related to but I would love to have some way to prevent this type of lagging. Also i DO NOT have Clockwork installed and my MC verison is 1.19.2.

**Comment by toga-01** [comment]
adding on that I'm having the same issue on my 1.19.2 server. while sitting in a ship made with Eureka, the console is spammed with "[VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big!". The ship is constantly lagging every time this pops up in the console, and is only the ship. The rest of the server still runs fine, even all other server data gets sent to the client with no issue.
The ship lag when moving slowly in already rendered chunks is 1/4-1/2 a second. when loading in new chunks while using the ship, the lag can be anywhere from 1-5 seconds. if you fly for too long on the server (usually 30s for us) the server crashes. 

(also note this happens on a single player world, just less intense)

I love the mod, but until the lag is fixed, its not worth having on my server

**Comment by CSdiscoveries** [comment]
Hello, I am having the same issue. It's getting really bad.

**Comment by timmbobb** [comment]
> adding on that I'm having the same issue on my 1.19.2 server. while sitting in a ship made with Eureka, the console is spammed with "[VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big!". The ship is constantly lagging every time this pops up in the console, and is only the ship. The rest of the server still runs fine, even all other server data gets sent to the client with no issue. The ship lag when moving slowly in already rendered chunks is 1/4-1/2 a second. when loading in new chunks while using the ship, the lag can be anywhere from 1-5 seconds. if you fly for too long on the server (usually 30s for us) the server crashes.
> 
> (also note this happens on a single player world, just less intense)
> 
> I love the mod, but until the lag is fixed, its not worth having on my server

Did you ever figure out a solution to this??

**Comment by S-moreo** [comment]
I'm having the same issue on 1.20.1

Log:
https://mclo.gs/BaBzqn7

**Comment by nvrsbr** [comment]
Same issue as S-moReo above.
1.20.1

**Comment by Bluperman949** [comment]
I'm having the same issue with VS and Eureka in 1.20.1. Console is filled with `[VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big!` and the server occasionally times everyone out.

**Comment by mikedrugs** [comment]
same issue

**Comment by Alexr360** [comment]
I am having the same issue with VS and Eureka in 1.20.1 Fabric basically no other mods.

**Comment by SomeoneYouKonw** [comment]
Same here, 1.20.1, dedecaitedserver, however ship is just getting fragmented.

**Comment by justmedic** [comment]
Identical problem on 1.18.2. There are no other mods. Is there any solution?

**Comment by TheGreat7868** [comment]
I'm having a similar problem here, but on top of that, End Crystals are unbreakable, I'm on Forge 1.20.1 47.3.7 with Create, VS2 Clockwork, Eureka!, and removing Clockwork or even Create doesn't fix the issue.

**Comment by ToxicTG100** [comment]
i have having same prob on fabric 1.20.1 i got 300 others mods

**Comment by ToxicTG100** [comment]
its using up a lot of ram

**Comment by PriestOfFerns** [comment]
Unless someone can find what mods exactly cause this, this issue is completely unreproducible

**Comment by BenCos17** [comment]
shows up for me also i think

[11:50:29] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8628978650000006E7, 67.0, -3443.662514336407] -> [-3609.497920504771, 72.02274053175302, 1.2290062650000006E7] returning empty list! this might break things 



spams this in logs 
seems to be since I added this mod

**Comment by thetheaplant** [comment]
Unable to reproduce, sort mods to find the problem.

**Comment by Alexr360** [comment]
Here is my modlist:
`
Mods:
  [✔️] [Fabric]ctov-3.4.2.jar
  [✔️] AdditionalStructures-1.20.x-(v.4.2.2-fabric).jar
  [✔️] AmbientEnvironment-fabric-1.20.1-11.0.0.1.jar
  [✔️] amendments-1.20-1.2.11-fabric.jar
  [✔️] Amplified_Nether_1.20.x_v1.2.5.jar
  [✔️] Aquamirae 6.jar
  [✔️] architectury-9.2.14-fabric.jar
  [✔️] ati_structures(1.20)_v1.1.0_FABRIC.jar
  [✔️] BadOptimizations-2.1.4-1.20.1.jar
  [✔️] bellsandwhistles-0.4.5+1.20.1-FABRIC.jar
  [✔️] betterarcheology-1.2.1-1.20.1.jar
  [✔️] betterchunkloading-fabric-1.20.1-4.3.jar
  [✔️] BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
  [✔️] botarium-fabric-1.20.1-2.3.4.jar
  [✔️] Bountiful-6.0.3+1.20.1-fabric.jar
  [✔️] cardinal-components-api-5.2.2.jar
  [✔️] Chunky-1.3.146.jar
  [✔️] cicada-lib-0.8.0+1.20.1.jar
  [✔️] ClearDespawn-fabric-1.20.2-1.1.15.jar
  [✔️] cloth-config-11.1.118-fabric.jar
  [✔️] clutter-1.20-0.5.10.jar
  [✔️] collective-1.20.1-7.84.jar
  [✔️] comforts-fabric-6.4.0+1.20.1.jar
  [✔️] Concentration-fabric-1.20.1-1.1.6.jar
  [✔️] copycats-2.1.4+mc.1.20.1-fabric.jar
  [✔️] Couplings-1.9.4+1.20.jar
  [✔️] CraftTweaker-fabric-1.20.1-14.0.43.jar
  [✔️] create_dd-0.1d.jar
  [✔️] create_enchantment_industry-1.2.16.jar
  [✔️] create_ironworks-2.7.0-fabric-1.20.1.jar
  [✔️] create_lt-1.0.1-fabric-mc1.20.1.jar
  [✔️] create_power_loader-1.5.3-mc1.20.1-fabric.jar
  [✔️] create_ultimate_factory-1.8.0-fabric-1.20.1.jar
  [✔️] create-cards-1.2.jar
  [✔️] createcobblestone-1.4-beta+fabric-1.20.1-49.jar
  [✔️] createcontraptionterminals-fabric-1.20-1.0.0.jar
  [✔️] createdeco-2.0.2-1.20.1-forge.jar
  [✔️] create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
  [✔️] createlagless-0.2.jar
  [✔️] create-man-of-many-planes-1.0.jar
  [✔️] create-man-of-many-planes-1.0(1).jar
  [✔️] create-new-age-fabric-1.20.1-1.1.2.jar
  [✔️] CreateNumismatics-1.0.7+fabric-mc1.20.1.jar
  [✔️] createrailwaysnavigator-fabric-1.20.1-0.6.0.jar
  [✔️] create-train-perspective-1.0.0+mc1.20.1.jar
  [✔️] CreateTweaker-fabric-1.20.1-4.0.10.jar
  [✔️] cristellib-1.1.5-fabric.jar
  [✔️] Crystal-Clear-2.1-Beta-fabric.jar
  [✔️] cupboard-fabric-1.20.1-2.3.jar
  [✔️] DeathKnell-Fabric-1.20.1-10.0.4.jar
  [✔️] Debugify-1.20.1+2.0.jar
  [✔️] design_decor-0.4.0b_fabric+1.20.1.jar
  [✔️] disableportalchecks-1.0.0.jar
  [✔️] DistantHorizons-fabric-2.1.3-a-dev-1.20.1.jar
  [✔️] do_a_barrel_roll-fabric-3.6.1+1.20.1.jar
  [✔️] dragonfight-fabric-1.20.1-4.3.jar
  [✔️] dummmmmmy-1.20-2.0.3-fabric.jar
  [✔️] dungeons-and-taverns-3.0.3.f[Fabric].jar
  [✔️] DungeonsArise-1.20.x-2.1.58-fabric-release.jar
  [✔️] earth2java-fabric-1.10.1+1.20.1.jar
  [✔️] EndsPhantasm-1.20.1-0.1.jar
  [✔️] enhancedblockentities-0.9+1.20.jar
  [✔️] entityculling-fabric-1.7.1-mc1.20.1.jar
  [✔️] eureka-1201-1.5.1-beta.3.jar
  [✔️] explorations-fabric-1.20.1-1.6.1.jar
  [✔️] exposure-1.20.1-1.7.7-fabric.jar
  [✔️] extendedgears-2.1.1-1.20.1-0.5.1.f-fabric.jar
  [✔️] fabric-api-0.92.2+1.20.1.jar
  [✔️] fabric-end-remastered-5.2.4.jar
  [✔️] fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar
  [✔️] FancyBlockParticles-1.20.1-fabric-20.1.1.1.jar
  [✔️] FarmersDelight-1.20.1-2.2.0+refabricated.jar
  [✔️] fast-ip-ping-v1.0.5-mc1.20.4-fabric.jar
  [✔️] ferritecore-6.0.1-fabric.jar
  [✔️] flamearrows-1.20.1-12-fabric.jar
  [✔️] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
  [✔️] formations-1.0.2-fabric-mc1.20.jar
  [✔️] formationsnether-1.0.5.jar
  [✔️] formationsoverworld-1.0.4.jar
  [✔️] geckolib-fabric-1.20.1-4.4.6.jar
  [✔️] guardvillagers-2.0.9-1.20.1.jar
  [✔️] Hearths v1.0.1 f12-48.jar
  [✔️] herdspanic-1.1.0.jar
  [✔️] HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar
  [✔️] ImmediatelyFast-Fabric-1.3.1+1.20.4.jar
  [✔️] immersive_aircraft-1.1.3+1.20.1-fabric.jar
  [✔️] immersive_melodies-0.3.0+1.20.1-fabric.jar
  [✔️] immersive_weathering-1.20.1-2.0.3-fabric.jar
  [✔️] Incendium_1.20.x_v5.3.5.jar
  [✔️] indium-1.0.34+mc1.20.1.jar
  [✔️] interiors-0.5.3+fabric-mc1.20.1.jar
  [✔️] iris-1.7.2+mc1.20.1.jar
  [✔️] iris-flywheel-compat-fabric1.20.1+1.1.4.jar
  [✔️] ItemsDisplayed - v1.3-1.20.1.jar
  [✔️] jei-1.20.1-fabric-15.20.0.105.jar
  [✔️] Kambrik-6.1.1+1.20.1-fabric.jar
  [✔️] krypton-0.2.3.jar
  [✔️] labels-1.20-1.20.2-fabric.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] letsdo-API-fabric-1.2.15-fabric.jar
  [✔️] letsdo-bakery-fabric-1.1.15.jar
  [✔️] letsdo-brewery-fabric-1.1.9.jar
  [✔️] letsdo-herbalbrews-fabric-1.0.8.1.jar
  [✔️] letsdo-vinery-fabric-1.4.28.jar
  [✔️] liquidburner-1.20.1-0.5.jar
  [✔️] liquidburner-fabric-1.20.1-0.5.jar
  [✔️] lithium-fabric-mc1.20.1-0.11.2.jar
  [✔️] loadmyresources_fabric_1.0.4-1_MC_1.20.jar
  [✔️] lukis-grand-capitals-1.0.jar
  [✔️] lunade-fastanim-1.6-1.20.jar
  [✔️] man_of_many_planes-0.2.0+1.20.1-fabric.jar
  [✔️] map_atlases-1.20-6.0.7-fabric.jar
  [✔️] mc249136-1.0.2.jar
  [✔️] mcw-furniture-3.3.0-mc1.20.1fabric.jar
  [✔️] memoryleakfix-fabric-1.17+-1.1.5.jar
  [✔️] mes-1.3.1-1.20-fabric.jar
  [✔️] modernfix-fabric-5.19.5+mc1.20.1.jar
  [✔️] modmenu-7.2.2.jar
  [✔️] molten_metals-1.20.1-0.1.4-fabric.jar
  [✔️] moonlight-1.20-2.13.21-fabric.jar
  [✔️] moreculling-1.20.4-0.24.0.jar
  [✔️] MouseTweaks-fabric-mc1.20-2.26.jar
  [✔️] MRU-1.0.4+1.20.1+fabric.jar
  [✔️] mvs-4.1.2-1.20-fabric.jar
  [✔️] naturalist-fabric-4.0.3-1.20.1.jar
  [✔️] nerb-1.20.1-0.3-FABRIC.jar
  [✔️] netherportalspread-1.20.1-8.3.jar
  [✔️] niftycarts-20.1.3.jar
  [✔️] noisium-fabric-2.3.0+mc1.20-1.20.1.jar
  [✔️] notenoughanimations-fabric-1.7.6-mc1.20.1.jar
  [✔️] Nullscape_1.20.x_v1.2.8.jar
  [✔️] Obscure-API-16.jar
  [✔️] owo-lib-0.11.0+1.20.jar
  [✔️] Patchouli-1.20.1-84-FABRIC.jar
  [✔️] Philips-Ruins1.20.1-4.6[Fabric].jar
  [✔️] RecipeCooldown-1.0.0.jar
  [✔️] repurposed_structures-7.1.15+1.20.1-fabric.jar
  [✔️] resourcefulconfig-fabric-1.20.1-2.1.2.jar
  [✔️] resourcefullib-fabric-1.20.1-2.1.29.jar
  [✔️] rrls-4.0.6.1+mc1.20.1-fabric.jar
  [✔️] seamless-loading-screen-2.0.3+1.20.1-fabric.jar
  [✔️] skiptransitions-1.3.3+mc1.20.jar
  [✔️] SkyVillages-1.0.3.2-1.19.2-1.20.1-fabric.jar
  [✔️] sliceanddice-fabric-3.3.1.jar
  [✔️] sodium-fabric-0.5.11+mc1.20.1.jar
  [✔️] Sounds-1.0.1+1.20.1.jar
  [✔️] sparsestructures-fabric-1.20.1-2.2.0.jar
  [✔️] spyglass-improvements-1.5.1+mc1.20+fabric.jar
  [✔️] Steam_Rails-1.6.4+fabric-mc1.20.1.jar
  [✔️] supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
  [✔️] supplementaries-1.20-3.1.0-fabric.jar
  [✔️] suppsquared-1.20-1.1.16-fabric.jar
  [✔️] Surface-1.8.1-1.20.1.jar
  [✔️] tectonic-fabric-1.20.1-2.4.1b.jar
  [✔️] TerraBlender-fabric-1.20.1-3.0.1.7.jar
  [✔️] Terralith_1.20.x_v2.5.4.jar
  [✔️] threadtweak-fabric-1.20.2-0.1.1.jar
  [✔️] tidal-towns-1.3.3.jar
  [✔️] tlc-fabric-1.0.1-1.20.X.jar
  [✔️] toms_storage_fabric-1.20-1.6.8.jar
  [✔️] Towns-and-Towers-1.12-Fabric+Forge.jar
  [✔️] travelersbackpack-fabric-1.20.1-9.1.18.jar
  [✔️] TravelersTitles-1.20-Fabric-4.0.2.jar
  [✔️] valkyrienskies-120-2.3.0-beta.5.jar
  [✔️] variantsandventures-fabric-mc1.20.1-1.0.6.jar
  [✔️] villagesandpillages-fabric-mc1.20.1-1.0.1.jar
  [✔️] wetlands-1.2-1.20.1.jar
  [✔️] wildlife-1.20.1-2.2.jar
  [✔️] worldedit-mod-7.2.15.jar
  [✔️] wraith-waystones-3.3.2+mc1.20.1.jar
  [✔️] YetAnotherConfigLib-3.5.0+1.20.1-fabric.jar
  [✔️] YungsApi-1.20-Fabric-4.0.6.jar
  [✔️] YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
  [✔️] YungsBetterDungeons-1.20-Fabric-4.0.4.jar
  [✔️] YungsBetterEndIsland-1.20-Fabric-2.0.6.jar
  [✔️] YungsBetterJungleTemples-1.20-Fabric-2.0.5.jar
  [✔️] YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
  [✔️] YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar
  [✔️] YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
  [✔️] YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
  [✔️] YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
  [✔️] YungsBridges-1.20-Fabric-4.0.3.jar
  [✔️] YungsExtras-1.20-Fabric-4.0.3.jar`

**Comment by thetheaplant** [comment]
Please stop spamming modlists. This github does not exist to diagnose modpacks, find the problem mod and make a specific issue.

**Comment by Alexr360** [comment]
Sorry

**Comment by lolnypop** [comment]
Still no fix? That's a great feat to achieve...

**Comment by Stevit** [comment]
got a similar proble with the same log even in singleplayer. It should be a problem between clockwork and valkirien skies where the ship boxes are too big and they collide with other entities ones causing errors. Mo idea how to resolve this .

**Comment by DenneyLewis** [comment]
I love how multiple people have commented this is an issue yet no fix or anything has been found. My server console is being absolutely spammed with this error on 1.20.1

**Comment by nvrsbr** [comment]
I forgot about this mod long ago after this never got fixed.
I moved on to using Immersive Aircraft with the Man of Many Planes addon.
