### ISSUE TITLE
<Can't load game>

### ISSUE THREAD

**Issue by Demonmaster-MD** [ValkyrienSkies/Valkyrien-Skies-2#499]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [ ] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

When I load the game through curseforge, the following error comes up on the launcher: "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vs_clockwork'!"

![Screenshot 2023-06-15 175957](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/127668304/7334f979-4b3b-48e0-bfb2-29cbd94a5c34)
Modlist above.

The Fabric version is 0.14.21

### Issue reproduction

Install those mods on a fresh profile on Curseforge

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11760714/latest.log)

**Comment by Demonmaster-MD** [comment]
Also, what is the issue and how do I fix it?

**Comment by Rubydesic** [comment]
clockwork is in alpha version, do not ask questions about it here, try the VS discord
