### ISSUE TITLE
clouds sometimes render through cc restitched monitors

### ISSUE THREAD

**Issue by deltanedas** [ValkyrienSkies/Valkyrien-Skies-2#50]
![16:01:39](https://user-images.githubusercontent.com/39013340/172413931-c81e3152-67a0-4b98-9b73-76c070e7ba46.png)

**Comment by deltanedas** [comment]
![23:14:49](https://user-images.githubusercontent.com/39013340/189453080-569153da-34a4-459a-889c-4c2ca8381c7f.png)
cant get it to do it anymore, seems fixed

**Comment by StewStrong** [comment]
sugnoma
