### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by BraveCaperCat2** [ValkyrienSkies/Valkyrien-Skies-2#503]
### Mod Name

Not sure, had multiple other mods installed

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

When constructing a ship, the ship disappears (which should only happen while loading for a few secs) and when i go on top i get stuck and must teleport out

### Issue reproduction

1. Install mods specified in the Latest.log
2. Launch The Game
3. Create or Open a world
4. Create A Ship
5. See it not load in
6. Jump on top and see if you get stuck.

### Logs

Can't upload Latest.log - File to large (25MB are allowed, 73MB were attempted to upload)
No such thing as Debug.log (in log folder)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS, addons, and one other mod, and then create a new issue
