### ISSUE TITLE
Crashes when Tardis interior is being generated

### ISSUE THREAD

**Issue by TinycliXZ** [ValkyrienSkies/Valkyrien-Skies-2#504]
### Mod Name

New Tardis Mod

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

When the New Tardis Mod tries to generate a new dimension for the Tardis interior the game crashes to desktop, exit code 1.

### Issue reproduction

Have both mods installed. Either use the /tardis create command or spawn a broken exterior and give it completed maps until it opens, the game will then crash.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11782382/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11782383/latest.log)

**Comment by thetheaplant** [comment]
Fixed in https://github.com/WhoCraft/TardisRefined/pull/398, see https://github.com/WhoCraft/TardisRefined/pull/379
