### ISSUE TITLE
game crashes after a couple seconds

### ISSUE THREAD

**Issue by elitesdead** [ValkyrienSkies/Valkyrien-Skies-2#505]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

When I remove Valkyrien-Skies and Eureka Ships, the issue no longer persists. I am able to provide more logs if more testing is necessary. I also cant tell if it's a compatibility bug or a bug in general?

### Issue reproduction

Add Valkyrien-Skies and Eureka Ships, and it will display a multitude of errors in the logs and then crash.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11782823/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11782824/latest.log)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
