### ISSUE TITLE
Server hangs on physics thread and times players out.

### ISSUE THREAD

**Issue by nourelar** [ValkyrienSkies/Valkyrien-Skies-2#506]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

"[10:51:32] [Physics thread/WARN] [or.va.co.im.pi.VSGamePipelineStage/]: Too many physics frames in the physics frame queue. Is the game stage broken?", then I get timed out. What I expect to happen is the server booting up fine and not timing me out in 3 minutes.

### Issue reproduction

Make a server, run it, join it, play for like 2 minutes or whatever.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11801811/latest.log)

**Comment by nourelar** [comment]
I used regular servers then arclight, hell I even tried magma but to no avail.

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
