### ISSUE TITLE
Question: Will there somehow be this mod in version 1.20.1?

### ISSUE THREAD

**Issue by lostopkk** [ValkyrienSkies/Valkyrien-Skies-2#512]
I know it's too early to ask for a port, but I just wanted to clear that doubt because I would like to make a modpack focused on 1.20.1 because some recent mods are so awesome, and I love this mod. sorry if I sound rude as version 1.19.2 has just been released.

**Comment by walksanatora** [comment]
eventually:tm:

**Comment by StewStrong** [comment]
Its already on 1.20.1, we just havent published it to curse yet

**Comment by StewStrong** [comment]
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/packages/1886678
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/packages/1886677
