### ISSUE TITLE
This is a thingy request I just dont have the option for that

### ISSUE THREAD

**Issue by robit4** [ValkyrienSkies/Valkyrien-Skies-2#519]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Please add clockwork download links not in discord (full of mean people) so I have the will to ever use this mod

### Issue reproduction

:(

**Comment by Rubydesic** [comment]
This will be done by the Clockwork developer, Potato, when they feel the mod is ready for general usage.

**Comment by robit4** [comment]
ok
