### ISSUE TITLE
Game crashes on load with eureka

### ISSUE THREAD

**Issue by aperson5647** [ValkyrienSkies/Valkyrien-Skies-2#528]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

having eureka, valkyrien skies and kotlin for forge installed on 1.20.1 my game crashes on loading world

### Issue reproduction

Enable eureka, valkyrien skies and kotlin for forge on 1.20.1 and load a world

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12006157/latest.log)

**Comment by StarLitDragon404** [comment]
i am having the same issue

**Comment by Aedremor** [comment]
I have the same issue in 1.19.2, and it was working fine until a few days ago.

**Comment by StewStrong** [comment]
Looks like a conflict with rhubidium

**Comment by StewStrong** [comment]
This should be fixed in v2.3.0-beta.3
