### ISSUE TITLE
crashes with WTHIT

### ISSUE THREAD

**Issue by slodkipiesio** [ValkyrienSkies/Valkyrien-Skies-2#531]
### Mod Name

WTHIT (what the hell is that)

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Quilt

### Issue description

(idk about 1.19) it is on 1.20 and on 1.20.1 and it occures on fabric too (i tested)

### Issue reproduction

install WTHIT for quilt/fabric, download valkyrien skies. boom quilt/fabric loader will show you a crash

### Logs

[crash-2023-07-13_22.49.21.1410-quilt_loader.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12044334/crash-2023-07-13_22.49.21.1410-quilt_loader.txt)

**Comment by Rubydesic** [comment]
Can you post the crash log that you get with fabric?

**Comment by slodkipiesio** [comment]
wait what
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/95749943/134f29a1-c63d-4d21-9432-8b4f228597b3)
it now works?????

**Comment by slodkipiesio** [comment]
HUH????
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/95749943/26bf6e70-aca1-4999-8288-ad01d3806bfe)
IT CRASHES WITH QUILT BUT NOT WITH FARRIC???

**Comment by slodkipiesio** [comment]
ok thats weird, ima try jade

**Comment by slodkipiesio** [comment]
i think its like valkyrien skies works with fabric version of wthit but not the quilt version as these are different
