### ISSUE TITLE
Reach issue in Survival Mode

### ISSUE THREAD

**Issue by yosoDev** [ValkyrienSkies/Valkyrien-Skies-2#537]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

This bug happens in v2.3.0-beta.3 for 1.20.1.

When playing in survival mode, the range for placing and breaking blocks indicated by the client does not seem to match what the server accepts.
When trying to break blocks at the very edge of the range, the blocks reappear immediately.
Similarly, when placing blocks from the same distance, they disappear again.

This odd behaviour first appeared to me when chopping down trees. Logs, that where further up, kept reappearing.

I am not sure if the client indicates a longer, but wrong, range, or if the server only accepts a slightly shorter range.

This doesn't seem to be an issue in creative mode.

### Issue reproduction

While in survival mode, breaking or placing blocks as far away as possible.

**Comment by ejektaflex** [comment]
I've also seen this in 1.20.1 - when placing blocks too far away, the server sometimes rejects the placement.

**Comment by TheOneTrueDev** [comment]
Reach stays the same, I tested this earlier since I'm also having this issue on my mod pack. Works completely fine in forge un-modded but once I add ValkyrienSkies the players and I are unable to break blocks at the max reachable distance.

**Comment by laserlemons** [comment]
I can confirm this issue. Reach distance seemed lower on the server side than client side, causing issues placing and breaking blocks near the limit of the survival reach distance. The issue was fixed after uninstalling Valkyrien Skies.

**Comment by Neoblacks** [comment]
I can also confirm this issue. The reach distance with the blocks is reduced by about 1 block to almost 1.5 blocks.

**Comment by peepeepoopoocaca** [comment]
I just wanted to add that this limit is a HARD limit. Mods that increase block reach distance through the use of enchantments, potions, or items do not fix this issue. Your reach is stuck at 2-ish blocks no matter what.

**Comment by MrBuildo** [comment]
You can temporarily mitigate this by going into the vs_server.json config file and changing "enableInteractDistanceChecks" to false

**Comment by thetheaplant** [comment]
Unable to recreate in beta.5.
