### ISSUE TITLE
ConcurrentModificationException when creating inventory tabs

### ISSUE THREAD

**Issue by ejektaflex** [ValkyrienSkies/Valkyrien-Skies-2#539]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

**This actually occurs on 1.20.1**, but it wasn't an option for the version. When attempting to load the game, occasionally it will crash, giving the error below. Because it's a ConcurrentModificationException, it's difficult to reliably reproduce, as it happens at random.

Somewhere, something must be modifying (inserting/deleting) from a list/map while something else is iterating over it.

### Issue reproduction

Add your mods and load the game.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12064789/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12064790/debug.log)

**Comment by ejektaflex** [comment]
My guess is because [you are registering the tab](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/1.20.1/main/forge/src/main/kotlin/org/valkyrienskies/mod/forge/common/ValkyrienSkiesModForge.kt#L202) in an `FMLLoadCompleteEvent`. Instead, you should be using `BuildCreativeModeTabContentsEvent` in Forge, which is specifically made for registering item groups. The Fabric equivalent is the method `ItemGroupEvents::modifyEntriesEvent`.

**Comment by StewStrong** [comment]
This should be fixed in the latest 1.20 version. Please reopen this issue if Im wrong.
