### ISSUE TITLE
Blocks collisions brakes while playing in multiplayer on local server / can't place blocks to ship in multiplayer

### ISSUE THREAD

**Issue by sanchezzzz1997aaa** [ValkyrienSkies/Valkyrien-Skies-2#550]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

If you are playing in multiplayer with at leasst one connected player to your host game, you can meet a critical bug with collisions of ship that you are building with your friends. 

How this bug looks: For example, for begining, you make a board 5*8*1 out of wooden plank blocks as the hull of the future ship. Then you make it physical and starts to add more blocks to reach a needed shape. But at this point, probably, you will notice that you can't aim at the some already placed blocks on your ship. If you will try to add more blocks, you can meet the situation when you are not able anymore to place more blocks on some part of your physical construction. Also you will notice that some "buggy" blocks, that you can't aim normally, also has no collisions and you fall through them down.

But the host and all clients still can see whole ship normally, even this bug happens. Also these blocks still collide world when moving... but not a player and it's still impossible to aim them.

### Issue reproduction

After some tests, I figured out how to reproduce this bug and found TEMPORARY SOLUTION for a players to avoid it.

How to reproduce:
- start a new game and open it for lan
- connect a second player
- build a board 5*8*1 out of wooden planks
- make it physical (If you are using Eureka, you place "steering wheel" and presses "assemble ship")
- try to add more blocks as showen on the picture
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/46871247/a5daf49a-5033-404e-9b74-a5a5e2247790)
- last blocks will have completely broken collisions

Some notes: it seems this bug happens only when at least two players trying to play and when **you are increassing the "box size" of your ship**. For example, if you build your ship and only later made it simulated object, you can place a blocks inside it normally, without any problems. But if you are placing blocks that increases the maximum length/width/height of your ship, you can meet this bug.

My temporary solution:
Option 1 - if you are using Eurika, you can disassemble your ship (make it static) and add long pilars out of blocks along XYZ axis. For example, add 10 blocks forward, backward, up, down, left and right. After that, make a ship physical again. And now you can remove these additional blocks. Since this moment, a "box size" of the ship will be bigger than ship is and you will able to add blocks without problems, becouse they will not increase a box size of ship while it's physical object.

Option 2 - if you can't or just don't want to make your ship static for some time, you can use this methood: after you started your save, don't hurry to open it for lan. Add pilars out of blocks like in option 1 to increasse the box size of your ship. Only after that open a game for lan and after your friend connected, you will be able to remove this temporal pillars.

P.S. I like Valkyrien Skies very much and I want to help to fix this bug))) If there will be some problems with reproducing, we can record a video with instructions.

**Comment by VosmoslaGod** [comment]
They said they fixed this bug when I opened an issue about it but it never really was fixed, idk why but only very few people have this issue

**Comment by sanchezzzz1997aaa** [comment]
> They said they fixed this bug when I opened an issue about it but it never really was fixed, idk why but only very few people have this issue

It's a bit strange, becouse I got this bug at the latest versions on all my computers. My friend also have reproduced this bug... Java versions is different, we even tried different launchers. Probably developers did something wrong when tried to reproduce it - maybe it's rare problem, but it's very annoying. May be they fixed it only in one part of possible scenarios - anyway I can test the specific version of the mod with specific version of java and forge. If bug is really fixed, we will know what versions we shoud use to avoid it)))

**Comment by thetheaplant** [comment]
Unable to recreate
