### ISSUE TITLE
Rendering errors when using with Sodium and DH 2.0

### ISSUE THREAD

**Issue by fernandoarmengol** [ValkyrienSkies/Valkyrien-Skies-2#552]
### Mod Name

Sodium and DH2.0-dev

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

- Invisible chunks: The bug only occurs when Sodium, DH and Eureka are installed. The bug doesn't happen without sodium. Enable DH, Build a ship from Eaureka and enable physics, then the chunks will start to look invisible / transparent.

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/71931361/1d07be2f-efcb-42f7-8e6a-a325c0da0609)

- Dark LOD (from dh): Some LODs chunks randomly darken near the edge of chunks between minecraft and distant horizons. In this case it is not necessary to create any ship, the bug occurs with the mods installed.

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/71931361/3eb22218-3f7e-4167-aaa3-d46b08b6bf83)

More info and images in dh gitlab issue: https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/541

### Issue reproduction

- Invisible chunks: Install the mods, enable DH, Build a ship from Eureka and enable physics.
- Dark LODS: Play with the mods and see lods.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12223263/latest.log)

**Comment by thetheaplant** [comment]
Invisible chunks are not a VS issue, unable to recreate the latter
