### ISSUE TITLE
Crash on startup when launching with Embedium

### ISSUE THREAD

**Issue by CaptRacoon** [ValkyrienSkies/Valkyrien-Skies-2#599]
### Mod Name

embeddium-0.2.1+mc1.20.1.jar

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When launching with Embedium, game crashes.

### Issue reproduction

Install embedium (latest)

### Logs

[crash-2023-10-13_19.08.10-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12900252/crash-2023-10-13_19.08.10-client.txt)

**Comment by SLimeyMC** [comment]
This is because Embeddium is ported from Sodium 0.5. Which VS hasn't yet updated to, an alternative might be using an older version of Rubidium

**Comment by Poopooracoocoo** [comment]
You could downgrade Create as well iirc

**Comment by JoelZBub** [comment]
duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556 & https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/569 & https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/580

**Comment by vinnyg0621** [comment]
it's embeddium not embedium.

**Comment by SLimeyMC** [comment]
> it's embeddium not embedium.

Refrain from necroposting with irrelevant topic
