### ISSUE TITLE
Crash when placing block on ship

### ISSUE THREAD

**Issue by supershorty1** [ValkyrienSkies/Valkyrien-Skies-2#600]
### Mod Name

clockwork

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Assmble ship then place block

### Issue reproduction

Crash when placing block on ship

### Logs

[crash-2023-10-14_12.38.12-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12902386/crash-2023-10-14_12.38.12-server.txt)

**Comment by StewStrong** [comment]
The old clockwork isnt compatible with newer versions of vs2
