### ISSUE TITLE
<Player being teleported into the void when breaking the ship>

### ISSUE THREAD

**Issue by respear** [ValkyrienSkies/Valkyrien-Skies-2#601]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Player being teleported into the void when breaking the ship.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/99116475/5b76891c-f2b9-475d-ad72-28d8d44a59b0

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/99116475/ed907891-c17a-4d78-b998-c8630310dfd0)

I don't think this should happen.

### Issue reproduction

Build a ship.
Activate the ship.
Break the ship.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12905041/latest.log)

**Comment by respear** [comment]
I tested it without the replay mod in survival and it had the same result btw

**Comment by StewStrong** [comment]
Fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/4861dfb2107eb2665873e998c69c650eeb268781
