### ISSUE TITLE
TerraFirmaCraft generates chunks in the shipyard, corrupting existing ships

### ISSUE THREAD

**Issue by 4P5** [ValkyrienSkies/Valkyrien-Skies-2#604]
### Mod Name

TerraFirmaCraft

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

When creating a ship with either the ship creator or Eureka's ship helm, the ship assembles with no issues. After a second or two, TerraFirmaCraft begins generating chunks in the shipyard, freezing the physics and bringing a second world into the current one.

The chunks aren't from the surrounding world, and generate even after creating the ship, so it's definitely not an issue with ship assembly. My theory is that TFC doesn't realise the chunks are meant to be void, and generates terrain regardless.

### Issue reproduction

- Install TerraFirmaCraft and VS2
- Create a ship using the ship creator
- Wait a few seconds for chunks to start generating in the shipyard (you may need to go underground in spectator to see them)

**Comment by CapEugene** [comment]
Hi! Recently I decided to create my own modpack on Minecraft 1.18.2 with TerraFirmaCraft and Eureka! and get this problem too. I found one simple decision: you need to open config and in server setting find "Max Ship Blocks" and change default value (in my case, i change of 600 blocks). It helped me, so maybe you can try this on and probably its help you. GOOD LUCK (P.S: Hi from Russia)
![изображение_2024-04-13_232254743](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/144322635/25acead3-f9f5-4e98-b440-5f4018e00af9)
![изображение_2024-04-13_232336873](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/144322635/b228b837-c717-4afe-8f61-eb38ab2d20c7)

**Comment by PriestOfFerns** [comment]
your fix makes it so that ships can’t have more than 600 blocks - so goodbye to any ship bigger than 9x9x9

**Comment by thetheaplant** [comment]
Fixed in #833
