### ISSUE TITLE
Game does not launch successfully.

### ISSUE THREAD

**Issue by ErickLin81** [ValkyrienSkies/Valkyrien-Skies-2#606]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

When I launch the game, the minecraft error screen pops up "Create has failed to launch properly". I expected to see the minecraft main menu meaning successfully loading into the game.

### Issue reproduction

1. Selecting the modpack (personal modpack)
2. Launching the game
3. Error appears

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13062085/latest.log)
[crash-2023-10-21_17.41.39-fml.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13062110/crash-2023-10-21_17.41.39-fml.txt)

**Comment by PriestOfFerns** [comment]
Steam and rails is incompatible with VS2, this is a known issue

**Comment by thetheaplant** [comment]
Steam and rails has since resolved the issue.
