### ISSUE TITLE
incompatibility with Steam_Rails

### ISSUE THREAD

**Issue by Laem13** [ValkyrienSkies/Valkyrien-Skies-2#614]
### Mod Name

Steam_Rails

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Everything works without valkyrienskies or Steam_Rails. When I put it in, Minecraft says that the create mod failed to load correctly.
forge-40.2.10
Minecraft Version 1.18.2
Mods:
create (0.5.1.c, or 0.5.1e), kotlin, Steam_Rails, valkyrienskies
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/149257555/bc7dea76-82ea-4677-8a7f-99c0be895019)

### Issue reproduction

Download create (0.5.1.c, or 0.5.1e), kotlin, Steam_Rails, valkyrienskies.
Put it in folder "mods"
Opening launcher and launch minecraft.
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/149257555/51a87bf4-7fe1-488f-aa15-efda0f74b77b)

**Comment by PriestOfFerns** [comment]
known issue, steam and rails in incompatible with VS2. One of VS2's mixins causes issues with steam and rails

**Comment by Laem13** [comment]
Is it possible to solve this problem?

**Comment by Laem13** [comment]
> known issue, steam and rails in incompatible with VS2. One of VS2's mixins causes issues with steam and rails
Is it possible to solve this problem?

**Comment by PriestOfFerns** [comment]
don’t use steam and rails

**Comment by Laem13** [comment]
> don’t use steam and rails

In the future they may become compatible for 1.18.2?

**Comment by PriestOfFerns** [comment]
I'm sure they'll eventually fix it, it's just not a priority right now

**Comment by Laem13** [comment]
> I'm sure they'll eventually fix it, it's just not a priority right now

Ok. Thanks.

**Comment by thetheaplant** [comment]
Has since been fixed by steam and rails.
