### ISSUE TITLE
Apache Common Lang3 Module should not be included in ValkyrienSkies => Compatibility Issue Source Found

### ISSUE THREAD

**Issue by FirstMegaGame4** [ValkyrienSkies/Valkyrien-Skies-2#617]
Hello Valkyrien Skies developers!

I got the [same issue as bv7dev](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/616) and after some deep research on the Quilt Discord Server, we found that the issue is coming from the `ArrayUtils` class in a old apache-common-lang3 module that is packed into ValkyrienSkies! This weird `ArrayUtils` class replaces the classic one, causing crash with CompleteConfig that uses the class. (CompleteConfig is used by RegionsUnexploredFabric).

There is actually a workaround to fix it, we can just remove the apache-common-lang3 package in the mod jar, but you should remove it directly from the mod source.

**Comment by Snownee** [comment]
Any progress on this issue? This also causes a crash with [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi)

**Comment by FirstMegaGame4** [comment]
> Any progress on this issue? This also causes a crash with [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi)

wait ValkyrenSkies is also doing that weird thing on NeoForge / LexForge?

**Comment by Snownee** [comment]
> > Any progress on this issue? This also causes a crash with [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi)
> 
> wait ValkyrienSkies is also doing that weird thing on NeoForge / LexForge?

Wrong link, sorry. It was Kiwi for Fabric. Fixed now

**Comment by FirstMegaGame4** [comment]
Closed in #798
