### ISSUE TITLE
Crash on startup with Timeless and Classics Guns

### ISSUE THREAD

**Issue by supershorty1** [ValkyrienSkies/Valkyrien-Skies-2#621]
### Mod Name

Timeless and Classics Guns

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Crash on startup

### Issue reproduction

Install both mods and lunch game

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13366984/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13366986/debug.log)

**Comment by illucc** [comment]
```
Mod ID: 'forge', Requested by: 'valkyrienskies', Expected range: '[40.2.4,)', Actual version: '40.2.0'
```
Update your forge to 40.2.4 or above.

**Comment by supershorty1** [comment]
> ```
> Mod ID: 'forge', Requested by: 'valkyrienskies', Expected range: '[40.2.4,)', Actual version: '40.2.0'
> ```
> 
> Update your forge to 40.2.4 or above.

updated

**Comment by supershorty1** [comment]
> ```
> Mod ID: 'forge', Requested by: 'valkyrienskies', Expected range: '[40.2.4,)', Actual version: '40.2.0'
> ```
> 
> Update your forge to 40.2.4 or above.

Updated sry but still Crashes
new logs:
[游戏崩溃前的输出.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13368499/default.txt)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13368501/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13368502/debug.log)

**Comment by walksanatora** [comment]
I dont see architectury API being loaded

**Comment by supershorty1** [comment]
> I dont see architectury API being loaded

Added but it sti
[游戏崩溃前的输出.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13373242/default.txt)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13373243/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13373244/debug.log)
ll Crashes
