### ISSUE TITLE
incompatible with timeless and clasicss guns 1.16.5 and 1.18.5

### ISSUE THREAD

**Issue by O5-Hans** [ValkyrienSkies/Valkyrien-Skies-2#627]
### Mod Name

timeless and clasicss guns

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

game crashes as soon as i try to launch the game

### Issue reproduction

launch the game with timeless and classicss gun mod and valkerian skies installed

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13400546/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13400547/latest.log)

**Comment by DrKaltsit** [comment]
按我这个装
clockwork-forge-0.0.1-alpha350ee73315
create-1.18.2-0.5.1.f
framework-0.4.2-1.18.2
tac-a-0.3.10.2-1.18.2（在mcmod.cn装）
valkyrienskies-118-2.1.1-beta.4(或Beta6)

**Comment by HagiwaraMiona** [comment]
> 按我这个装 clockwork-forge-0.0.1-alpha350ee73315 create-1.18.2-0.5.1.f framework-0.4.2-1.18.2 tac-a-0.3.10.2-1.18.2（在mcmod.cn装） valkyrienskies-118-2.1.1-beta.4(或Beta6)

行不通，错误还是会有

**Comment by thetheaplant** [comment]
Check the wiki, use TACZ
