### ISSUE TITLE
Clockwork crashed when a new world genareted

### ISSUE THREAD

**Issue by Assashinlord** [ValkyrienSkies/Valkyrien-Skies-2#628]
### Mod Name

Create,Clockwork

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Minecraft Version
1.18.2

Forge Version
40.2.5

Other Mods
kotlin for forge 3.12.0
architechtury forge 4.11.93
not enough crashes
create 0.5.1.f
valkryien skies 2.1.1 beta
clockwork 0.0.1-alpha350ee73315

I tried to launch game with these mods.At first there was no problems but when tried to create a new world game just crashed

### Issue reproduction

1.Launch the game with mentioned mods
2.Create a new world
3.Game crashes
4.Try to rejoin the world or create a new one
5.Crash again

### Logs

https://bytebin.lucko.me/E4UcXYvFnJ

**Comment by thetheaplant** [comment]
This issue was caused by the wrong create version, use latest of both.
