### ISSUE TITLE
Breaking leads on ships causes a freeze

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#632]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

If you have a mob tied to a ship with a lead and make it break the lead the game will freeze. On a server I was on after the long freeze the mob would disappear, my hardware isn't powerful enough to test that. The issues also causes high memory usage.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/000dc76e-3e2e-475c-8ecb-464ac31b8dc0

### Issue reproduction

Tie a mob to a fence post on a ship with a lead. Then have the lead break and now the game will be partially frozen. Entities seems won't anymore, some iterations seem unaffected.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13454057/latest.log)

**Comment by MattB70** [comment]
Still happens.

**Comment by thetheaplant** [comment]
Unable to recreate on 1.18.2.
