### ISSUE TITLE
Sticker From Create causing huge lag in game<title>

### ISSUE THREAD

**Issue by kamitojaeger** [ValkyrienSkies/Valkyrien-Skies-2#633]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

If you have sticker on your ship, after activating it and have it stick to blocks from overworld or contraptions, the game would begin to lag. The lag would only stop after reentering the world

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/110318836/9d009eba-88c8-458d-b742-2f29856a8a2e)

### Issue reproduction

1. enter the world
2. create a ship with a sticker on it
3. activate the sticker
4. drive the ship into a wall to make the sticker stick to the wall
5. lag happen

**Comment by thetheaplant** [comment]
Related to #323, closing
