### ISSUE TITLE
Incompatibility with TerraFirmaCraft:The Next Generation

### ISSUE THREAD

**Issue by NewMajor73nanami** [ValkyrienSkies/Valkyrien-Skies-2#635]
### Mod Name

TerraFirmaCraft:The Next Generation

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

As shown in the picture, we encountered the issue when attempting to make TerraFirmaCraft:The Next Generation compatible with Valkyrien Skies and Clockwork. I am certain that this is not a rendering issue, as the distorted areas have entities.
We have confirmed that in a Superflat world with Valkyrien Skies and Clockwork mod, the blocks in TFC:TNG is working normally.
Could you please advise on what might have gone wrong? Does the development team have any plans to fix this bug? If not, we have to plan to organize a team to work on compatibility by ourselves. Thanks very much.

![Cache_5b9d68535191373d](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/94152219/22f597f7-f8dc-4590-b459-67ed5e4d015f)
![Cache_-7730193fa8b1bd29](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/94152219/3b63c501-7dfc-4df4-9fa2-6e99734a2fc1)

### Issue reproduction

When using Valkyrien Skies and Clockwork mod in TFC:TNG

**Comment by bmartin127** [comment]
Sir you are assembling the world as a physics object

**Comment by ewoudje** [comment]
Should be fixed with latest commit please try it out [from](https://github.com/orgs/ValkyrienSkies/packages?repo_name=Valkyrien-Skies-2). If it works please close the issue on both githubs

**Comment by NewMajor73nanami** [comment]
> Sir you are assembling the world as a physics object

Thanks a lot, I thought we had found the problem because of the mixin conflict by TFC's overridding :)
