### ISSUE TITLE
Steam n Rails Unsupported?

### ISSUE THREAD

**Issue by miolk** [ValkyrienSkies/Valkyrien-Skies-2#636]
### Mod Name

Create: Steam 'n' Rails

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Creates Addon Steam n Rails is unsupported. but there is no reason for it to be... is there any way you guys could fix ythis issue>

### Issue reproduction

there is no way to reproduce untell they fix this...

**Comment by PriestOfFerns** [comment]
Steam Rails and VS2 have an issue with mixins, that causes them to crash on launch when in the same modpack. Should be possible to fix, but it's just not really a priority from what I've seen

**Comment by thetheaplant** [comment]
Has been fixed by Steam and Rails since.
