### ISSUE TITLE
Breaks with tardis refined 

### ISSUE THREAD

**Issue by thesheriff1** [ValkyrienSkies/Valkyrien-Skies-2#641]
### Mod Name

Tardis Refined 

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

The crash occurs when you enter the Tardis

### Issue reproduction

Enter the Tardis 

### Logs

https://pastebin.com/UaS1HkSc

**Comment by shadowedblue** [comment]
+1

I worked around it by moving all my ships/valkyrien skies blocks into unloaded chunks, removing all Valkyrien skies mods, shear the Tardis roots, then adding back Valkyrien skies and I am able to enter/exit Tardis just fine.

**Comment by thetheaplant** [comment]
Duplicate of #504
