### ISSUE TITLE
FramedBlocks is causing minecraft to crash when is placed on physics object

### ISSUE THREAD

**Issue by fdno272** [ValkyrienSkies/Valkyrien-Skies-2#650]
### Mod Name

FramedBlocks

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Game crashes after I place or even just look at physics object while being close enough to place it holding specific FramedBlocks frame. How do I get dubug.log btw? 

### Issue reproduction

You need to create a physical object, make something like a wheel, you need it to move, place a vertical framed slope on it

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13667765/latest.log)
[crash-2023-12-14_03.51.33-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13667766/crash-2023-12-14_03.51.33-client.txt)

**Comment by thetheaplant** [comment]
Unable to recreate.
