### ISSUE TITLE
the game does not open please help me with this error

### ISSUE THREAD

**Issue by wardeada** [ValkyrienSkies/Valkyrien-Skies-2#657]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [ ] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Well, as I said, the game doesn't open, I don't know why, but I hope someone can help me with this problem, explain more or less what I can do when I install the mod in the mods folder and click start. and I wait for the game to load, but after a few seconds the game closes. Cave clarifies that I have a pirated launcher since I don't have the money to buy an original copy.

It is also worth noting that I have installed the following mods, here I leave an image
![captura](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/140228174/fd34c9c7-e40f-4f3a-b681-7a6c7c53fcae)

Well I hope someone can help me with this problem as I would greatly appreciate it, thank you

### Issue reproduction

.

### Logs

.

**Comment by rjulib00** [comment]
share the log, there is a folder "logs" which creates a log, even if the game doesnt start

**Comment by thetheaplant** [comment]
Valkyrien skies is not present in the attached modlist
