### ISSUE TITLE
Crash on Startup (Valkyrien Skies 2 & Timeless and Classics Guns)

### ISSUE THREAD

**Issue by MiiRuUwU** [ValkyrienSkies/Valkyrien-Skies-2#663]
### Mod Name

Timeless and Classics Guns

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

The game fails to start when the two mods are launched together (they work fine on their own)

### Issue reproduction

- Install Valkyrien Skies 2 (valkyrienskies-118-2.1.1-beta.4) and Timeless and Classics (tac-0.3.10.1-1.18.2.)

- Launch the game

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13772202/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13772203/debug.log)

**Comment by DrKaltsit** [comment]
TaC我已经测出来兼容版本了，可以按照我这个装一下试试
clockwork-forge-0.0.1-alpha350ee73315
create-1.18.2-0.5.1.f
framework-0.4.2-1.18.2
tac-a-0.3.10.2-1.18.2（在mcmod.cn的下载页面下载）
valkyrienskies-118-2.1.1-beta.4

**Comment by DrKaltsit** [comment]
瓦尔基里beta6也可以

**Comment by thetheaplant** [comment]
Use TACZ.
