### ISSUE TITLE
Joust doesnt start for no reason

### ISSUE THREAD

**Issue by MaNo-cz666** [ValkyrienSkies/Valkyrien-Skies-2#664]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

When I try to start the game whit valkerionskys and some of the addons like create interactive it joust doesent work.
It shows a unknown error.

### Issue reproduction

I joust start the game whith some of yours mods. For example: Create interactive, Create, Valkirienskies

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13773734/latest.log)

**Comment by mrsterner** [comment]
you need kotlin for forge
