### ISSUE TITLE
Unable to use server without Valkirien Skies 2 mod

### ISSUE THREAD

**Issue by Borailuce99** [ValkyrienSkies/Valkyrien-Skies-2#670]
A few days ago I created a server with several mods in minecraft 1.20.1 with fabric 0.15.1, including the Valkyrien Skies 1.20.1-fabric-2.3.0-beta.4 and Eureka 1.20.1-fabric-1.3.0-beta.2. However, giving that over the days was giving quite a few problems and crashes, I decided to uninstall both mods, but to re-enter the server with the same world, no player could move. When reinstalling these mods the problem of not moving was fixed, but we still have the initial problems of crashes.
I think I understand that the problem of not being able to move was because the world was generated with the Valkyrien+Eureka installed and the physics of the world were generated, and when deleting the mod, these movements were eliminated making it impossible to move. How could I disable or delete the mods to avoid the initial crashes, but keeping all the progress of the world and being able to move?

If it

Thanks in advance!

**Comment by ahkoukyoussef** [comment]
Same problem here , even with the lastest version that was out 1 day ago...

**Comment by backspaceCynosa** [comment]
i had the same issue except my server's world was not generated with the mod but was added later, i fixed the problem by removing "vs_ship_data.dat" from my worlds data directory and confirming that i did not still have VS and eureka installed on my client

**Comment by Rubydesic** [comment]
Other players need to remove VS from their client
