### ISSUE TITLE
<title>1.20.1 beta crashes on start up if rubidium is installed.

### ISSUE THREAD

**Issue by PrinceAbsolution** [ValkyrienSkies/Valkyrien-Skies-2#673]
### Mod Name

Rubidium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

crashes on start up.

### Issue reproduction

Install Valk with rubidium or embedium on the 1.21 version

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13800035/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13800036/latest.log)

**Comment by PrinceAbsolution** [comment]
It is also incompatible with aether

**Comment by PrinceAbsolution** [comment]
Groovy mod loader also doesnt work
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13800062/latest.log)

**Comment by Beanbag141** [comment]
I am also having this issue. Embeddium will crash the game on startup if Rubidium is also installed. I uninstalled Rubidium and Embeddium worked.

**Comment by rjulib00** [comment]
> I am also having this issue. Embeddium will crash the game on startup if Rubidium is also installed. I uninstalled Rubidium and Embeddium worked.

yes, cause they are the same mod, it says that in the error log + this isnt from this mod

**Comment by Kogomre** [comment]
yes, here is duplicate
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/677

**Comment by Witherking25** [comment]
> yes, here is duplicate
> https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/677 

This is not a duplicate. The issue you linked is a mixin related crash due to not having the kotlin stdlib in the classpath, usually from forgetting to install kotlin for forge. The crash in this issue is from some refactoring that was done to sodium that broke a bunch of mixins in vs2

**Comment by Wolfkid200444** [comment]
Having same issue with Embeddium/Rubidium on 1.20.1 it just crashes on startup

**Comment by Fureniku** [comment]
There are a number of issues mentioning this problem now, and it should be considered as a very high priority to fix. Many people use embeddium/rubidium and in some cases they can't be removed, meaning Valk has to be dropped instead

**Comment by Liamgrayskull** [comment]
Considering Embeddium/Rubidium is a fork of Sodium, and the 0.5 update across the board broke VS compat with it, they're working on a patch for the issue as shown here in the discord: https://discord.com/channels/244934352092397568/662249805430390795/1192376281115922494

**Comment by heretoctrl-c** [comment]
[vs crash document.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14027417/vs.crash.document.txt)
why tho

**Comment by ewoudje** [comment]
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556
