### ISSUE TITLE
discord invite invalid

### ISSUE THREAD

**Issue by Olibobs1** [ValkyrienSkies/Valkyrien-Skies-2#695]
I have no idea where to put this except here, but the discord invite is invalid.

**Comment by Rubydesic** [comment]
It's not, you're probably banned

**Comment by Rubydesic** [comment]
If you give your username, I can look up the reason

**Comment by Olibobs1** [comment]
Olibobs1#7372
Yes I was banned, however, it was for a fair reason but before being banned I was asked to resolve the issue, I did, apologised and was later banned. The issue was having the n word as my pronouns which I do see as a problem therefore I did change it when asked, I was having a dispute with someone over a separate matter who then looked at my profile and called a mod. I found that person on another server and made up, so If I could be unbanned so I have access to alphas I would appreciate it.

I presumed the invite was invalid as I tried on multiple devices with different accounts to rejoin.

If you want anymore information on the situation just ask. Thanks.
