### ISSUE TITLE
When i use Valkyrien, Kotlin and Eureka my game instantly closes after launching

### ISSUE THREAD

**Issue by Smoker120900** [ValkyrienSkies/Valkyrien-Skies-2#696]
### Mod Name

i have +100 mods (i'm making a modpack), i don't know which one is causing the issue

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I open the game and it closes, it is supposed to open and let me play

### Issue reproduction

Open the game and it will instantly close during the loading screen

### Logs

[crash-2024-01-18_01.36.15-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13972229/crash-2024-01-18_01.36.15-client.txt)

**Comment by Roshag** [comment]
Sodium/Rubidium/Embeddium. Not compatible atm.

**Comment by Smoker120900** [comment]
so that's the reason, thanks, i'll wait for the compat

**Comment by ewoudje** [comment]
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556
