### ISSUE TITLE
Not compatible with Rubidium Extras' "Max Entity Distance" culling

### ISSUE THREAD

**Issue by CritLoren** [ValkyrienSkies/Valkyrien-Skies-2#707]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Entity blocks (chests, signs, skulls) appear invisible when the "Max Entity Distance" toggle is enabled in the settings provided by [Embeddium/Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras). I presume this is an issue because the entities 

### Issue reproduction

1. Add Valkyrien Skies and the [Embeddium/Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) mod
2. Place a chest inside the prospective ship
3. Build a ship
4. Watch the chest no longer be visible (at least when you sail far enough)

**Comment by BigBro27** [comment]
i have the same :(

**Comment by Hastagaspatcho** [comment]
This also happens with the same setting in embeddium++ 1.2.13 as well.

**Comment by thetheaplant** [comment]
Given that the ships are in the shipyard, millions of blocks away, max entity culling distance must be disabled for the blocks to appear.
