### ISSUE TITLE
Valkyrien Skies 2 is incompatible with TerraFirmaCraft

### ISSUE THREAD

**Issue by DedMaxim** [ValkyrienSkies/Valkyrien-Skies-2#711]
### Mod Name

TerraFirmaCraft

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Game won't launch when TerraFirmaCraft and Valkyrien Skies 2 are installed.

Error message:
TerraFirmaCraft (tfc) has failed to load correctly
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

System:
Windows 10 22h2, Atlas mod
Intel Xeon E5-2680 v2
DDR3 ECC REG 4x8Gb
Nvidia GTX 1070

Minecraft:
Game version - 1.20.1
Forge 47.2.19

Patchouli 84 (required by TFC)
kotlinforge 4.10.0 (required by VS2)
TerraFirmaCraft 3.1.6
ValkyrienSkies 120-2.1.3

### Issue reproduction

Install mentioned above mods and try launching the game

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14095280/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14095284/debug.log)

**Comment by DarthSidiousPalpatine** [comment]
Bumping up +1. Same error log, same versions.

**Comment by DarthSidiousPalpatine** [comment]
If only this was fixed... I really want to try to make a simple addon for VS and TFC.

**Comment by Coach-mdl** [comment]
Please correct me if I'm wrong but from what I've heard it's an issue with just about anything that changes the worldgen drastically. Terrafirmacraft generator generates land where the shipyard is supposed to be.

Would it make sense to have VS2 generate the shipyard during the final stages of world loading after all the other mods have finished to ensure that the shipyard gets generated properly? Or is it more nuanced than I think?

**Comment by thetheaplant** [comment]
Fixed in #833

**Comment by MayTheCutie** [comment]
> Would it make sense to have VS2 generate the shipyard during the final stages of world loading after all the other mods have finished to ensure that the shipyard gets generated properly? Or is it more nuanced than I think?

I would assume so, since its a structure of sorts. It would need to generate on the specific biome
