### ISSUE TITLE
1.20.1 Valkyrien skies, and Clockwork do not work with embeddium

### ISSUE THREAD

**Issue by jojofenin99** [ValkyrienSkies/Valkyrien-Skies-2#714]
### Mod Name

Valkyrien skies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

It says it cannot inject something in the crash log, also the embeddium dev said it has to be fixed on valkyrien skies’s side

### Issue reproduction

get Valkyrien skies , create, clockwork, and kotlin, with Architectury, with embeddium, embeddium++ ,and Tex trues embeddium options 

### Logs

[2024-01-31-2.log](https://github.com/embeddedt/embeddium/files/14119421/2024-01-31-2.log)
[crash-2024-01-31_21.09.25-client.txt](https://github.com/embeddedt/embeddium/files/14119423/crash-2024-01-31_21.09.25-client.txt)

**Comment by Rubydesic** [comment]
duplicate
