### ISSUE TITLE
Incompatible with Embeddium

### ISSUE THREAD

**Issue by Camawama** [ValkyrienSkies/Valkyrien-Skies-2#717]
### Mod Name

Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The game refuses to boot up when both mods are installed together. Embeddium dev says it has to be fixed on your end!
https://github.com/embeddedt/embeddium/issues/179

### Issue reproduction

Install Embeddium, Install Valkyrien Skies, and attempt to start the game.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14135559/latest.log)

**Comment by PriestOfFerns** [comment]
It’s being worked on, it’s a known issue and it’s duplicate issue

**Comment by Camawama** [comment]
> It’s being worked on, it’s a known issue and it’s duplicate issue

Sounds good! Sorry for the duplicate issue report.

**Comment by Camawama** [comment]
It seems like it was fixed recently. I have been testing it and seems to work fine!!!

**Comment by MeditatorLogic** [comment]
UNTIL 6.1.2024, is hasnt been fixed?????????????

**Comment by Camawama** [comment]
Try these two versions.

Embeddium 0.3.19
Valkyrien Skies 120-2.3.0-beta.5

**Comment by MeditatorLogic** [comment]
Thx a lot, since i've tried.
Despite, i still filled.
Dont know wha's happening :(
#859

**Comment by myfirsttry567** [comment]
> Try these two versions.
> 
> Embeddium 0.3.19 Valkyrien Skies 120-2.3.0-beta.5

omg, thank you so much, after 15 attemp i finally found this and it workk, i can only say thank you so much
