### ISSUE TITLE
<title>In the Arclight server, the VS2 component randomly causes server crashes.

### ISSUE THREAD

**Issue by wglpython** [ValkyrienSkies/Valkyrien-Skies-2#718]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

The server's performance utilization is less than half, and upon reviewing the logs, I can only determine that it is likely caused by mixins, but I am unable to resolve the issue. The server crashes approximately four to five times every day due to this problem.

### Issue reproduction

 I'm not sure because everything seems to be perfectly normal, except for the random crashes caused by VS2 leading to server shutdowns.

### Logs

[crash-2024-02-02_20.17.27-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14151588/crash-2024-02-02_20.17.27-server.txt)

**Comment by wglpython** [comment]
@ewoudje  I apologize for bothering you, but my technical team informed me that the specific situation is completely opaque, and we can only report it to the official development team of VS2.

**Comment by walksanatora** [comment]
why not check with arclight also since their job is to be fully interopable
this is why hybrid plugin and modded do not mix well (espically for forge)

**Comment by wglpython** [comment]
> 为什么不检查一下 Arclight，因为它们的工作是完全可互操作的，这就是为什么混合插件和修改不能很好地混合的原因（尤其是对于 Forge 而言）

 Because I can't find any alternative server other than Arc.

**Comment by walksanatora** [comment]
I dont see any issues on the Arclight github. also make one there

**Comment by wglpython** [comment]
> Arclight

ok
