### ISSUE TITLE
CTD when placing Crystal sign from Aether

### ISSUE THREAD

**Issue by sprocketaudio** [ValkyrienSkies/Valkyrien-Skies-2#724]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Games crashes to desktop when you place a crystal sign from the aether mod.

### Issue reproduction

Install  aether and VS, place crystal sign

VS 2.1.2 beta1
Aether 1.2.0

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14226295/latest.log)
[crash-2024-02-09_20.58.55-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14226296/crash-2024-02-09_20.58.55-client.txt)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS, addons, and one other mod, and then create a new issue
