### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by jkd69** [ValkyrienSkies/Valkyrien-Skies-2#733]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [ ] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I tried making one of my creatins a physics object and the game instantly crashed now everytime i try to join that world the game crashes every other world works perfectly fine

### Issue reproduction

i have no idea

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14271257/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14271258/debug.log)

**Comment by ewoudje** [comment]
Seems to be sodium, you didn't test this without any other mods as specified in your issue.
Sodium is tracked here https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556

**Comment by Rubydesic** [comment]
Clockwork reports are not accepted on the VS2 issue tracker. If you  have an issue with Clockwork, report it in the #support channel on the [Discord](https://discord.gg/7N8xVdvMYr) server. Clockwork is in alpha, so your issue may not be resolved immediately.
