### ISSUE TITLE
Crash when rendering Create blocks on ships with Flywheel backend set to batching

### ISSUE THREAD

**Issue by SomeoneTookSima713** [ValkyrienSkies/Valkyrien-Skies-2#739]
### Mod Name

Flywheel

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Having the Flywheel backend set to batching, then placing a block from the Create mod that uses the Flywheel renderer (e.g. a creative motor) on a ship or assembling a Create contraption on a ship crashes the game with a ClassCastException.

This issue not only occurs on 1.18.2, but I've also been able to reproduce this issue on 1.19.2 and 1.20.1, all with the same crash. I've uploaded the `debug.log` and `latest.log` files from all three versions.

### Issue reproduction

1. Install the newest versions of VS2, Kotlin for Forge and Create
2. Set the rendering backend of Flywheel to batching
3. Create a ship with the Ship Creator tool from VS2
4. Place a Creative motor from the Create mod onto the ship

### Logs

[debug-1.18.2.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315990/debug-1.18.2.log)
[latest-1.18.2.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315991/latest-1.18.2.log)
[debug-1.19.2.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315992/debug-1.19.2.log)
[latest-1.19.2.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315993/latest-1.19.2.log)
[debug-1.20.1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315998/debug-1.20.1.log)
[latest-1.20.1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14315999/latest-1.20.1.log)

**Comment by BHASVIC-sholtocoulter23** [comment]
I am getting this issue too except I am on fabric
