### ISSUE TITLE
Valkyrien Skies on Aternos

### ISSUE THREAD

**Issue by Nighelation** [ValkyrienSkies/Valkyrien-Skies-2#741]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I am trying to run Valkyrien Skies on an Aternos server, and I keep getting this error in the log: https://mclo.gs/eKzZ7DP.  When I tested my server with only Valkyrien Skies and addons(eureka, architechtury, citadel, kotlin for forge and moonlight), the server won't crash.  But when I try to add more mods in, the server will crash right after startup.  Regardless of how it behaves with or without other mods, I'd still like to figure out why it's giving me an error.

### Issue reproduction

Make an Aternos server with the forge version for 1.20.1 and add on the latest compatible version of all the mods described.

### Logs

https://mclo.gs/eKzZ7DP

**Comment by Rubydesic** [comment]
It's not really an error, it just means the game is lagging
