### ISSUE TITLE
ships have a inaccurate hitboxes

### ISSUE THREAD

**Issue by bob1to** [ValkyrienSkies/Valkyrien-Skies-2#742]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

ships that are big seem to be affected by real blocks from a bigger distance that usual
![2024-02-19_20 35 20](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/154676065/afa7d57f-62f7-455e-a5b3-3db48b59e421)
![2024-02-19_20 36 26](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/154676065/7239a4ea-52de-4c62-9623-f2e92ab1901e)

### Issue reproduction

make a somewhat big ship on a flat ground and it will levitate(the bigger the larger the distance)

**Comment by xiewuzhiying** [comment]
You can mitigate this by setting the LOD Detail value to a larger value in the mod settings.
