### ISSUE TITLE
<crash and entity display problem >

### ISSUE THREAD

**Issue by witherHong** [ValkyrienSkies/Valkyrien-Skies-2#751]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I'm using PojavLauncher to play Minecraft, but after installing the Valkyrien Skies mod, the game crashes as soon as I open the world. Does anyone know what's going on?
![Screenshot_20240229_205150](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159994069/dc3630de-9faa-44a5-9012-d15e88659fec)
This screenshot shows where the crash report indicates a problem with the mod. I unpacked it to check. By the way, when I join a server, everything works fine. It only crashes when I open my own world
btw i also got some problem in server.i cant see entity such as the cover of chest and alot of mod entity
but worked normally.

Here is the crash report
[crash-2024-02-29_20.33.32-server.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14449959/crash-2024-02-29_20.33.32-server.txt)

### Issue reproduction

1.put valkyrien skies mod in mods folder
2.open game
3.create world
4.crash

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14450182/latest.log)

**Comment by ewoudje** [comment]
Pojav Launcher is not supported atm, this happens because our phyics engine is native.
You can join servers since then they run the native phyics engine.
