### ISSUE TITLE
Loaded Mod into our 1.18.2 Multiplayer server and my Client. But it continues to say Server does not have correct version.

### ISSUE THREAD

**Issue by Zindith** [ValkyrienSkies/Valkyrien-Skies-2#752]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

I have just installed the mod on our Multiplayer server and my client with the dependency. However when I go to connect, it refuses my connect saying the server doesn't have the correct version of Valkyrien Skies or even have the mod at all. So I opened up a new world no mods, nothing. And just popped in the mod and dependency, and got the same issue. I have no clue what's going on here. I also made sure to grab the most recent Forge version, as well as the most recent version of Kotlin for 1.18.2 as well. Would love some help please. Also error is in the picture for reference.
![Valkyrian Skies Bug](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/46834185/26f226c9-149d-4b22-aa81-79e63c7b4ba5)

### Issue reproduction

Just add both Valkyrien Skies and Kotlin 1.18.2 to any multiplayer server and client and try to connect. Maybe it's something to do with my host, we use Pebblehost, I have no clue if it's an issue with something on their end. But that's it.

**Comment by Rubydesic** [comment]
Update Valkyrien Skies on both server and client to latest version
