### ISSUE TITLE
Server crash 1.19.2 VS ERROR WHILE LOADING SHIP DATA

### ISSUE THREAD

**Issue by Subrodai** [ValkyrienSkies/Valkyrien-Skies-2#759]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

while I try to lauch the server he cant launch and indicate an error while loading ship data
[crash-2024-03-08_05.43.03-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14533361/crash-2024-03-08_05.43.03-server.txt)

On my client with the "STEAMPUNK [LPS]" modpack I can load the world and when I try to assemble a ship my game crash with the code error 1

### Issue reproduction

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/103133566/350cb8b6-b6a6-4e83-8f23-d6632446a828)
just install these it's a pack with just my create mod and VS2 for the big version of my mod pack it's "Steampunk [LPS]" on curseforge

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14533374/latest.log)
[crash-2024-03-08_05.43.03-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14533376/crash-2024-03-08_05.43.03-server.txt)

**Comment by Rubydesic** [comment]
You cannot save worlds with new version of VS and then load them with an old version.
