### ISSUE TITLE
Fix lag spikes caused by entity collision

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies-2#76]
This problem is exacerbated by the fact that ships do not have an AABB (see #28), but adding one will not fix the problem entirely. When an entity collides with an unloaded chunk, the chunk is forced to load, causing a large lag spike. 

Entities should be frozen in place and until the chunk they are in can be loaded rather than forcing the chunk to be loaded in the same tick.

TBD: should entities also load queue the chunk they're in to be loaded or should they just remain suspended until a player gets close enough to load the chunk?

**Comment by StewStrong** [comment]
Fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/81

**Comment by StewStrong** [comment]
Why is this open
