### ISSUE TITLE
whenever a physics bearing is loaded anywhere, my game just crashes instantly.

### ISSUE THREAD

**Issue by thatguysdad** [ValkyrienSkies/Valkyrien-Skies-2#761]
I was playing Minecraft clockwork and I was looking through jei, then my game just crashed, luckily minecraft saved before it closed and the launcher hit me with an error, here it is:

[crash-2024-03-12_12.35.07-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14578012/crash-2024-03-12_12.35.07-client.txt)

As I myself am not good at coding, this made no sense, but the the message in the Minecraft launcher read this:

The game crashed whilst rendering block entity
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.RenderType$CompositeRenderType from class org.valkyrienskies.clockwork.ClockworkRenderTypes (net.minecraft.client.renderer.RenderType$CompositeRenderType is in module minecraft@1.19.2 of loader 'TRANSFORMER' @7d986d83; org.valkyrienskies.clockwork.ClockworkRenderTypes is in module vs_clockwork@1.19.2-0.1.13-forge-4621aeec07 of loader 'TRANSFORMER' @7d986d83)

"the game crashed whilst rendering block entity" this I understood, and I loaded the game up again, and eventually found said block, the physics bearing. 
Whenever I would search up the physics bearing in jei or place it down, (the latter completely preventing you from opening the world) the game would crash. 

The funny part is, I actually need the physics bearing in my create build, so if anyone knows how I could fix this issue, it would be greatly appreciated. :)

**Comment by PriestOfFerns** [comment]
Do you have architectury api installed? It’s a dependency of clockwork

**Comment by Rubydesic** [comment]
Clockwork reports are not accepted on the VS2 issue tracker. If you  have an issue with Clockwork, report it in the #support channel on the [Discord](https://discord.gg/7N8xVdvMYr) server. Clockwork is in alpha, so your issue may not be resolved immediately.
