### ISSUE TITLE
game crashes or get very laggy when i use phys bearing

### ISSUE THREAD

**Issue by ChatoXYZ** [ValkyrienSkies/Valkyrien-Skies-2#762]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

game crashes or get very laggy when i use phys bearing (crashes when i tried making a turnable tank, Very laggy when i use the bearing in a plain new world) 

### Issue reproduction

just use the phys bearing anywhere

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14607118/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14607122/latest.log)
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/mod_list)

**Comment by Rubydesic** [comment]
Clockwork reports are not accepted on the VS2 issue tracker. If you  have an issue with Clockwork, report it in the #support channel on the [Discord](https://discord.gg/7N8xVdvMYr) server. Clockwork is in alpha, so your issue may not be resolved immediately.
