### ISSUE TITLE
Unexpected Game Crash

### ISSUE THREAD

**Issue by CaptainAngle** [ValkyrienSkies/Valkyrien-Skies-2#765]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

crash when switching to clockwork creative tab

### Issue reproduction

open clockwork creative tab

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14616548/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14616549/debug.log)

**Comment by CaptainAngle** [comment]
The launcher shows this error

The game crashed whilst rendering item
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.RenderType$CompositeRenderType from class org.valkyrienskies.clockwork.ClockworkRenderTypes (net.minecraft.client.renderer.RenderType$CompositeRenderType is in module minecraft@1.20.1 of loader 'TRANSFORMER' @31e739bf; org.valkyrienskies.clockwork.ClockworkRenderTypes is in module vs_clockwork@1.20.1-0.1.13-forge-8cf946b78e of loader 'TRANSFORMER' @31e739bf)

**Comment by Yoshiman5551** [comment]
I have the same issue and I'm using GDLauncher. Crash report here: https://mclo.gs/JMFoFFc.

**Comment by Yoshiman5551** [comment]
I have the same issue and I'm using GDLauncher. Crash report here: https://mclo.gs/JMFoFFc#L1.

**Comment by PriestOfFerns** [comment]
1. This is the VS2 github. It's issue's tab is for posting VS2 issues. This is an issue with clockwork
2. You seem to be missing architechtury API, a dependency of clockwork

**Comment by VeiTheOne** [comment]
A: I'm having the same issue.
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/82922007/4d8603bb-6cb2-41a5-abc1-636e3aa61c7f)

B: It doesn't say anywhere that that API was needed.
C: Why does this happen?
D: Clockwork's Discord link= no working, so.....

**Comment by Rubydesic** [comment]
Clockwork reports are not accepted on the VS2 issue tracker. If you  have an issue with Clockwork, report it in the #support channel on the [Discord](https://discord.gg/7N8xVdvMYr) server. Clockwork is in alpha, so your issue may not be resolved immediately.

**Comment by batgab02** [comment]
What APIs are needed for Clockwork to work?
otherwise how do all these YouTubers use it?
