### ISSUE TITLE
Cannot Launch Due to TrackBlockOutlineMixin

### ISSUE THREAD

**Issue by OnesAndZer0s** [ValkyrienSkies/Valkyrien-Skies-2#768]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Cannot launch due to incomplete Create Compat

### Issue reproduction

- Build `1.20.1/main`
- `./gradlew -p ./forge runClient`
Crashes due expecting a different Mixin for `harvest` in `MixinTrackBlockOutline.java`

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14628902/latest.log)

**Comment by Rubydesic** [comment]
should be fixed
