### ISSUE TITLE
VS-Core github link is useless

### ISSUE THREAD

**Issue by nohax955** [ValkyrienSkies/Valkyrien-Skies-2#772]
the link provided in the description to the vs core doesnt work pls fix

**Comment by thetheaplant** [comment]
VS-core is private, ewo has a defunct version on their profile.

**Comment by nohax955** [comment]
o ok

**Comment by Hex4dec** [comment]
The maven is still up, which includes a -javadoc and -sources jar, it's not private.

**Comment by Hex4dec** [comment]
@Rubydesic Seems like my account got flagged by GitHub and the notification didn't go through, pinging again. Sorry for the inconvenience.
