### ISSUE TITLE
Game Majorly Lags

### ISSUE THREAD

**Issue by SirBlueAxolotl** [ValkyrienSkies/Valkyrien-Skies-2#773]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

If I load into a world with a 9x14x13 mini-ship it's fine at first, but then it starts spamming in logs "Too many physics frames in the physics frame queue. Is the game stage broken?" and "java.lang.Exception: Collision box is too big! AABB[-357.48366827614365, -13696.959238825844, 10.27484571338158] -> [60600.55169005297, 90.39520795816995, 343.4021876823907] returning empty list! this might break things". 
Also, it's not compatible with Pehkui.

### Issue reproduction

1. Create a world in fabric 1.20.1 with these mods: https://drive.google.com/drive/folders/1M0sm42FreD3_uII0XkyPiNuIO8mzht9H?usp=sharing
2. Use the mini ship creator twice on a block.
3. Make that mini-ship 9x14x13.
4. Stare at the mini-ship until the logs start spamming or crashes.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14734202/latest.log)
[crash-2024-03-23_18.29.38-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14734203/crash-2024-03-23_18.29.38-server.txt)

**Comment by SirBlueAxolotl** [comment]
Nevermind. Pehkui was causing the lag.

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
