### ISSUE TITLE
Ship becomes invisible after being assembled

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [ValkyrienSkies/Valkyrien-Skies-2#774]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Nothing much, it's just that no matter what the size of the ship is, it just disappears / becomes invisible after being assembled. That's what I know and I'm very upset about this.

### Issue reproduction

I don't think that it's a performance issue or a client issue, I've checked both and none is the problem. It's not texture packs as I've tried it without mine and there is no difference. See if that's fixable.

**Comment by SuperSpaceEye** [comment]
You probably have optifine or immersive portals installed. Remove them.

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
