### ISSUE TITLE
The mass of water is too high after the Weightloss Update

### ISSUE THREAD

**Issue by xiewuzhiying** [ValkyrienSkies/Valkyrien-Skies-2#777]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/92735961/4961efb6-7795-4930-a344-f9a0ad199bff)
Stones (and other heavy blocks) should not float on water

### Issue reproduction

Create a ship out of some "heavy" blocks and place it in the water.

**Comment by thetheaplant** [comment]
Fixed in #775
