### ISSUE TITLE
Sodium compatibility

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies-2#78]
The mod is currently incompatible with [Sodium](https://github.com/CaffeineMC/sodium-fabric). Should hopefully be not too hard to fix. Probably have to replace MixinLevelRenderer, MixinClientChunkCache, MixinViewArea, and some others.

**Comment by juan-90s** [comment]
hope could fix the incompatible with [Rubidium](https://github.com/Asek3/Rubidium), a fork of Sodium on forge
