### ISSUE TITLE
1.20.1 - Crash when using Rubidium 0.7.1x with VS 2.3.0-beta.5

### ISSUE THREAD

**Issue by Beckstation** [ValkyrienSkies/Valkyrien-Skies-2#780]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Using Latest Rubidium, 0.7.1/a and Latest VS, 2.3.0 Beta 5, creating a ship results in a crash every time.

### Issue reproduction

Have both Latest Rubidium and VS installed and try to create an airship/ship.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14761631/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14761632/debug.log)
[crash-2024-03-26_16.19.04-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14761635/crash-2024-03-26_16.19.04-client.txt)

**Comment by Rubydesic** [comment]
not supported only sodium0.5/embedium
