### ISSUE TITLE
Loading embeddium causes entity blocks to not render

### ISSUE THREAD

**Issue by MKMKLMLM** [ValkyrienSkies/Valkyrien-Skies-2#783]
### Mod Name

embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

forge: 4.7.2.21
valkyrienskies-120-2.3.0-beta.5
eureka-1201-1.3.0-beta.4
kotlinforforge-4.10.0-all
embeddium-0.3.9+mc1.20.1
In picture, many vanilla blocks cannot be rendered. My mouse points to an vanilla chest, but it completely not rendered
"Use Block Face Culling" and "Use EntityCulling" have been turned off in the video settings, but they are completely invalid
Embeddium++has been tested and is also invalid
![2024-03-28_21 10 43](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/87943192/ea3ad09d-70b5-4108-9098-d60c6194474e)

### Issue reproduction

forge: 4.7.2.21
Both versions 4.7.2.21 and 4.7.2.0 have been tested
mod list:
valkyrienskies-120-2.3.0-beta.5
eureka-1201-1.3.0-beta.4
kotlinforforge-4.10.0-all
embeddium-0.3.9+mc1.20.1

Every Valkyrien structure will encounter this problem

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14790252/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14790259/debug.log)

**Comment by MKMKLMLM** [comment]
After testing, it was found that embeddedium-0.3.11 also had issues

**Comment by Rubydesic** [comment]
So, it turns out that embeddium adds extra code that Sodium 0.5.8 doesn't have. I will investigate this.

**Comment by Beckstation** [comment]
If using Oculus for shaders with Embeddium - Use Oculus Flywheel Compat to fix the issue until VS updates to fix.

**Comment by AlexDerProGamer** [comment]
same problem with clockwork (gyro, phys bearing, propeller bearing):

vs2: 2.3.0-beta.5
clockwork: 1.20.1-0.1.13-forge-8cf946b78e
embeddium: 0.3.12+mc1.20.1
embeddium++: 1.20.1-v1.2.5
eureka (idk if it matters): 1.3.0-beta.4

**Comment by Rubydesic** [comment]
update embedium disable any distance based culling in embedium+
