### ISSUE TITLE
Randomly black hitboxes and green center of mass

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#792]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

When moving around the lines denoting the ship hitbox and center of mass change color seemingly randomly. It may be a feature, but I wouldn't think so. If it was showing that a ship isn't being ticked then why did the ship in the video move?

The hitboxes change from purple and red to black while the center of mass changes from yellow to green.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/fb1605d3-bbe3-4b8e-aa28-a6e7749ad50b

### Issue reproduction

1. create a few ships
2. fly around and see if the lines change color

**Comment by thetheaplant** [comment]
Unable to replicate, are any other mods present?

**Comment by AlexanderwithaA** [comment]
Nope

**Comment by thetheaplant** [comment]
I tried to replicate it for the better part of 10 minutes, closing for now.
