### ISSUE TITLE
CTD with Panda's Falling Tree's

### ISSUE THREAD

**Issue by RowanSkie** [ValkyrienSkies/Valkyrien-Skies-2#797]
### Mod Name

Panda's Falling Tree's

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Crash to desktop with Panda's Falling Tree's. Should work instead.

Relevant issue on the other mod: https://github.com/PandaDap2006/Pandas-Falling-Trees/issues/57

### Issue reproduction

1. Install Valkyrien Skies 2.
2. Install Panda's Falling Tree's.
3. Run Game
4. CTD.

### Logs

https://mclo.gs/GhUb0ZO <- Crash Txt

https://mclo.gs/2y7U1Ub <- Latest.log

**Comment by Rubydesic** [comment]
I don't think this issue has anything to do with Valkyrien Skies
