### ISSUE TITLE
please fix: "java.lang.NoClassDefFoundError: org/valkyrienskies/core/impl/datastructures/DenseBlockPosSet" when using vs: tournament

### ISSUE THREAD

**Issue by ff6f8d68** [ValkyrienSkies/Valkyrien-Skies-2#801]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

java.lang.NoClassDefFoundError: org/valkyrienskies/core/impl/datastructures/DenseBlockPosSet

### Issue reproduction

1.use Minecraft 1.18.2 forge
2. install Valkyrien-Skies-2 (with dependencies)
3. install vs: tournament

### Logs

**-----latest.log-----**
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14875126/latest.log)
**-----debug.log-----**
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14875128/debug.log)

**Comment by ff6f8d68** [comment]
and I´m on client not server

**Comment by Rubydesic** [comment]
Probably update tournament. But you should report issues with Tournament on their issue tracker, not here.

**Comment by ff6f8d68** [comment]
tournament is newest version (v1.0.0 beta 3 snapshot 0.6)

**Comment by ff6f8d68** [comment]
> Probably update tournament. But you should report issues with Tournament on their issue tracker, not here.

I can´t upload it on their issue tracker
because: This repository has been archived by the owner on Jun 1, 2023. It is now read-only.

**Comment by walksanatora** [comment]
then use a older vs2 version. it is not their problem to fix. if you want you could either fork tournament and fix it for latest vs2 or try and badger the tournament creator to update it.
