### ISSUE TITLE
Crash with Yung's Better End Island

### ISSUE THREAD

**Issue by adozenlionsroaring** [ValkyrienSkies/Valkyrien-Skies-2#803]
### Mod Name

Yung's Better End Island

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I'm using Minecraft 1.20.1 with Embeddium v0.3.12. I removed all mods and added them back one by one until I found the culprits that cause the crash together. The game works again when either Yung's Better End Island v2.0.6 or Valkyrien Skies 2.3.0-beta 5/Eureka 1.3.0-beta 4 are removed. I'm not sure if the problem is on this mod's end or the Yung's End Island end.

### Issue reproduction

Load Yung's Better Island v2.0.6 alongside Valkyrien Skies 2.3.0 beta 5 and Eureka 1.3.0 beta 4.

Sadly no crash report is produced - the game simply crashes with exit code 1.

**Comment by thetheaplant** [comment]
Please attach the latest.log and a modlist.

**Comment by adozenlionsroaring** [comment]
@Liamgrayskull @thetheaplant 

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14896104/latest.log)

Sure thing, here's my latest.log, and here are the mods I have in my folder - I do have Forge Kotlin, Architectury and Yung's API installed:

- Aeroblender
- Aether
- Ambient Sounds
- Appleskin
- Architectury
- Athena
- Balm
- Bclib
- BlockUI
- Blueprint
- Bookshelf
- Canary
- Catalogue
- Cerbon's API
- Cherished Worlds
- Citadel
- Cloth Config
- Clumps
- COFH Core
- Collective
- Sinytra Connector
- Connector Extras
- Creative Core
- Cristel Lib
- CTD Core
- Cupboard
- Curios
- Do API
- Domum Ornamentum
- Dynamic Lights
- Dynview
- Embeddium
- Embeddium++
- Eureka
- Forgified Fabric API (for Sinytra Connector)
- Farsight
- Fastload Reforged
- Ferrite Core
- Forge Endertech
- Formations
- Framework
- Fusion 
- Geckolib
- Handcrafted
- Iceberg
- ImmediatelyFast
- Jade
- JEI
- Kotlin Forge
- Library Ferret
- Majrusz' Library
- Mav Api
- Memory Leak Fix
- Modernfix
- Moonlight
- Moving Elevators
- Multipiston
- Mysterious Mountain Lib
- Oculus
- Patchouli
- Player Animation Lib
- Polymorph
- Prism
- Puzzles Lib
- Redirector
- Resourceful Config
- Resourceful Lib
- SeasonHUD Forge
- Serene Seasons
- Shetiphian Core
- Sophisticated Core
- Sound Physics
- Starlight
- Structure Gel
- Structurize
- Supermartijn642 Config Lib
- Supermartijn642 Core Lib
- Terrablender Lib
- Textrues Embeddium Options
- Valhesia Core
- Valkyrien Skies
- Waystones
- Xaero's Minimap
- Xaero's Waystones Compatibility
- Xaero's World Map
- Yet Another Config Lib
- Yung's API
- Yung's Better Desert Temples
- Yung's Better Dungeons
- Yung's Better End Island (the problematic mod)
- Yung's Better Mineshafts
- Yung's Better Nether Fortresses
- Yung's Better Ocean Monuments
- Yung's Better Strongholds
- Yung's Better Witch Huts
- Yung's Bridges
- Yung's Extras

(Most are library or performance mods, because I was trying to slim down the modlist to pinpoint the conflicting mods.)

This list of mods works when Yung's Better End Island is removed.

**Comment by thetheaplant** [comment]
Try without connector extras.

**Comment by adozenlionsroaring** [comment]
My apologies for getting back to this so late! I can indeed confirm that removing the Connector Extras addon enabled them to load. I will close this issue.
