### ISSUE TITLE
<crash with my modpack>

### ISSUE THREAD

**Issue by Thunderrock424242** [ValkyrienSkies/Valkyrien-Skies-2#807]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

my game crashes

### Issue reproduction

use my modpack

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14935069/latest.log)

**Comment by thetheaplant** [comment]
There is no modpack linked, remove mods until it stops crashing. If you have rubidium, remove that.

**Comment by thetheaplant** [comment]
Also you checked "I have tested this issue and it occurs when no other mods are installed", that is incorrect.

**Comment by Thunderrock424242** [comment]
Cause I could not proceed so I had to check it

**Comment by PriestOfFerns** [comment]
There’s a very good reason you couldn’t proceed
