### ISSUE TITLE
error "too many physics frame queue & "not for public" 

### ISSUE THREAD

**Issue by LadyMaree** [ValkyrienSkies/Valkyrien-Skies-2#808]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

Giving an error "too many physics frame queue. Does not list dependents. Added Clock, Eureka, and Kotlin; new error said "not for public" does this mean single player only/no servers, if so can you post that.

### Issue reproduction

plays fine with all 4 mods in single player. dependents need to be better listed, are we missing something to play on a server or is it only single player at this time, if so also please post that.

**Comment by PriestOfFerns** [comment]
Clockwork doesn’t have a 1.16 version…

**Comment by LadyMaree** [comment]
we are using 1.20.1 sorry, it must have auto filled

**Comment by LadyMaree** [comment]
we are also using curse forge, really loved it in single player. and desperately wanting it to work on server

**Comment by SirBlueAxolotl** [comment]
Do you have Pehkui installed? Because Pehkui makes a lot of lag and "Too many physics frames in the physics frame queue. Is the game stage broken?"

**Comment by jig487** [comment]
Also getting this bug but hosting on a server. I do not have Pehkui installed

**Comment by Frankky001** [comment]
yup same problem it causes a lot of lag on servers. ive tried it with just create, eureka, clockwork and vs and still get that message

**Comment by thetheaplant** [comment]
Closing in favor of #323
