### ISSUE TITLE
Not compatible with Pehkui

### ISSUE THREAD

**Issue by SirBlueAxolotl** [ValkyrienSkies/Valkyrien-Skies-2#810]
### Mod Name

Pehkui

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

The game crashes after spamming "Too many physics frames in the physics frame queue. Is the game stage broken?" in the logs.
To clarify, I'm using Modrinth.

### Issue reproduction

- Right-click twice on a block with the "Mini-Ship Creator"
- Scale yourself to 0.25 or use this command "/scale @s pehkui:base 0.25" 
- Wait for a bit then inside logs, it should say "Too many physics frames in the physics frame queue."

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14967900/latest.log)

**Comment by Hex4dec** [comment]
Pretty sure mini-ships have all sorts of performance issues, not related to Pehkui. Set your NBT data to somewhere distant to where you were and teleport yourself to where the ship was *in-game*.

**Comment by SirBlueAxolotl** [comment]
what ever
