### ISSUE TITLE
End Crystals Are Not Breaking

### ISSUE THREAD

**Issue by CherryPuppet** [ValkyrienSkies/Valkyrien-Skies-2#812]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

After fighting the Ender Dragon for the first time, the end crystals on the surrounding obsidian pillars become indestructible in survival mode. Swords, bows, and even other end crystals blowing up next to them do nothing. It is only when switching to creative mode that the crystals become susceptible to damage.

The end crystals should not be invincible.

### Issue reproduction

Install Valkyrien Skies version 2.3.0-beta.5 and Kotlin for Forge version 4.10.0

(Make sure to be in survival mode) 
After fighting the Ender Dragon for the first time, re-summon it at the exit portal. Once it has finished respawning, try and blow up the end crystals using bows, swords, anything obtainable in survival mode, really. The end crystals will be impervious to your damage.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14977214/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14977217/debug.log)

**Comment by Igneaalis** [comment]
Same issue!

**Comment by SuperSpaceEye** [comment]
ok wtf, it's actually true i've just tested. so strange 🤔

**Comment by UAVwaffle** [comment]
I also have this issue (1.19.2)

**Comment by thetheaplant** [comment]
Closing in favor of #697

**Comment by AVRR75** [comment]
Here's the solution, you welcome!
https://www.curseforge.com/minecraft/texture-packs/valkyrien-skies-end-crystals-destruction-fix

**Comment by allanonmage** [comment]
Neither bug in the tracker is assigned to anyone, is it being worked on? I'm putting together a Vanilla+ modpack with VS, and killing the dragon repeatedly is kind of important.
