### ISSUE TITLE
Crash when respawning on an assembled ship with Distant Horizons 2.0

### ISSUE THREAD

**Issue by IhorPakharenko** [ValkyrienSkies/Valkyrien-Skies-2#821]
### Mod Name

Distant Horizons 2.0.3-a-dev

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Expected: 
I can respawn on an assembled ship without crashing.

### Actual: 
The game crashes after the respawn button is clicked. 

### Issue reproduction

1. In your world, assemble a ship with a bed on it (or place it afterwards). This design is sufficient:
![2024-04-21_09 29 03](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/22911624/85674da3-c2d7-4029-b377-4a26ab88fc09)
2. Set your respawn point to this bed.
3. Stay close to the ship. **If you are far away enough so that the ship is unloaded, this issue _does not_ occur.**
4. Kill yourself.
5. Click respawn. The game should crash.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15051031/latest.log)

**Comment by IhorPakharenko** [comment]
The latest nightly version of Distant Horizons fixed this issue.

**Comment by thetheaplant** [comment]
Unable to recreate, use newest full release of distant horizons.
