### ISSUE TITLE
Random crash when opening Clockwork creative tab

### ISSUE THREAD

**Issue by Cod1ngGamer** [ValkyrienSkies/Valkyrien-Skies-2#828]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Note: The issue tracker for Valkyrien Skies: Clockwork doesn't exist. So I'm making the issue here. Here's where it should be according to the log file: https://github.com/ValkyrienSkies/Clockwork-Issues/issues
I just open Clockwork's creative tab, and the game closes.

This issue occurs even when the only mods installed are the dependencies, in this case Valkyrien Skies, Eureka, Create, and Kotlin for Forge.
The modloader I'm using is Modrinth, and I'm on a Windows 11 laptop.

### Issue reproduction

Open Clockwork's creative tab.

### Logs

[log.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15170161/log.txt)

**Comment by SuperSpaceEye** [comment]
@Cod1ngGamer you could've just asked in discord. Anyways, add architectury api

**Comment by DogeGT** [comment]
> @Cod1ngGamer you could've just asked in discord. Anyways, add architectury api

THX so much I needed this
