### ISSUE TITLE
Ships cannot be teleported into other dimensions

### ISSUE THREAD

**Issue by armet06** [ValkyrienSkies/Valkyrien-Skies-2#829]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When using the vs teleport command with execute, like this:
`/execute in minecraft:nether run vs teleport ship_name ~ ~ ~`
the ship will be moved to the specified coordinates and have rotation, velocity, etc applied but remain in the overworld - the chat message specifying newDimension=null and newScale=null. 

### Issue reproduction

Simply play on 1.20.1 with the Valkyrien Skies beta and try using /execute to teleport a ship across dimensions.

**Comment by Sussy-Chungus** [comment]
To kind of piggyback off of this. I use a mod that lets me fly through the top of the skybox to go to the End (AKA Space). I'd really like to be able to just fly my ship into and out of the "atmosphere" without using a command.

**Comment by PriestOfFerns** [comment]
VS2 ships can already travel through dimensions, but there isn’t really a way for players to force a ship through to another dimensions. Ships used to be able go through nether portals, but I don’t know if that feature still works or not

**Comment by PriestOfFerns** [comment]
@Sussy-Chungus sounds like you should talk to the creator of that mod about adding vs2 compat

**Comment by Sussy-Chungus** [comment]
> @Sussy-Chungus sounds like you should talk to the creator of that mod about adding vs2 compat

I'll do some testing and then reach out to them.

**Comment by xiewuzhiying** [comment]
#908
