### ISSUE TITLE
Compat issue with Create Big Cannons

### ISSUE THREAD

**Issue by FatherSarge** [ValkyrienSkies/Valkyrien-Skies-2#835]
### Mod Name

Create Big Cannons

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Hello! I've encountered a small but extremely annoying bug when using Create Big Cannons. When you build an autocannon that is player controlled when on a VS/Eureka ship, a normal sized player becomes unable to aim the gun because they cannot see, the controls still work. The player's view is of the inside of the recoil spring/or breech, whatever is the block on the cannon mount crossbar. You cannot see outside the cannon block at all.

I say normal sized player because it turns out that using the Origins mod, players that are 1 block tall basically just ride on top of the autocannon and can aim just fine xD

### Issue reproduction

Steps to reproduce:
1.20.1 Forge/NeoForge
Create v0.5.1.f (+Kotlin)
Create Big Cannons v0.5.4-nightly
Valkyrien Skies 2 v2.3.0-beta.5
VS Eureka v1.5.0-beta.3

Step 1: Build a basic airship (wooden plank platform, helm, some balloons and assemble by shift right clicking the helm)
Step 2: Build a basic autocannon consisting of 2 barrels, a recoil spring(this should be the block on the mount crossbar), and a breech, right click with wrench to make it player controllable
Step 3: assemble the cannon and take control of it

If done correctly your vision should be entirely obscured by the gun.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15256490/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15256491/debug.log)

**Comment by 07Productions** [comment]
I also suffer from this issue

**Comment by PriestOfFerns** [comment]
Known issue, it's just not getting fixed rn, because VS2 is going through a rework for the vs-api update

**Comment by thetheaplant** [comment]
Fix in #922

**Comment by GormAuslander** [comment]
Issue persists in the latest version

**Comment by Endalion** [comment]
> Fix in #922

Actually, this bug was fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/847

**Comment by LuciTheBoi** [comment]
still dealing with this issue, any way i can fix myself?

**Comment by thetheaplant** [comment]
wait for the official release of VS 2.5.0.
