### ISSUE TITLE
Wings/Flaps Broken on 1.20.1

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#839]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

If a ship is made which contains wings or flaps the ship will spazz out and fly in random directions

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/d5316499-eedd-416e-93f9-9487a66ce883

This also effects the 1.20.1 fabric versions.

### Issue reproduction

1. assemble a wing or flap with the ship creator (Can do it other ways, just the fastest/easiest)

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15287490/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15287494/debug.log)

**Comment by Endalion** [comment]
Still exists in beta5, however things to note
- Does not update until the world(1) is reloaded **with flaps on the ship**, that means removing the flap does not remove the issue until the world(1) is reloaded
- The bug applies a phantom force proportional to drag but of a very high magnitude
- Direction of phantom force is undetermined
- Drag is no longer in the correct position (as the vessel experiences no aligning torque), possible that lift still exists but unconfirmed

(1) uncertain if it is when world or ship is reloaded

**Comment by Endalion** [comment]
Fixed by https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/945

**Comment by AlexanderwithaA** [comment]
Wow, that was awhile, anyway I can’t confirm this as fixed for a while.
