### ISSUE TITLE
Can shipify already shipified blocks

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#841]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

Back in the 1.16.5 versions of vs2 it would say the following when you tried to shipify a block that'd already been shipified, but in later versions 1.18.2 and up it doesn't do anything.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/7797ca79-a6ae-45f0-b17a-9a77e2393164

### Issue reproduction

1. shipify a block in 1.16.5 to see what it should say
2. shipify a block in 1.18.2 or above and it won't say that

**Comment by StewStrong** [comment]
Its not a bug its a feature ;)

**Comment by AlexanderwithaA** [comment]
You as well as I know it is not
