### ISSUE TITLE
No boats anywhere with Eureka and VS2. VS2 error in console.

### ISSUE THREAD

**Issue by Kiwicast** [ValkyrienSkies/Valkyrien-Skies-2#842]
### Mod Name

Valkrien Skies 

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I have tried adding just Valkyrien skies with Kotlin and get a console error. Then added Eureka, still got the VS error in console and no boats anywhere. Looked around for a while and nothing.

### Issue reproduction

Install Valkyrien Skies and Kotlin into server - console error on start up. Install Eureka on server and install  and error is still there start server and no boats

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15290907/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15290917/debug.log)

**Comment by Rubydesic** [comment]
the error doesn't mean anything. please elaborate on what is actually wrong and create a new issue
