### ISSUE TITLE
<title>Ship froxen once flying over 256 block hight, unable to move. Trying to save the ship build 

### ISSUE THREAD

**Issue by nextjr** [ValkyrienSkies/Valkyrien-Skies-2#844]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

my airship is rather large but has been functioning well, however, when i accidentally set CC to Raise it got stuck at 300 blocks high and i can no longer fly it, realign it or disassemble it. I really hope that we can fix this, as i didn't get a worldedit schematic of my ship before it broke. 

### Issue reproduction

Create a large airship, 30k+ blocks and fly it over 256 blocks high.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15319843/latest.log)

**Comment by luoluo39** [comment]
use `/vs teleport ship_name ~ 100 ~`. this saved my ship when it stuck at 314 blocks high

**Comment by nextjr** [comment]
You're a savior! it worked perfect!!!!!!!!!
