### ISSUE TITLE
the menu crashes

### ISSUE THREAD

**Issue by Blood-ShedSam** [ValkyrienSkies/Valkyrien-Skies-2#849]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

I decided to play with the mod, but for some reason when I open the page with blocks, the game crashes, here is the error code: [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID c494dfc9-29e7-47f3-943e-9f53f027ddd6
Thanks for any answer

### Issue reproduction

I started minecraft, made a world, and entered the inventory in it, but when I decided to open a page with blocks from the mod, game just crash.

### Logs

(the main problem code is at the very bottom)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/15395517/debug.log)

**Comment by Blood-ShedSam** [comment]
I forgot to add a video, here: 

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/170472527/8e21be8a-bc39-413b-9131-111aa829a98f

**Comment by PriestOfFerns** [comment]
Add architectury api to the modpack

**Comment by Blood-ShedSam** [comment]
Thank you very much
