### ISSUE TITLE
The ship is stuck in the air and does not respond to any actions

### ISSUE THREAD

**Issue by hhtut82** [ValkyrienSkies/Valkyrien-Skies-2#855]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

The ship rose to a height of 200+ blocks. And got stuck there. The "Align" command does not help.
### Issue reproduction

![2024-05-27_22 29 27](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/170976644/3c356c0d-014a-40dd-becf-f15514b809ce)
![Uploading 2024-05-27_22.36.10.png…]()

**Comment by Rubydesic** [comment]
try to restart or teleport the ship. we are working on fixing this

**Comment by hhtut82** [comment]
And how can I teleport him to myself?

**Comment by hhtut82** [comment]
> попробуйте перезапустить корабль или телепортировать его. мы работаем над исправлением этого

And how can I teleport him to myself?
