### ISSUE TITLE
Ships invisible with nvidium/acedium

### ISSUE THREAD

**Issue by antdoesthings** [ValkyrienSkies/Valkyrien-Skies-2#857]
### Mod Name

Acedium (nvidium forge port)

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Expectation:
When assembling a ship, it is visible.

What happens:
The ship is invisible.

### Issue reproduction

1. Install VS, Embeddium, Acedium for Forge 1.20.1
2. Create a world
3. Create a ship

It will be invisible.

### Logs

[latest.log](https://github.com/user-attachments/files/15508692/latest.log)

No debug.log was generated.

**Comment by thetheaplant** [comment]
Nvidium is incompatible, will need to be fixed on nvidium's end.
