### ISSUE TITLE
#EMBEDDIUM IS REJECTED BY VS2 IN 1.20.1!!!#

### ISSUE THREAD

**Issue by MeditatorLogic** [ValkyrienSkies/Valkyrien-Skies-2#859]
### Mod Name

embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I wanna play vs2 along with clockwork mod, tournament, cc:vs or kontraption addons in 1.20.1, and the fps is lagged into 0~1. Therefore, i have to add iris mod but the point is that IRIS addons like oculus in 1.20.1 is ALL using embeddium.AND ALSO, GAME GAME CARSHED ALONG WITH EMBEDDIUM AND VS2 ARE LOADED THE SAME TIME!!! SO plz plz plz help me play well in 1.20.1!

### Issue reproduction

I've already asked the athor of embeddium and they said that valkyrien skies2 keeps rejecting embeddium.
Why is this happening?
Or can you make a mod having the similar efforts like iris to keep fps when playing your mods?

### Logs

https://github.com/embeddedt/embeddium/issues?q=valkyrien

**Comment by MeditatorLogic** [comment]
like issue #717 but i've found that in 1.20.1 the latest release is 2.30b5,and is still not compatable.

**Comment by Rulft44** [comment]
what, i cannot understadn a thing you said

**Comment by SuperSpaceEye** [comment]
@MeditatorLogic false, embeddium works with VS2

**Comment by thetheaplant** [comment]
Update embeddium, show logs

**Comment by MeditatorLogic** [comment]
> Update embeddium, show logs



> @MeditatorLogic false, embeddium works with VS2

OK, and i'd test if it really works before i cloe this thread.
Or there maybe any rejections with embeddium and clockwork? kontraptions? or tournament~continued?

**Comment by MeditatorLogic** [comment]
Well, doesn't work a cent...
[crash_report_translated-2024-6-6_11.09.56.zip](https://github.com/user-attachments/files/15600829/crash_report_translated-2024-6-6_11.09.56.zip)

**Comment by thetheaplant** [comment]
Please post a modlist.

**Comment by MeditatorLogic** [comment]
only valkyrien skies2.3.0b5 and embeddium 0.3.19+mc1.20.1
im using forge 47.2.32
and not using official launcher
are these the case?



在 2024-06-07 01:32:49，"Thea" ***@***.***> 写道：

Please post a modlist.

**Comment by thetheaplant** [comment]
Do you have kotlin?

**Comment by MeditatorLogic** [comment]
Sh*t i must forget it!
Now it work properly so the point isnt between vs2 and embeddium!
now im just checking other incompatiations in my modpack!
thx a lot for help
also, excuse for sparing such time on my careless problem!
