### ISSUE TITLE
Log Spam when game tick loop frozen.

### ISSUE THREAD

**Issue by ffernn-dev** [ValkyrienSkies/Valkyrien-Skies-2#861]
### Mod Name

Tick Stasis

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

I'm using the mod Tick Stasis to cause the tick loop and time progression of my server when nobody is online. However, I think VS is not affected by this and tries to queue tonnes of physics updates which never arrive because the game is frozen, logging the following repeatedly

[Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?

### Issue reproduction

Install Valkyrien skies, and Tick Stasis on a fabric server. Start the server.

**Comment by thetheaplant** [comment]
Closing in favor of #323
