### ISSUE TITLE
Textures do not render properly with Sodium

### ISSUE THREAD

**Issue by Droogamcwizardly** [ValkyrienSkies/Valkyrien-Skies-2#865]
### Mod Name

Sodium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

While having Valkyrian Skies and Sodium installed in minecraft 1.20.1, textures of block do not render properly on a ship while a ship while it is assembled. I have tested and it seems to only happen while Sodium is installed, I can't use an older version of Sodium as the only version for Valkyrian Skies is compatible with is Sodium 0.5.8. This does not cause any issue other than visual from what I have found.
![2024-06-04_11 50 12](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/171718658/fe9faf66-f151-4f4e-abb6-c8a72f254999)

### Issue reproduction

Install Valkrian Skies, Eureka!, and Sodium then create and assemble a ship.

### Logs

[latest.log](https://github.com/user-attachments/files/15567847/latest.log)
[debug.log](https://github.com/user-attachments/files/15567850/debug.log)

**Comment by ParkerTCK** [comment]
this can be fixed by turning off Use Block Face Culling in performance

**Comment by Droogamcwizardly** [comment]
Thank you, I did not know if it was something wrong on my end but this defiantly fixed it.

**Comment by Minenash** [comment]
Hey any chance this could be added to the description? I would be surprised if anyone used VS without Sodium

**Comment by thetheaplant** [comment]
@Minenash This information will be added to the wiki when I get around to it.
