### ISSUE TITLE
Valkyrian Skies and Complete Config Incompat

### ISSUE THREAD

**Issue by notdivad0** [ValkyrienSkies/Valkyrien-Skies-2#866]
### Mod Name

Complete Config

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Having completeconfig installed alongside Valkyrien Skies causes game to not start

These are the noticeable mods I had installed
   - Fabric 0.15.11 on Minecraft 1.20.1
    - CompleteConfig 2.5.4
    - Realistic Stamina (uses CompleteConfig)
    - Valkyrien Skies 2.3.0-beta.5 
    
    Traceback
[stacktrace.txt](https://github.com/user-attachments/files/15611845/stacktrace.txt)

Weird part is that VS isn't mentioned anywhere in the traceback, I found that out by carefully removing mods one by one until I found that it was the cause

### Issue reproduction

Install Fabric modloader with:

VS2 and its dependencies, Realistic Stamina (modrinth) and Complete Config

### Logs

[latest.log](https://github.com/user-attachments/files/15612222/latest.log)

**Comment by ash-development** [comment]
this issue was technically solved in pull #798, but it seems that the mod devs haven't actually pushed a release with that commit in it. same issue is #616, there is a [solution ](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/616#issuecomment-1791726336)in there that should work for you :)

**Comment by thetheaplant** [comment]
Fixed in #798.
