### ISSUE TITLE
Player voided upon unstable physics object landing on head

### ISSUE THREAD

**Issue by OhNooooooooo** [ValkyrienSkies/Valkyrien-Skies-2#868]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I was making a clockwork plane on a multiplayer server not owned by me
When I was selecting it I forgot that separate selections produced separate ships
Thus, I had at least 10 ships
I tried to use the /vs teleport command to teleport them into one place
It worked
The pieces with wings on them were unstable and would erratically move around
Once I had them in place, I right clicked on the winged piece with my Gravitron
It bugged out again
I had to teleport it twice more to get it stable before I got voided
I went from around x=-267 y=-42 z=4115 to x=-2000 y=-3500 z=-4000
Rejoining the server dropped me down to 3 hearts

### Issue reproduction

Unsure
Probably create unstable VS2 physics object with wings from Create x VS: Clockwork
Teleport directly above player multiple times until desired effect is produced

my testing did not yield the same results but I'm pretty sure that if you are caught on an unstable physics object it can take you pretty much anywhere
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/109457389/76ab9a49-5403-4c8e-99b6-f1f46299387e)
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/109457389/c3989df8-3143-42a5-85f8-b118f13851fa)

### Logs

[latest.log](https://github.com/user-attachments/files/15748566/latest.log)
[debug.log](https://github.com/user-attachments/files/15748567/debug.log)

**Comment by thetheaplant** [comment]
Wings have been fixed in #839.
