### ISSUE TITLE
Game stuck when I wanted to enter a created world

### ISSUE THREAD

**Issue by TheCYPER** [ValkyrienSkies/Valkyrien-Skies-2#870]
### Mod Name

A modpack related to One Piece

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

I'm Play Java Edition 1.16.5 with a modpack about One Piece and it always stuck when I wanted to enter a created world. Thus, I remove the mods one by one and test for several hours and find that it is related to Valkyrien Skies2 and Eureka! Airships! If I remove them, the problem will not occur. I don't know if this is a problem of compatibility or a problem with VS2. Here is my Log(https://mclo.gs/s7ikT7n), result from calling the stack(https://mclo.gs/IglN9PZ) of my JVM, and my mod list. Did someone met similar problems with VS2 in 1.16.5? 

![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/105260131/f229d989-0e70-46f2-9974-10ce3cbb5758)
![截屏2024-06-12 下午12 52 20](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/105260131/df20cdd1-7779-4d5d-927a-6aa79aaf1059)
By the way, english is not my native language; please excuse typing errors or awkward phrasing.

### Issue reproduction

I will drop my save later. I just got stuck whenever I enter a created world. 

### Logs

JStack Dump
[minecraft-exported-jstack-dump-2024-06-11T11-31-26.log](https://github.com/user-attachments/files/15798518/minecraft-exported-jstack-dump-2024-06-11T11-31-26.log)
Log
[minecraft-exported-logs-2024-06-11T11-31-44.log](https://github.com/user-attachments/files/15798519/minecraft-exported-logs-2024-06-11T11-31-44.log)

**Comment by TheCYPER** [comment]
My save 
[2024-06-12_12-59-52_ONE_PIECE.zip](https://github.com/user-attachments/files/15798552/2024-06-12_12-59-52_ONE_PIECE.zip)

**Comment by thetheaplant** [comment]
1.16.5 no longer has support, use 1.18.2-1.20.1

**Comment by thetheaplant** [comment]
Closing as 1.16.5 is no longer maintained.
