### ISSUE TITLE
crush run

### ISSUE THREAD

**Issue by MaxLegend** [ValkyrienSkies/Valkyrien-Skies-2#872]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

`[23:57:51] [main/ERROR] [mixin/]: valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer: Interface mixin contains a non-public method! Found includeShipsInDistanceCheck(Lnet/minecraft/world/entity/player/Player;DDD)D in valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer
org.spongepowered.asm.mixin.transformer.throwables.InvalidInterfaceMixinException: Interface mixin contains a non-public method! Found includeShipsInDistanceCheck(Lnet/minecraft/world/entity/player/Player;DDD)D in valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer
`

### Issue reproduction

restart

### Logs

[latest.log](https://github.com/user-attachments/files/15859853/latest.log)

**Comment by thetheaplant** [comment]
Please attach a mod list and a crashlog.

**Comment by Rubydesic** [comment]
The part of the error you copy-pasted isn't even an error. The reason your game doesn't work is because you didn't read the instructions to download Kotlin for Forge that are in huge letters on the curseforge page.
