### ISSUE TITLE
VS constantly doins something without my knowledge?

### ISSUE THREAD

**Issue by KrokusAstra** [ValkyrienSkies/Valkyrien-Skies-2#875]
Hi, i'm trying to make modpack just for myself, you know, funny playthrought, a bit of this, a bit of that. I was planning to make VS2 and Create/Clockwork important part of my game, and make big flying fortress. My credo "throw bunch of mods, and then delete what isn't working". But then i started to check up what is lagging, my Spark and log files (while i TP'd across the map, deciding which biome mode to delete), i faced a lag problems. Spark also shows me, VS2 constantly eating up like 8-10% of my tps, as if i'm currently building fortress and have like 5k block moving structure. But i didn't do anything! 
I never create single object with VS2/Clockwork in this savefile, it's just test run, i'm watching what is causing lag, TP and write what i should delete. How is VS2 eating like 10% tps, just being in mod's folder? It shouldn't work until i touch it, no?
Any other mods, even heavy, like minecolonies, bumblezone, alex mods, eating up quite less resources, while i constantly meet something from those mods. Also, when i disabled VS, my RAM usage immediately propped 5-7%
Is it really active all time?
[latest.log](https://github.com/user-attachments/files/15893622/latest.log)

**Comment by Rubydesic** [comment]
Valkyrien Skies consumes your TPS because every loaded terrain needs to be converted into physics meshes and passed to our physics engine. We are working on this but even though we will improve the performance, the mod will never not "work until i touch it"

**Comment by KrokusAstra** [comment]
Oh, i understand now. Sorry for being ignorant, my bad. You did gread job and your mod is really cool! You are on the frontline of modding! Keep it up! 👍
