### ISSUE TITLE
Copycats+ boards have different collision than carpets, even though they have the same dimensions.

### ISSUE THREAD

**Issue by Tornc** [ValkyrienSkies/Valkyrien-Skies-2#877]
### Mod Name

Copycats+

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/110984950/df562f6f-7e8f-4cf3-bf8c-bac58b81a70a

**Entire modlist:**
![explorer_eA3DDry1x5](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/110984950/793a22ee-cd9d-495b-983c-eccba049a3ab)

Every mod config setting is default.

**Relevant mods:**
- Copycats+
- Create
- Clockwork
- Valkyrien Skies

### Issue reproduction

Place a phys bearing facing upwards, make the phys entity/ship attached to it rotate. On the same level, place carpets, they will get ignored by the phys entity/ship when it goes over the carpets. If boards are placed instead, they will collide and the phys entity will stop.

**Comment by thetheaplant** [comment]
Is the collision box of the panels a full block or just their visible shape?
If they are not a full block, then this was probably intentional.

**Comment by Tornc** [comment]
Sorry, I'm not entirely sure what you mean by collision box. Could you please elaborate? Though, I'm pretty sure that this behaviour was not intentional on the Copycats+ mod developers' end. (If you meant that)

Here's a conversation I had with one of the Copycats+ devs:
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/110984950/8d0c204a-1de2-40fb-8d39-54acec3cde76)
I then asked if I should report it to VS github instead.
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/110984950/4e6ac805-9f59-4d0f-8366-646e0a796169)

**Comment by Rubydesic** [comment]
VS uses BlockState#getShape to determine the shape of a blockstate, which is I think pretty standard? Not sure what a multistate is.

**Comment by thetheaplant** [comment]
Copycats+ boards have a hitbox consistent with their model, no issue.
