### ISSUE TITLE
Game crashes when some players leave the server

### ISSUE THREAD

**Issue by Mapter228** [ValkyrienSkies/Valkyrien-Skies-2#879]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [ ] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

The server goes down periodically, I've noticed that most often the error occurs when some players leave the server, especially OPs

### Issue reproduction

Logging out of the server causes a crash

### Logs

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/25/24, 7:30 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at org.valkyrienskies.core.impl.shadow.Ac.a(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.5.jar%2378!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.zI.b(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.5.jar%2378!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.postTick(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.5.jar%2378!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ak.b(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.5.jar%2378!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.At.postTickGame(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.5.jar%2378!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.handler$bca001$postTick(MinecraftServer.java:4118) ~[server-1.18.2-20220404.173914-srg.jar%2384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:880) ~[server-1.18.2-20220404.173914-srg.jar%2384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2384!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 6.1.0-12-amd64
	Java Version: 17.0.11, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1520726576 bytes (1450 MiB) / 2988220416 bytes (2849 MiB) up to 4938399744 bytes (4709 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 97093.00
	Virtual memory used (MB): 115124.61
	Swap memory total (MB): 32734.00
	Swap memory used (MB): 6959.91
	JVM Flags: 5 total; -Xms512M -XX:MaxRAMPercentage=95.0 -XX:ConcGCThreads=3 -XX:ParallelGCThreads=3 -XX:+UseSerialGC
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:radium (incompatible), mod:rhino (incompatible), mod:fastload (incompatible), mod:jei (incompatible), mod:applecrates (incompatible), mod:controlling (incompatible), mod:configured (incompatible), mod:weather2 (incompatible), mod:starlight (incompatible), mod:cloth_config (incompatible), mod:forge, mod:grieflogger (incompatible), mod:tfc, mod:waterflasks, mod:weathertfc, mod:voicechat (incompatible), mod:swingthroughgrass (incompatible), mod:creativecore (incompatible), mod:pcf, mod:astikorcarts (incompatible), mod:asspackets, mod:kotlinforforge, mod:applecrates_tfc, mod:tfcambiental, mod:curios (incompatible), mod:flywheel (incompatible), mod:create, mod:createsifter (incompatible), mod:patchouli (incompatible), mod:gravestone (incompatible), mod:polymorph (incompatible), mod:cc (incompatible), mod:coroutil (incompatible), mod:architectury (incompatible), mod:kubejs (incompatible), mod:antiqueatlas (incompatible), mod:kubejs_create (incompatible), mod:ferritecore (incompatible), mod:firmalife, mod:valkyrienskies (incompatible), mod:vs_eureka (incompatible), mod:trackwork, mod:create_interactive (incompatible), mod:locksmith (incompatible), mod:pollen, mod:kubevs (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
	Mod List: 
		radium-0.7.10.jar                                 |Radium                        |radium                        |0.7.10              |DONE      |Manifest: NOSIGNATURE
		rhino-forge-1802.2.1-build.255.jar                |Rhino                         |rhino                         |1802.2.1-build.255  |DONE      |Manifest: NOSIGNATURE
		Fastload-Reforged-mc1.18.2-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1005.jar                  |Just Enough Items             |jei                           |10.2.1.1005         |DONE      |Manifest: NOSIGNATURE
		locksmith-forge-1.1.1-1.18.2.jar                  |Locksmith                     |locksmith                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Apple Crates-forge-1.18.2-1.7.3.jar               |Apple Crates                  |applecrates                   |1.7.3               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+23.jar               |Controlling                   |controlling                   |9.0+23              |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.18.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		weather2-1.18.2-2.7.5.jar                         |Weather2                      |weather2                      |1.18.2-2.7.5        |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-6.3.81.jar                     |Cloth Config v4 API           |cloth_config                  |6.3.81              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.21-universal.jar                |Forge                         |forge                         |40.2.21             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		grieflogger-1.18.2-1.0.jar                        |GriefLogger                   |grieflogger                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		TerraFirmaCraft-Forge-1.18.2-2.2.33.jar           |TerraFirmaCraft               |tfc                           |2.2.33              |DONE      |Manifest: NOSIGNATURE
		waterflasks-2.0.7.jar                             |TFC Water Flasks              |waterflasks                   |2.0.7               |DONE      |Manifest: NOSIGNATURE
		WeatherTFC-1.18.2-1.5.4.jar                       |Weather TFC                   |weathertfc                    |1.5.4               |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.5.16.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.5.16       |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.2-1.9.1.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.2-1.9.1        |DONE      |Manifest: NOSIGNATURE
		Forge-1.18.2-Pollen-1.6.0.jar                     |Pollen                        |pollen                        |1.6.0               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.17_mc1.18.2.jar           |CreativeCore                  |creativecore                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		proxy-compatible-forge-1.18.2-1.1.4.jar           |Proxy Compatible Forge        |pcf                           |1.18.2-1.1.4        |DONE      |Manifest: NOSIGNATURE
		tfc-astikorcarts-1.18.2-1.1.6.jar                 |AstikorCarts                  |astikorcarts                  |1.1.6               |DONE      |Manifest: NOSIGNATURE
		asspackets-1.1.0.jar                              |Ass♂ Packets                  |asspackets                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |DONE      |Manifest: NOSIGNATURE
		Firma Crates-forge-1.18.2-0.7.0.jar               |Apple Crates for Premium Wood |applecrates_tfc               |0.7.0               |DONE      |Manifest: NOSIGNATURE
		tfcambiental-2.2.0-1.18.2.jar                     |TFC Ambiental                 |tfcambiental                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.2.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.2      |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.10-105.jar              |Flywheel                      |flywheel                      |0.6.10-105          |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		createsifter-1.18.2-1.5.5.b-285.jar               |Create Sifter                 |createsifter                  |1.18.2-1.5.5.b-285  |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.50.jar                   |Polymorph                     |polymorph                     |1.18.2-0.50         |DONE      |Manifest: NOSIGNATURE
		ClaimChunk-1.18-1.0.17 (1).jar                    |Claim Chunk                   |cc                            |1.0.17              |DONE      |Manifest: NOSIGNATURE
		coroutil-forge-1.18.2-1.3.6.jar                   |CoroUtil                      |coroutil                      |1.18.2-1.3.6        |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		kubejs-forge-1802.5.5-build.569.jar               |KubeJS                        |kubejs                        |1802.5.5-build.569  |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-7.1.1-forge-mc1.18.2.jar             |Antique Atlas                 |antiqueatlas                  |7.1.1-forge-mc1.18.2|DONE      |Manifest: NOSIGNATURE
		kubejs-create-forge-1802.2.4-build.16.jar         |KubeJS Create                 |kubejs_create                 |1802.2.4-build.16   |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		firmalife-1.2.18.jar                              |Firmalife                     |firmalife                     |1.2.18              |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-118-2.1.1-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.1.1-beta.5        |DONE      |Manifest: NOSIGNATURE
		eureka-1.5.1-beta.1.jar                           |VS Eureka Mod                 |vs_eureka                     |1.5.1-beta.1        |DONE      |Manifest: NOSIGNATURE
		kubevs-1.0.0.jar                                  |KubeVS                        |kubevs                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		trackwork-1.18.2-0.0.1h1-alpha.jar                |Trackwork Mod                 |trackwork                     |1.18.2-0.0.1h1-alpha|DONE      |Manifest: NOSIGNATURE
		create_interactive-forge-1.0.0-beta.1+bbb6a25a59.j|Create: Interactive           |create_interactive            |1.0.0-beta.1+bbb6a25|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 92996264-7d77-477c-8274-76429397a4c7
	FML: 40.2
	Forge: net.minecraftforge:40.2.21

**Comment by thetheaplant** [comment]
Please verify that this still occurs with just Valkyrien Skies and and vs addons present, then post that log if it still crashes.

**Comment by thetheaplant** [comment]
Unable to recreate this issue, closing until more information is provided, or if the issue can be recreated with only VS and only the mods that cause the issue.
