### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by BluAxoVR** [ValkyrienSkies/Valkyrien-Skies-2#884]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

I might be stupid but how do I install VS2?

### Issue reproduction

???

### Logs

???

**Comment by thetheaplant** [comment]
What do you want us to explain, watch any videos on installing mods

**Comment by BluAxoVR** [comment]
videos dont fucking help
