### ISSUE TITLE
Game Crash When Using Scissors on Root Shell with Both Valkyrien Skies and TARDIS Refined Installed

### ISSUE THREAD

**Issue by Dithree** [ValkyrienSkies/Valkyrien-Skies-2#885]
### Mod Name

TARDIS Refined

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

As mentioned in the title, using scissors to right-click on the Root Shell after creating the TARDIS with both Valkyrien Skies and TARDIS Refined installed causes the game to crash.
However, I'm not sure if an issue involving multiple mods should be posted here. I apologize if this is the wrong place to report it.

### Issue reproduction

1.Install Valkyrien Skies and TARDIS Refined
2.Place a Root Shell
3.Use scissors to right-click on the Root Shell
4.Game crashes

### Logs

[latest.log](https://github.com/user-attachments/files/16038620/latest.log)
[crash-2024-06-29_11.31.28-server.txt](https://github.com/user-attachments/files/16038621/crash-2024-06-29_11.31.28-server.txt)

**Comment by thetheaplant** [comment]
Tardis refined is incompatible, as is immersive portals.

**Comment by kotx** [comment]
> Tardis refined is incompatible, as is immersive portals.

What's the technical reason? Tardis Refined doesn't do anything similarly to Immersive Portals (which I would understand due to potential rendering and entity changes).

**Comment by thetheaplant** [comment]
I assume it's related to rendering or the tardis dimension, I'm not entirely sure what it breaks, but it messes with some of vs2's processes. We've seen this same issue several times, it just causes a server tick error, see #504, and #641.
