### ISSUE TITLE
When i added this thing in virustotal:

### ISSUE THREAD

**Issue by TheRaventy** [ValkyrienSkies/Valkyrien-Skies-2#886]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Found virus....

### Issue reproduction

![obrazek](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/172971459/59671728-8896-485e-82fd-2d2e4c1e2bad)

**Comment by TheRaventy** [comment]
+ when i start game, it crashes

**Comment by thetheaplant** [comment]
That is a false positive, probably due to the direct ram access.

**Comment by PriestOfFerns** [comment]
Sangfor Engine Zero is a very poorly made ml-powered chinese virus detector, known for flagging AAA games as malware
