### ISSUE TITLE
Respawning with Distant Horizons crashes the game.

### ISSUE THREAD

**Issue by snoandpetals** [ValkyrienSkies/Valkyrien-Skies-2#892]
### Mod Name

Distant Horizons

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

When respawning within range of a ship while using Distant Horizons, the game freezes.

### Issue reproduction

1. Open world with Distant Horizons and Valkyrien Skies
2. Make a ship
3. /kill
4. Attempt to respawn
5. Freeze

### Logs

https://mclo.gs/WHtU5o3

**Comment by HMKing2006** [comment]
I've had this same issue as the host of a LAN world, and another player connected to the LAN was able to respawn on the same ship as me without crashing the game. We both used Distant Horizons.

**Comment by thetheaplant** [comment]
Unable to recreate.
