### ISSUE TITLE
*clockwork* Wanderlite is not spawning in 1.18.2

### ISSUE THREAD

**Issue by LuigiPlayer1** [ValkyrienSkies/Valkyrien-Skies-2#894]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

whenever I try to play 1.18.2 on forge with the clockwork mod no wanderlite spawns. I have tried different mod versions, only using clockworks, different versions of kotlin, arch API, etc. I used xray mods and spectator and nothing spawns so I can definitely confirm it.
This issue only happens in versions after 1.10, aka versions after arch API changes

### Issue reproduction

Open any version of the clockwork mod after version 1.10 in the forge mod loader and in minecraft 1.18.2 and you will not be able to find any wanderlite naturally spawn

**Comment by SLimeyMC** [comment]
This is not problem with valkyrien skies, if you want to report problem go to the https://github.com/mrsterner/Clockwork-Issues/issues/, however it's been abandoned as of late since the main dev work on new update.

**Comment by thetheaplant** [comment]
Clockwork, not vs issue.
