### ISSUE TITLE
Bedrock Compatibility

### ISSUE THREAD

**Issue by Haegon967** [ValkyrienSkies/Valkyrien-Skies-2#898]
### Mod Name

Valkrien Skies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I would just like that a mcpedl or mcaddon be made so i can play with my freinds on bedrock

### Issue reproduction

no

### Logs

no

**Comment by xiewuzhiying** [comment]
It could never be made, they're not even the same thing. Not to mention what Mojang did with the Bedrock edition a while back.

**Comment by Syclusion** [comment]
Someone close this lol, waste of an issue.

**Comment by ambientNexus** [comment]
Why are children allowed to make accounts on github?

**Comment by Haegon967** [comment]
Fuck off i learned c++ and fixed it myself
________________________________

**Comment by ambientNexus** [comment]
> Fuck off i learned c++ and fixed it myself

There's nothing to fix, you're asking for a mod to be ported to a different game entirely, ones that's also written in a different coding language.

**Comment by ambientNexus** [comment]
On another note, genuinely curious how much of a mess your supposed version of this is. Have you uploaded it anywhere, or have any proof it exists?

**Comment by thetheaplant** [comment]
This can be fixed, but you have to run it as java on android. There is no bedrock support, check the wiki for details.
