### ISSUE TITLE
ValkyrienSkies server crash [physics thread warning, server overloaded]

### ISSUE THREAD

**Issue by Minestock** [ValkyrienSkies/Valkyrien-Skies-2#900]
Prominence 2 RPG

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

I am running the latest version of ValkyrienSkies and Eureka on my server (fabric 1.20.1) with the Prominence 2 rpg modpack on Bisecthosting. I tested it client side and it worked however I am having issues with it on my server. On my server, both prominence 2 and valyrienskies work when run separately, but not together. It crashes out at a memory of 5gb out of 12gb, and I keep getting a physics thread warning. Here is my error message. Has anyone else had this issue?

Too many physics frames in the physics frame queue. Is the game stage broken?
[21:42:11] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 12539ms or 250 ticks behind
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
/entrypoint.sh: line 38:    57 Aborted                 (core dumped) java -Xmx${SERVER_MEMORY}M -XX:+UseContainerSupport -Xms128M -XX:MaxRAMPercentage=85 -Dterminal.jline=false -Dterminal.ansi=true ${CUSTOM_ARGS} -jar ${SERVER_JARFILE} ${CUSTOM_ARGS_END}
[Panel]: Server marked as offline...
[Panel]: ---------- Detected server process in a crashed state! ----------
[Panel]: Exit code: 134
[Panel]: Out of memory: false
[Panel]: Updating process configuration files...
[Panel]: Ensuring file permissions are set correctly, this could take a few seconds...

### Issue reproduction

Bisecthosting pre-install of prominence 2 and install the following to the mods folder
![TheseWork](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/175274601/60b80633-3988-4074-ad24-313224b4dc88)

Uninstall Carry On
Uninstall the 3 Iris Mods
Uninstall regions unexplored
Uninstall VRcombat
Uninstall vivecraft

**Comment by souldbminersmwc** [comment]
Same error

**Comment by XCwosjw** [comment]
me too

**Comment by Minestock** [comment]
Update: Havnt fixed isue. But after combing through the discord i found that you can get rid of the physics warning by going to configs, then go to valkyrien skies, then to vs_core_server.json and change synchronizephysics to true. My server now goes online momentarily but still crashes with the attached crash report. 
Another solution ive seen is to unallocate memory on your server as VS runs on unallocated memory. Im not quite sure how to do this on bisecthosting. 
[crashlog2.txt](https://github.com/user-attachments/files/16202128/crashlog2.txt)

**Comment by Dedekuhl** [comment]
I've been having the same exact issue. It works fine on a VPS or a singleplayer world, but not on a server. I'm not sure if it may have any correlation, but I've noticed the crash only happens when there's dimension mods installed, in my specific case Voidz and Minecells. (I've tried removing them and it worked fine. I also tested them separately)

**Comment by Dedekuhl** [comment]
@Minestock did you figure something out?

**Comment by Minestock** [comment]
@Dedekuhl No I havnt. After chatting on the discord I believe it might have something to do with this 

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/826

In this case you may have to get the server host staff to make these configurations for you.

**Comment by XCwosjw** [comment]
Not necessarily. For example, I used the entire server to run the server directly, but the same situation occurred

**Comment by Minestock** [comment]
> XCwosjw

what type of server are you running?
