### ISSUE TITLE
Batching engine crash with Create

### ISSUE THREAD

**Issue by scmcgowen** [ValkyrienSkies/Valkyrien-Skies-2#901]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Crash when a vs ship has copycat blocks on it when being assembled
[crash-2024-07-12_22.21.20-client.txt](https://github.com/user-attachments/files/16201021/crash-2024-07-12_22.21.20-client.txt)

### Issue reproduction

Place multiple copycat blocks on the ship pre assembly, then assemble with Eureka

**Comment by scmcgowen** [comment]
This was reported to me by a beta tester for the pack we are testing

**Comment by thetheaplant** [comment]
Change flywheel batching engine mode.
