### ISSUE TITLE
where can i get nightlies? this project is impossible to build

### ISSUE THREAD

**Issue by TheKidThatCodes** [ValkyrienSkies/Valkyrien-Skies-2#903]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

nightlies are a good way to bug test new features

### Issue reproduction

n/a

**Comment by thetheaplant** [comment]
You can find nightlies in the packages tab, this is not a bug report or an issue.
