### ISSUE TITLE
game crashes when open a clockworks creative page 

### ISSUE THREAD

**Issue by AndrewSol12112013** [ValkyrienSkies/Valkyrien-Skies-2#916]
### Mod Name

idk

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

I open creative page and my game crashes, I don't use optifine. Please help me fix that issue :(

### Issue reproduction

idk

### Logs

[latest.log](https://github.com/user-attachments/files/16337177/latest.log)
[debug.log](https://github.com/user-attachments/files/16337179/debug.log)

**Comment by thetheaplant** [comment]
Not a Valkyrien Skies issue, please close this issue.

**Comment by xiewuzhiying** [comment]
install Architectury API

**Comment by AndrewSol12112013** [comment]
thx
