### ISSUE TITLE
VS2 doesnt load 

### ISSUE THREAD

**Issue by DinoThatGames** [ValkyrienSkies/Valkyrien-Skies-2#923]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

When I load minecraft unlimited it just crashes and says that VS2 is the problem so what do I do? Please help

### Issue reproduction

so just load minecraft and it crashes and says VS2 is the thing that is causing the problem

**Comment by thetheaplant** [comment]
Please send a crashlog, modlist, latest.log, anything with actually useful information

**Comment by DinoThatGames** [comment]
> Please send a crashlog, modlist, latest.log, anything with actually useful information

<img width="735" alt="Screen Shot 2024-07-28 at 11 12 32 PM" src="https://github.com/user-attachments/assets/6e18153a-0a8d-4e19-9bc0-7be6908fa63e">

**Comment by FullMetalMaster** [comment]
same issue but i just get this 
![image](https://github.com/user-attachments/assets/b0c25970-d03a-45fd-854b-e991544af15f)
[latest.log](https://github.com/user-attachments/files/16462942/latest.log)

**Comment by thetheaplant** [comment]
There is no crashlog attached, check in your .minecraft/crashlogs folder.
