### ISSUE TITLE
VS2/clockwork crash with drippy loading screen and even when removed can not load or create worlds 

### ISSUE THREAD

**Issue by Shadower006** [ValkyrienSkies/Valkyrien-Skies-2#926]
### Mod Name

Drippy Loading Screen (drippyloadingscreen), Version: 3.0.1

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I expect the game to load up without issue but i crash when loading in , and when i remove drippy loading screen i load in succesfully but then i cant open my world i crash every time i try to open my world or make a new world.

### Issue reproduction

Have craft to exile 2 mod pack installed +

VS2 120-2.3.0
Eureka 1201-1.5.1
clockwork 1.20.1-0.1.13
create interactive 1.201 forge-1.0.2

Spartan weaponry 3.1.1
Spartan Shields 3.1.1
spartan toolkit
spartan skies
spartan undergarden 

immersive armors 1.6.1
butcher mod 2.5.1
Epic fight 20.6.3
more discs 1.20.1-33.1
Sound physics 1.20.1-1.4.5
born in chaos 1.3.1
end of herobrine 1.0.8.2
from the fog 1.9.2
the graveyard 3.1
dynamic village 0.4
realmrpg fallen adventurers 1.0.3
spelunkers charm 3.6.0 

Then run the game it should crash and give you a crash log similar to what i posted in the logs file

### Logs

[crash-2024-07-30_02.05.24-fml.txt](https://github.com/user-attachments/files/16420441/crash-2024-07-30_02.05.24-fml.txt)

**Comment by Shadower006** [comment]
i noticed i was using an older version of clockwork i switched it out with the newest 1 on discord but im still crashing 
[crash-2024-07-30_10.57.19-client.txt](https://github.com/user-attachments/files/16425343/crash-2024-07-30_10.57.19-client.txt)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS, addons, and one other mod, and then create a new issue
