### ISSUE TITLE
ComputerCraft's speakers does not work on ships

### ISSUE THREAD

**Issue by Nicolas1423YTBR** [ValkyrienSkies/Valkyrien-Skies-2#930]
### Mod Name

CC: VS, ComputerCraft

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Basically, when i place a computer and a speaker on a ship, and try to play a sound, it plays, but when i move the ship, the sound location from the speaker stays where it was placed on first, it does NOT move along with the ship.

### Issue reproduction

Place a speaker, a computer, and a Eureka's ship helm (thats what im using), then glue it and assemble the ship. Try to play a sound. It will play on the location of the speaker before the ship was assembled, and it will not play on the actual speaker on the ship. It will be like an invisible speaker.

**Comment by Hex4dec** [comment]
Also adding that at least in previous versions (haven't played VS in a while), PCM audio does not work at all.

**Comment by PriestOfFerns** [comment]
fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/1c62cccd2dd52dcd1daf998a3f8bc7ae5d5458b8

**Comment by Nicolas1423YTBR** [comment]
thank you PriestOfFerns, i will test it and leave a reply here if it does not work

**Comment by Nicolas1423YTBR** [comment]
didnt work, keeps crashing

**Comment by xiewuzhiying** [comment]
The latest vs2 build is currently incompatible with addons
You can choose to install vs addition which provides the same fix

**Comment by Nicolas1423YTBR** [comment]
is the name literally vs:additions or not? if not, send me the link please

**Comment by Nicolas1423YTBR** [comment]
vs:addition does not work, it still has the same issue

**Comment by thetheaplant** [comment]
Fix has been merged.
