### ISSUE TITLE
Eating Animation / GroovyModLoader crash

### ISSUE THREAD

**Issue by FullMetalMaster** [ValkyrienSkies/Valkyrien-Skies-2#932]
### Mod Name

Eating Animation / GroovyModLoader

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

exit code 1

### Issue reproduction

https://www.curseforge.com/minecraft/mc-mods/eating-animation-forge
https://www.curseforge.com/minecraft/mc-mods/gml
and valskys

**Comment by thetheaplant** [comment]
Please check for past issues before posting duplicates.
