### ISSUE TITLE
memory overflow 

### ISSUE THREAD

**Issue by blackvccat** [ValkyrienSkies/Valkyrien-Skies-2#933]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

In the process of using Valkyrie, Java sends a request for 2t memory to the server, causing the server memory to [overflow.
![d3423d721a7f13fe93ff4af72355378](https://github.com/user-attachments/assets/b3775841-0f93-4eff-9eed-480a6fb4c992)

### Issue reproduction

When I am driving a ship, running the single-player archive through cc is normal, but it will cause the server's memory to overflow. The server operates on the kvm architecture, and the memory is allocated to 64g, but when running the ship, the jvm applies to the host. 2tb of memory requirements, which is incredible, and there are also related questions about Too many physics frames in the physics frame queue. Is the game stage broken?
![d3423d721a7f13fe93ff4af72355378](https://github.com/user-attachments/assets/fb76ea6f-2b89-491f-87a7-42d9d5f30db7)
![203616497284791a2a8e2ef14de38d9](https://github.com/user-attachments/assets/49778d06-a61d-470d-b993-69e02f76fe74)

### Logs

[latest.log](https://github.com/user-attachments/files/16501096/latest.log)

**Comment by blackvccat** [comment]
https://spark.lucko.me/wNEKW1MQ4O
https://spark.lucko.me/wxGDDiMdKL

**Comment by PriestOfFerns** [comment]
does this happen on 1.18 or 1.19 VS2?

**Comment by blackvccat** [comment]
> 这发生在 1.18 还是 1.19 VS2 上？

1.20.1

**Comment by PriestOfFerns** [comment]
You said that you’re allocating 64 GBs of RAM. How much RAM does the server have in total? VS2 uses off-heap RAM, so if you allocate all of your RAM to minecraft, VS2 runs into issues. Never seen anything like this though

**Comment by blackvccat** [comment]
> 您说您正在分配 64 GB 的 RAM。服务器总共有多少 RAM？VS2 使用堆外 RAM，因此如果您将所有 RAM 分配给 Minecraft，VS2 会遇到问题。从来没有见过这样的事情

The server has a total of 128g of memory, but I virtualized the server through kvm. The server that opens Minecraft only occupies 64g of which 10g are allocated to the system. The remaining 48g of memory is directly occupied by the server.

**Comment by thetheaplant** [comment]
Closing in favor of #525
