### ISSUE TITLE
Minecraft won't open for me

### ISSUE THREAD

**Issue by DracoHero** [ValkyrienSkies/Valkyrien-Skies-2#935]
I need help, I have been having this problem when I have Valkyrien Skies installed and more than 300 additional mods, including the dependencies of this, I leave the entire list of mods and the last log in a image

![image](https://github.com/user-attachments/assets/b72ba847-dbf0-459c-9edb-b91d5691f3fa)
[mods list.json](https://github.com/user-attachments/files/16532006/mods.list.json)

**Comment by killer2gudpl** [comment]
Remove Eating Animation and GML (Eating animation is the mod and GML is the library it uses). Its the incompatibility that I found by having the same problem and removing/adding mods.

**Comment by thetheaplant** [comment]
Seems to be solved, read the wiki for incompatible mods.
