### ISSUE TITLE
Mixin conflict issues related to reach_entity_attributes

### ISSUE THREAD

**Issue by 4li77l3n00b** [ValkyrienSkies/Valkyrien-Skies-2#938]
### Mod Name

reach_entity_attributes

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Modpack won't launch after adding VS. It seems that it's related to Connector Extras since it provides forgified REA API, but I was able to get Minecraft to launch with VS and all fabric mods(including those that demand connector extras). I can't really locate the conflicting mod since it's a large modpack.

### Issue reproduction

Remove VS and all addons: Launches
Remove all addons and keep VS core: Fails (reach_entity_attributes Mixin error)
Keep VS and addons: Fails (reach_entity_attributes Mixin error)
Keep VS and Fabric mods only: Launches

### Logs

[latest.log](https://github.com/user-attachments/files/16551834/latest.log)

**Comment by thetheaplant** [comment]
Refer to https://github.com/Sinytra/ConnectorExtras/issues/33

**Comment by 4li77l3n00b** [comment]
ok it's now working
