### ISSUE TITLE
Ship textures break on one side

### ISSUE THREAD

**Issue by dreadstrike-inferniclaw** [ValkyrienSkies/Valkyrien-Skies-2#939]
### Mod Name

?

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

I make a ship and the textures break on one side. My photos are taken with shaders but this issue occurs even without them installed. The ship is an upgraded End Ship from the BetterEnd mod.
![Screenshot 2024-08-08 163518](https://github.com/user-attachments/assets/004e52e2-ced2-45fb-a071-898dda4e27b3)
![Screenshot 2024-08-08 163530](https://github.com/user-attachments/assets/b7faec6d-2af7-4c2f-9aff-d2b530972a74)

### Issue reproduction

Make a ship.

**Comment by dreadstrike-inferniclaw** [comment]
This only happens on large ships. I made a small ship and its perfectly fine.

**Comment by thetheaplant** [comment]
Turn off block face culling in performance settings.

**Comment by dreadstrike-inferniclaw** [comment]
This worked!

**Comment by dreadstrike-inferniclaw** [comment]
VS Community, if ship textures are breaking one one side go to performance settings and turn off block face culling!
