### ISSUE TITLE
VS clockwork tab crash

### ISSUE THREAD

**Issue by yusar123456** [ValkyrienSkies/Valkyrien-Skies-2#942]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When I try to load up the VS  clockwork tab in the inventory my game crashes
[crash-2024-08-19_10.42.17-client.txt]
(https://github.com/user-attachments/files/16657304/crash-2024-08-19_10.42.17-client.txt)

(https://github.com/user-attachments/assets/7967f335-3c45-48ee-b655-94fdda7cdcb8)

### Issue reproduction

 ?

### Logs

?

**Comment by PriestOfFerns** [comment]
This isn't the place for clockwork issues, nor is it the place to diagnose your modpacks.

Either way, install architectury api

**Comment by yusar123456** [comment]
so where do I report this then??
