### ISSUE TITLE
<title>Versioning issues with Kotlin for Forge

### ISSUE THREAD

**Issue by doskel** [ValkyrienSkies/Valkyrien-Skies-2#944]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I'm using neoforge server on 1.20.1. With only VS2 (latest modrinth version) and KfF (latest 1.20.1 modrinth version), VS2 fails to launch with some odd errors. I also tried using some older versions of both KfF and VS and had no luck. It works fine on my desktop system with a regular client install, so I assume there's some strange discrepancy causing this.

### Issue reproduction

Install NeoForge server on 1.20.1, install only latest 1.20.1 versions of VS2 and KfF from Modrinth. On launch, game hard crashes before window initialization.

### Logs

[latest.log](https://github.com/user-attachments/files/16682651/latest.log)
[debug.log](https://github.com/user-attachments/files/16682652/debug.log)

**Comment by thetheaplant** [comment]
This is not a kotlin issue, can you send a crashlog and which operating system you are using.

**Comment by thetheaplant** [comment]
The device in the logs does not support GlibC's functions, consider using another device.
