### ISSUE TITLE
(Eureka) Anchor Doesn't work properly

### ISSUE THREAD

**Issue by RoboSteveLegacy** [ValkyrienSkies/Valkyrien-Skies-2#949]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When the ancho block is activated with a redstone signal, it does immobilize the ship. Problem is, it's permanent; nothing will get it to move again. Turning off the redstone signal, breaking the anchor, it does nothing. 

### Issue reproduction

Try using the anchor on a Eureka ship.

**Comment by thetheaplant** [comment]
Wrong repo, you're looking https://github.com/ValkyrienSkies/Eureka/issues. Please recreate this issue there and close this one.
