### ISSUE TITLE
CEM blocks are invisible on eureka ships

### ISSUE THREAD

**Issue by Plasman888** [ValkyrienSkies/Valkyrien-Skies-2#957]
### Mod Name

Entity Model Features

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

CEM blocks are invisible on eureka ships

### Issue reproduction

**To Reproduce**
Download EMF and ETF
Download Valkyrein skies and eureka
Download a resource pack with CEM textures for blocks (In my case the reimagined texture pack)
Place the CEM black on an assembled eureka ship (In my case a chest)

**Expected behavior**
The chest should be visible

**Screenshots**
https://outplayed.tv/minecraft-java/66LNDO

**Comment by thetheaplant** [comment]
Fixed in #958
