### ISSUE TITLE
Mod toml file missing issue

### ISSUE THREAD

**Issue by Tmhgutsun** [ValkyrienSkies/Valkyrien-Skies-2#961]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The log shows that this mod is missing toml files of fmlcore,javafmllanguage,lowcodelanguage and mclanguage
Is this issue related to other language such as Chinese or Japanese?

### Issue reproduction

Forge version:1.20.1-Forge_47.3.7
minecraft version:1.20.1 
no ther mods are installed

### Logs

[latest.log](https://github.com/user-attachments/files/16964708/latest.log)
[debug.log](https://github.com/user-attachments/files/16964710/debug.log)

**Comment by thetheaplant** [comment]
Please attach the crashlog or the mod folder.

**Comment by Tmhgutsun** [comment]
[Crash_report-2024-9-12_20.23.28.zip](https://github.com/user-attachments/files/16979133/Crash_report-2024-9-12_20.23.28.zip)

**Comment by Tmhgutsun** [comment]
> Please attach the crashlog or the mod folder.

[Crash_report-2024-9-12_20.23.28.zip](https://github.com/user-attachments/files/16979154/Crash_report-2024-9-12_20.23.28.zip)

**Comment by thetheaplant** [comment]
Can you attach the mod folder, there is not crashlog in that file.

**Comment by Tmhgutsun** [comment]
> Can you attach the mod folder, there is not crashlog in that file.

[mod.zip](https://github.com/user-attachments/files/17013108/mod.zip)
[错误报告-2024-9-16_20.24.59.zip](https://github.com/user-attachments/files/17013111/-2024-9-16_20.24.59.zip)
Original and latest Chinese ver. file,launched by PCL2 launcher

**Comment by thetheaplant** [comment]
I was unable to replicate this issue, the mods.toml file seems to be correct. Make sure you have all dependencies, like kotlin. I would recommend using Curseforge or Modrinth to automatically install them.

**Comment by thetheaplant** [comment]
Closing as I am unable to recreate this issue, feel free to report any other issues or join the discord server.
