### ISSUE TITLE
""Burger Factory"" issues with Embeddium

### ISSUE THREAD

**Issue by AverageUser67** [ValkyrienSkies/Valkyrien-Skies-2#964]
### Mod Name

Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The Embeddium renderer reloads constantly when you have VS2 installed, caused by the Burger Factory... whatever that is.

### Issue reproduction

1. Install VS2 and Embeddium latest from CurseForge
2. Load into a new world
3. Epilepsy

### Logs

[debug.log](https://github.com/user-attachments/files/17091372/debug.log)
[latest.log](https://github.com/user-attachments/files/17091374/latest.log)

**Comment by thetheaplant** [comment]
Unable to recreate with VS beta.5 and Embeddium 0.3.31.

**Comment by thetheaplant** [comment]
Another one of your mods is conflicting, not a VS issue. Make sure the issue only happens with VS and the problematic mod installed.
