### ISSUE TITLE
Add different gravity for each dimension

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Valkyrien-Skies-2#967]

**Comment by StewStrong** [comment]
Done in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/686bd75c6fe996d7c7ec8a0ca33d31a830eb3fc6

**Comment by sentialx** [comment]
@StewStrong Can this gravity be modified locally to a ship the player is inside? E.g. when the ship is rotated upside down (roll) and I want to specify where the floor is
