### ISSUE TITLE
Really weird...

### ISSUE THREAD

**Issue by Leonithass** [ValkyrienSkies/Valkyrien-Skies-2#979]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The game crushed when I tried to open my save.

### Issue reproduction

Install forge 1.20.1 47.3.0, then open a save, the game crushes.

### Logs

[debug.log](https://github.com/user-attachments/files/17254602/debug.log)
[latest.log](https://github.com/user-attachments/files/17254609/latest.log)

**Comment by thetheaplant** [comment]
What device are you running this on? Windows on Arm is not technically supported.

**Comment by Leonithass** [comment]
> What device are you running this on? Windows on Arm is not technically supported.

Mine is exactly windows on arm...

**Comment by thetheaplant** [comment]
do you have a crash report you can send?

**Comment by Leonithass** [comment]
> do you have a crash report you can send?
[crash-2024-10-05_10.22.47-server.txt](https://github.com/user-attachments/files/17264825/crash-2024-10-05_10.22.47-server.txt)

**Comment by thetheaplant** [comment]
Unfortunately there does not appear to be much we can do to fix that, you may consider moving to a standard architecture, or wait until GlibC is cross-compiled for windows on arm.

**Comment by Leonithass** [comment]
> Unfortunately there does not appear to be much we can do to fix that, you may consider moving to a standard architecture, or wait until GlibC is cross-compiled for windows on arm.

Ok. But what is GlibC ?

**Comment by thetheaplant** [comment]
msvcrt is the technical version windows uses, essentially it provides useful functions relating to direct memory access for VS2's physics engine; Krunch. Without it present, Krunch cannot access the memory.

**Comment by Leonithass** [comment]
> msvcrt is the technical version windows uses, essentially it provides useful functions relating to direct memory access for VS2's physics engine; Krunch. Without it present, Krunch cannot access the memory.

OK, thanks =)

**Comment by thetheaplant** [comment]
OS incompatibility, unfixable.
