### ISSUE TITLE
Enter the server, and Minecraft crashes

### ISSUE THREAD

**Issue by Yummy-cookie** [ValkyrienSkies/Valkyrien-Skies-2#983]
[crash-2024-10-13_08.36.35-client.txt](https://github.com/user-attachments/files/17352595/crash-2024-10-13_08.36.35-client.txt)

**Comment by thetheaplant** [comment]
Check the compatibility list at https://wiki.valkyrienskies.org/wiki/Compatibility_list, and if no mods listed are present, perform a binary search or remove mods until it works. The issues tab is not meant for troubleshooting modpacks.

**Comment by thetheaplant** [comment]
Forgematica issue, closing in favor of #906
