### ISSUE TITLE
Incompatability with Spartain Weaponry. 

### ISSUE THREAD

**Issue by BroHawkMC** [ValkyrienSkies/Valkyrien-Skies-2#985]
### Mod Name

Spartain weaponry

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Game crashed on launch.

### Issue reproduction

Launch the game with Valk, create, clockwork, and spartan weaponry installed. Disabling Valk and clockwork allows the game to launch. 

### Logs

[latest.log](https://github.com/user-attachments/files/17368017/latest.log)

There was no debug.log file.

**Comment by thetheaplant** [comment]
@BroHawkMC was the issue resolved on spartan weaponary's end?
