### ISSUE TITLE
<title> Tetra Dupe Glitch

### ISSUE THREAD

**Issue by Billnotic** [ValkyrienSkies/Valkyrien-Skies-2#991]
### Mod Name

Tetra

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

If you turn a tetra workbench into a physics object, it will throw off the item on the bench as if it were broken. However, the bench that is now a physics object keeps the item, effectively duping it.

### Issue reproduction

Turn a tetra basic_workbench into part of physics object.

**Comment by thetheaplant** [comment]
Fixed in  #878
