### ISSUE TITLE
<title>the value "ship" is changed?

### ISSUE THREAD

**Issue by Annypst** [ValkyrienSkies/Valkyrien-Skies-2#994]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

we want to messure the value "ship" to get the information of the ship,but it is worse.
![image](https://github.com/user-attachments/assets/b45d4f49-5898-46f4-954e-e64906d57bae)

### Issue reproduction

i use computer craft mod to write a code

### Logs

ship.setScale(1) is worst

**Comment by thetheaplant** [comment]
You have an issue with your mods or config, additionally this is not a vs issue.
