### ISSUE TITLE
Crash upon starting up minecraft server

### ISSUE THREAD

**Issue by PortalFan15** [ValkyrienSkies/Valkyrien-Skies-2#998]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When the server is launched it gives an error.

### Issue reproduction

1. Download forge-1.20.1-47.3.0-installer.jar
2. Check install server
3. set eula to true
4. Add latest version of mod to mod folder
5. run run.bat

### Logs

[debug.log](https://github.com/user-attachments/files/17640369/debug.log)
[latest.log](https://github.com/user-attachments/files/17640370/latest.log)

**Comment by thetheaplant** [comment]
VS requires kotlin to work.
